/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

import * as import0 from '@angular/core/src/render/api';
import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/linker/element';
import * as import3 from './addNewsModal';
import * as import4 from '@angular/core/src/linker/view_utils';
import * as import5 from '@angular/core/src/di/injector';
import * as import6 from '@angular/core/src/linker/view_type';
import * as import7 from '@angular/core/src/change_detection/change_detection';
import * as import8 from '@angular/http/src/http';
import * as import9 from '../../../services/ModalService';
import * as import10 from '../../../services/LocalizationService';
import * as import11 from '../../../services/UserInformationService';
import * as import12 from '@angular/core/src/metadata/view';
import * as import13 from '@angular/core/src/linker/component_factory';
import * as import14 from '@angular/forms/src/directives/ng_form';
import * as import15 from '@angular/forms/src/directives/ng_control_status';
import * as import16 from '@angular/forms/src/directives/select_control_value_accessor';
import * as import17 from '@angular/forms/src/directives/select_multiple_control_value_accessor';
import * as import18 from '@angular/core/src/linker/element_ref';
import * as import19 from '@angular/forms/src/directives/control_container';
var renderType_AddNewsModal_Host:import0.RenderComponentType = (null as any);
class _View_AddNewsModal_Host0 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import2.AppElement;
  _AddNewsModal_0_4:import3.AddNewsModal;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_AddNewsModal_Host0,renderType_AddNewsModal_Host,import6.ViewType.HOST,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.selectOrCreateHostElement('add-news-modal',rootSelector,(null as any));
    this._appEl_0 = new import2.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = viewFactory_AddNewsModal0(this.viewUtils,this.injector(0),this._appEl_0);
    this._AddNewsModal_0_4 = new import3.AddNewsModal(this.parentInjector.get(import8.Http),this.parentInjector.get(import9.ModalService),this.parentInjector.get(import10.LocalizationService),this.parentInjector.get(import11.UserInformationService));
    this._appEl_0.initComponent(this._AddNewsModal_0_4,[],compView_0);
    compView_0.create(this._AddNewsModal_0_4,this.projectableNodes,(null as any));
    this.init([].concat([this._el_0]),[this._el_0],[],[]);
    return this._appEl_0;
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import3.AddNewsModal) && (0 === requestNodeIndex))) { return this._AddNewsModal_0_4; }
    return notFoundResult;
  }
}
function viewFactory_AddNewsModal_Host0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  if ((renderType_AddNewsModal_Host === (null as any))) { (renderType_AddNewsModal_Host = viewUtils.createRenderComponentType('',0,import12.ViewEncapsulation.None,[],{})); }
  return new _View_AddNewsModal_Host0(viewUtils,parentInjector,declarationEl);
}
export const AddNewsModalNgFactory:import13.ComponentFactory<import3.AddNewsModal> = new import13.ComponentFactory<import3.AddNewsModal>('add-news-modal',viewFactory_AddNewsModal_Host0,import3.AddNewsModal);
const styles_AddNewsModal:any[] = [];
var renderType_AddNewsModal:import0.RenderComponentType = (null as any);
class _View_AddNewsModal0 extends import1.AppView<import3.AddNewsModal> {
  _el_0:any;
  _text_1:any;
  _el_2:any;
  _text_3:any;
  _text_4:any;
  _el_5:any;
  _text_6:any;
  _el_7:any;
  _text_8:any;
  _el_9:any;
  _text_10:any;
  _el_11:any;
  _text_12:any;
  _text_13:any;
  _text_14:any;
  _el_15:any;
  _text_16:any;
  _text_17:any;
  _text_18:any;
  _el_19:any;
  _text_20:any;
  _el_21:any;
  _NgForm_21_3:import14.NgForm;
  _ControlContainer_21_4:any;
  _NgControlStatusGroup_21_5:import15.NgControlStatusGroup;
  _text_22:any;
  _el_23:any;
  _text_24:any;
  _text_25:any;
  _el_26:any;
  _text_27:any;
  _el_28:any;
  _text_29:any;
  _el_30:any;
  _text_31:any;
  _el_32:any;
  _el_33:any;
  _text_34:any;
  _text_35:any;
  _el_36:any;
  _el_37:any;
  _text_38:any;
  _text_39:any;
  _text_40:any;
  _text_41:any;
  _el_42:any;
  _text_43:any;
  _el_44:any;
  _text_45:any;
  _el_46:any;
  _NgSelectOption_46_3:import16.NgSelectOption;
  _NgSelectMultipleOption_46_4:import17.NgSelectMultipleOption;
  _text_47:any;
  _text_48:any;
  _el_49:any;
  _NgSelectOption_49_3:import16.NgSelectOption;
  _NgSelectMultipleOption_49_4:import17.NgSelectMultipleOption;
  _text_50:any;
  _text_51:any;
  _el_52:any;
  _NgSelectOption_52_3:import16.NgSelectOption;
  _NgSelectMultipleOption_52_4:import17.NgSelectMultipleOption;
  _text_53:any;
  _text_54:any;
  _el_55:any;
  _NgSelectOption_55_3:import16.NgSelectOption;
  _NgSelectMultipleOption_55_4:import17.NgSelectMultipleOption;
  _text_56:any;
  _text_57:any;
  _el_58:any;
  _NgSelectOption_58_3:import16.NgSelectOption;
  _NgSelectMultipleOption_58_4:import17.NgSelectMultipleOption;
  _text_59:any;
  _text_60:any;
  _text_61:any;
  _text_62:any;
  _text_63:any;
  _el_64:any;
  _text_65:any;
  _text_66:any;
  _el_67:any;
  _text_68:any;
  _el_69:any;
  _text_70:any;
  _el_71:any;
  _text_72:any;
  _el_73:any;
  _text_74:any;
  _text_75:any;
  _text_76:any;
  _text_77:any;
  _el_78:any;
  _text_79:any;
  _el_80:any;
  _text_81:any;
  _el_82:any;
  _text_83:any;
  _el_84:any;
  _text_85:any;
  _text_86:any;
  _el_87:any;
  _text_88:any;
  _el_89:any;
  _text_90:any;
  _el_91:any;
  _text_92:any;
  _el_93:any;
  _el_94:any;
  _text_95:any;
  _text_96:any;
  _text_97:any;
  _el_98:any;
  _text_99:any;
  _el_100:any;
  _text_101:any;
  _text_102:any;
  _el_103:any;
  _text_104:any;
  _el_105:any;
  _text_106:any;
  _text_107:any;
  _el_108:any;
  _text_109:any;
  _el_110:any;
  _text_111:any;
  _text_112:any;
  _el_113:any;
  _text_114:any;
  _el_115:any;
  _text_116:any;
  _text_117:any;
  _el_118:any;
  _text_119:any;
  _el_120:any;
  _text_121:any;
  _text_122:any;
  _el_123:any;
  _text_124:any;
  _el_125:any;
  _text_126:any;
  _text_127:any;
  _text_128:any;
  _el_129:any;
  _text_130:any;
  _el_131:any;
  _text_132:any;
  _text_133:any;
  _el_134:any;
  _text_135:any;
  _el_136:any;
  _text_137:any;
  _text_138:any;
  _el_139:any;
  _text_140:any;
  _el_141:any;
  _text_142:any;
  _text_143:any;
  _text_144:any;
  _text_145:any;
  _text_146:any;
  _el_147:any;
  _text_148:any;
  _el_149:any;
  _text_150:any;
  _text_151:any;
  _text_152:any;
  _text_153:any;
  _text_154:any;
  _text_155:any;
  _el_156:any;
  _text_157:any;
  _el_158:any;
  _text_159:any;
  _el_160:any;
  _text_161:any;
  _el_162:any;
  _text_163:any;
  _el_164:any;
  _text_165:any;
  _text_166:any;
  _text_167:any;
  _text_168:any;
  _el_169:any;
  _text_170:any;
  _el_171:any;
  _text_172:any;
  _el_173:any;
  _text_174:any;
  _el_175:any;
  _text_176:any;
  _text_177:any;
  _text_178:any;
  _text_179:any;
  _text_180:any;
  _el_181:any;
  _text_182:any;
  _text_183:any;
  _el_184:any;
  _text_185:any;
  _el_186:any;
  _text_187:any;
  _el_188:any;
  _text_189:any;
  _el_190:any;
  _text_191:any;
  _el_192:any;
  _text_193:any;
  _el_194:any;
  _text_195:any;
  _el_196:any;
  _text_197:any;
  _el_198:any;
  _text_199:any;
  _el_200:any;
  _text_201:any;
  _el_202:any;
  _text_203:any;
  _el_204:any;
  _text_205:any;
  _text_206:any;
  _text_207:any;
  _text_208:any;
  _el_209:any;
  _text_210:any;
  _el_211:any;
  _text_212:any;
  _el_213:any;
  _text_214:any;
  _text_215:any;
  _text_216:any;
  _text_217:any;
  _text_218:any;
  _text_219:any;
  _el_220:any;
  _text_221:any;
  _el_222:any;
  _text_223:any;
  _el_224:any;
  _text_225:any;
  _el_226:any;
  _text_227:any;
  _el_228:any;
  _text_229:any;
  _text_230:any;
  _text_231:any;
  _el_232:any;
  _text_233:any;
  _el_234:any;
  _text_235:any;
  _text_236:any;
  _text_237:any;
  _el_238:any;
  _text_239:any;
  _el_240:any;
  _text_241:any;
  _text_242:any;
  _text_243:any;
  _el_244:any;
  _text_245:any;
  _el_246:any;
  _text_247:any;
  _text_248:any;
  _text_249:any;
  _text_250:any;
  _text_251:any;
  _text_252:any;
  _text_253:any;
  _text_254:any;
  _text_255:any;
  _text_256:any;
  /*private*/ _expr_4:any;
  /*private*/ _expr_5:any;
  /*private*/ _expr_6:any;
  /*private*/ _expr_7:any;
  /*private*/ _expr_8:any;
  /*private*/ _expr_9:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_AddNewsModal0,renderType_AddNewsModal,import6.ViewType.COMPONENT,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    const parentRenderNode:any = this.renderer.createViewRoot(this.declarationAppElement.nativeElement);
    this._el_0 = this.renderer.createElement(parentRenderNode,'div',(null as any));
    this.renderer.setElementAttribute(this._el_0,'aria-labelledby','exampleModalLabel');
    this.renderer.setElementAttribute(this._el_0,'class','modal');
    this.renderer.setElementAttribute(this._el_0,'id','exampleModal');
    this.renderer.setElementAttribute(this._el_0,'role','dialog');
    this.renderer.setElementAttribute(this._el_0,'tabindex','-1');
    this._text_1 = this.renderer.createText(this._el_0,'\n  ',(null as any));
    this._el_2 = this.renderer.createElement(this._el_0,'div',(null as any));
    this.renderer.setElementAttribute(this._el_2,'class','modal-dialog');
    this.renderer.setElementAttribute(this._el_2,'role','document');
    this._text_3 = this.renderer.createText(this._el_2,'\n    ',(null as any));
    this._text_4 = this.renderer.createText(this._el_2,'\n    ',(null as any));
    this._el_5 = this.renderer.createElement(this._el_2,'div',(null as any));
    this.renderer.setElementAttribute(this._el_5,'class','modal-content news-create news-create-guide');
    this._text_6 = this.renderer.createText(this._el_5,'\n      ',(null as any));
    this._el_7 = this.renderer.createElement(this._el_5,'div',(null as any));
    this.renderer.setElementAttribute(this._el_7,'class','modal-header');
    this._text_8 = this.renderer.createText(this._el_7,'\n        ',(null as any));
    this._el_9 = this.renderer.createElement(this._el_7,'button',(null as any));
    this.renderer.setElementAttribute(this._el_9,'aria-label','Close');
    this.renderer.setElementAttribute(this._el_9,'class','close');
    this.renderer.setElementAttribute(this._el_9,'type','button');
    this._text_10 = this.renderer.createText(this._el_9,'\n          ',(null as any));
    this._el_11 = this.renderer.createElement(this._el_9,'span',(null as any));
    this.renderer.setElementAttribute(this._el_11,'aria-hidden','true');
    this._text_12 = this.renderer.createText(this._el_11,'×',(null as any));
    this._text_13 = this.renderer.createText(this._el_9,'\n        ',(null as any));
    this._text_14 = this.renderer.createText(this._el_7,'\n        ',(null as any));
    this._el_15 = this.renderer.createElement(this._el_7,'h1',(null as any));
    this.renderer.setElementAttribute(this._el_15,'class','modal-title');
    this._text_16 = this.renderer.createText(this._el_15,'Создать публикацию',(null as any));
    this._text_17 = this.renderer.createText(this._el_7,'\n      ',(null as any));
    this._text_18 = this.renderer.createText(this._el_5,'\n      ',(null as any));
    this._el_19 = this.renderer.createElement(this._el_5,'div',(null as any));
    this.renderer.setElementAttribute(this._el_19,'class','modal-body');
    this._text_20 = this.renderer.createText(this._el_19,'\n        ',(null as any));
    this._el_21 = this.renderer.createElement(this._el_19,'form',(null as any));
    this._NgForm_21_3 = new import14.NgForm((null as any),(null as any));
    this._ControlContainer_21_4 = this._NgForm_21_3;
    this._NgControlStatusGroup_21_5 = new import15.NgControlStatusGroup(this._ControlContainer_21_4);
    this._text_22 = this.renderer.createText(this._el_21,'\n          ',(null as any));
    this._el_23 = this.renderer.createElement(this._el_21,'h3',(null as any));
    this.renderer.setElementAttribute(this._el_23,'class','mt-1');
    this._text_24 = this.renderer.createText(this._el_23,'Категория',(null as any));
    this._text_25 = this.renderer.createText(this._el_21,'\n          ',(null as any));
    this._el_26 = this.renderer.createElement(this._el_21,'div',(null as any));
    this.renderer.setElementAttribute(this._el_26,'class','row');
    this._text_27 = this.renderer.createText(this._el_26,'\n            ',(null as any));
    this._el_28 = this.renderer.createElement(this._el_26,'div',(null as any));
    this.renderer.setElementAttribute(this._el_28,'class','col-md-3');
    this._text_29 = this.renderer.createText(this._el_28,'\n              ',(null as any));
    this._el_30 = this.renderer.createElement(this._el_28,'ul',(null as any));
    this.renderer.setElementAttribute(this._el_30,'class','nav nav-pills selector');
    this._text_31 = this.renderer.createText(this._el_30,'\n                ',(null as any));
    this._el_32 = this.renderer.createElement(this._el_30,'li',(null as any));
    this.renderer.setElementAttribute(this._el_32,'class','active');
    this.renderer.setElementAttribute(this._el_32,'role','presentation');
    this._el_33 = this.renderer.createElement(this._el_32,'a',(null as any));
    this.renderer.setElementAttribute(this._el_33,'class','link');
    this._text_34 = this.renderer.createText(this._el_33,'Home',(null as any));
    this._text_35 = this.renderer.createText(this._el_30,'\n                ',(null as any));
    this._el_36 = this.renderer.createElement(this._el_30,'li',(null as any));
    this.renderer.setElementAttribute(this._el_36,'role','presentation');
    this._el_37 = this.renderer.createElement(this._el_36,'a',(null as any));
    this.renderer.setElementAttribute(this._el_37,'class','link');
    this._text_38 = this.renderer.createText(this._el_37,'Profile',(null as any));
    this._text_39 = this.renderer.createText(this._el_30,'\n              ',(null as any));
    this._text_40 = this.renderer.createText(this._el_28,'\n            ',(null as any));
    this._text_41 = this.renderer.createText(this._el_26,'\n            ',(null as any));
    this._el_42 = this.renderer.createElement(this._el_26,'div',(null as any));
    this.renderer.setElementAttribute(this._el_42,'class','col-md-9');
    this._text_43 = this.renderer.createText(this._el_42,'\n              ',(null as any));
    this._el_44 = this.renderer.createElement(this._el_42,'select',(null as any));
    this.renderer.setElementAttribute(this._el_44,'class','form-control');
    this._text_45 = this.renderer.createText(this._el_44,'\n                ',(null as any));
    this._el_46 = this.renderer.createElement(this._el_44,'option',(null as any));
    this._NgSelectOption_46_3 = new import16.NgSelectOption(new import18.ElementRef(this._el_46),this.renderer,(null as any));
    this._NgSelectMultipleOption_46_4 = new import17.NgSelectMultipleOption(new import18.ElementRef(this._el_46),this.renderer,(null as any));
    this._text_47 = this.renderer.createText(this._el_46,'Выберите тематику публикации',(null as any));
    this._text_48 = this.renderer.createText(this._el_44,'\n                ',(null as any));
    this._el_49 = this.renderer.createElement(this._el_44,'option',(null as any));
    this._NgSelectOption_49_3 = new import16.NgSelectOption(new import18.ElementRef(this._el_49),this.renderer,(null as any));
    this._NgSelectMultipleOption_49_4 = new import17.NgSelectMultipleOption(new import18.ElementRef(this._el_49),this.renderer,(null as any));
    this._text_50 = this.renderer.createText(this._el_49,'публикация 1',(null as any));
    this._text_51 = this.renderer.createText(this._el_44,'\n                ',(null as any));
    this._el_52 = this.renderer.createElement(this._el_44,'option',(null as any));
    this._NgSelectOption_52_3 = new import16.NgSelectOption(new import18.ElementRef(this._el_52),this.renderer,(null as any));
    this._NgSelectMultipleOption_52_4 = new import17.NgSelectMultipleOption(new import18.ElementRef(this._el_52),this.renderer,(null as any));
    this._text_53 = this.renderer.createText(this._el_52,'публикация 2',(null as any));
    this._text_54 = this.renderer.createText(this._el_44,'\n                ',(null as any));
    this._el_55 = this.renderer.createElement(this._el_44,'option',(null as any));
    this._NgSelectOption_55_3 = new import16.NgSelectOption(new import18.ElementRef(this._el_55),this.renderer,(null as any));
    this._NgSelectMultipleOption_55_4 = new import17.NgSelectMultipleOption(new import18.ElementRef(this._el_55),this.renderer,(null as any));
    this._text_56 = this.renderer.createText(this._el_55,'публикация 3',(null as any));
    this._text_57 = this.renderer.createText(this._el_44,'\n                ',(null as any));
    this._el_58 = this.renderer.createElement(this._el_44,'option',(null as any));
    this._NgSelectOption_58_3 = new import16.NgSelectOption(new import18.ElementRef(this._el_58),this.renderer,(null as any));
    this._NgSelectMultipleOption_58_4 = new import17.NgSelectMultipleOption(new import18.ElementRef(this._el_58),this.renderer,(null as any));
    this._text_59 = this.renderer.createText(this._el_58,'публикация 4',(null as any));
    this._text_60 = this.renderer.createText(this._el_44,'\n              ',(null as any));
    this._text_61 = this.renderer.createText(this._el_42,'\n            ',(null as any));
    this._text_62 = this.renderer.createText(this._el_26,'\n          ',(null as any));
    this._text_63 = this.renderer.createText(this._el_21,'\n\n          ',(null as any));
    this._el_64 = this.renderer.createElement(this._el_21,'h3',(null as any));
    this.renderer.setElementAttribute(this._el_64,'class','mt-1');
    this._text_65 = this.renderer.createText(this._el_64,'Заглавие',(null as any));
    this._text_66 = this.renderer.createText(this._el_21,'\n          ',(null as any));
    this._el_67 = this.renderer.createElement(this._el_21,'div',(null as any));
    this.renderer.setElementAttribute(this._el_67,'class','row');
    this._text_68 = this.renderer.createText(this._el_67,'\n            ',(null as any));
    this._el_69 = this.renderer.createElement(this._el_67,'div',(null as any));
    this.renderer.setElementAttribute(this._el_69,'class','col-lg-12');
    this._text_70 = this.renderer.createText(this._el_69,'\n              ',(null as any));
    this._el_71 = this.renderer.createElement(this._el_69,'div',(null as any));
    this.renderer.setElementAttribute(this._el_71,'class','form-group');
    this._text_72 = this.renderer.createText(this._el_71,'\n                ',(null as any));
    this._el_73 = this.renderer.createElement(this._el_71,'input',(null as any));
    this.renderer.setElementAttribute(this._el_73,'class','form-control');
    this.renderer.setElementAttribute(this._el_73,'type','text');
    this._text_74 = this.renderer.createText(this._el_71,'\n              ',(null as any));
    this._text_75 = this.renderer.createText(this._el_69,'\n            ',(null as any));
    this._text_76 = this.renderer.createText(this._el_67,'\n          ',(null as any));
    this._text_77 = this.renderer.createText(this._el_21,'\n\n          ',(null as any));
    this._el_78 = this.renderer.createElement(this._el_21,'div',(null as any));
    this.renderer.setElementAttribute(this._el_78,'class','row');
    this._text_79 = this.renderer.createText(this._el_78,'\n            ',(null as any));
    this._el_80 = this.renderer.createElement(this._el_78,'div',(null as any));
    this.renderer.setElementAttribute(this._el_80,'class','col-md-12');
    this._text_81 = this.renderer.createText(this._el_80,'\n              ',(null as any));
    this._el_82 = this.renderer.createElement(this._el_80,'div',(null as any));
    this.renderer.setElementAttribute(this._el_82,'class','panel panel-primary mt-1');
    this._text_83 = this.renderer.createText(this._el_82,'\n                ',(null as any));
    this._el_84 = this.renderer.createElement(this._el_82,'h3',(null as any));
    this.renderer.setElementAttribute(this._el_84,'class','pull-left');
    this._text_85 = this.renderer.createText(this._el_84,'Текст публикации',(null as any));
    this._text_86 = this.renderer.createText(this._el_82,'\n                ',(null as any));
    this._el_87 = this.renderer.createElement(this._el_82,'div',(null as any));
    this.renderer.setElementAttribute(this._el_87,'class','panel-heading pull-right');
    this._text_88 = this.renderer.createText(this._el_87,'\n                  ',(null as any));
    this._el_89 = this.renderer.createElement(this._el_87,'div',(null as any));
    this.renderer.setElementAttribute(this._el_89,'class','inline-block');
    this._text_90 = this.renderer.createText(this._el_89,'\n                    ',(null as any));
    this._el_91 = this.renderer.createElement(this._el_89,'button',(null as any));
    this.renderer.setElementAttribute(this._el_91,'class','btn btn-default btn-sm');
    this.renderer.setElementAttribute(this._el_91,'data-toggle','tooltip');
    this.renderer.setElementAttribute(this._el_91,'title','Add article');
    this.renderer.setElementAttribute(this._el_91,'type','button');
    this._text_92 = this.renderer.createText(this._el_91,'\n                      ',(null as any));
    this._el_93 = this.renderer.createElement(this._el_91,'i',(null as any));
    this.renderer.setElementAttribute(this._el_93,'class','fa fa-plus');
    this._el_94 = this.renderer.createElement(this._el_91,'span',(null as any));
    this._text_95 = this.renderer.createText(this._el_94,'Добавить главу',(null as any));
    this._text_96 = this.renderer.createText(this._el_91,'\n                    ',(null as any));
    this._text_97 = this.renderer.createText(this._el_89,'\n                    ',(null as any));
    this._el_98 = this.renderer.createElement(this._el_89,'button',(null as any));
    this.renderer.setElementAttribute(this._el_98,'class','btn btn-default btn-sm');
    this.renderer.setElementAttribute(this._el_98,'data-toggle','tooltip');
    this.renderer.setElementAttribute(this._el_98,'title','camera');
    this.renderer.setElementAttribute(this._el_98,'type','button');
    this._text_99 = this.renderer.createText(this._el_98,'\n                      ',(null as any));
    this._el_100 = this.renderer.createElement(this._el_98,'i',(null as any));
    this.renderer.setElementAttribute(this._el_100,'class','fa fa-camera');
    this._text_101 = this.renderer.createText(this._el_98,'\n                    ',(null as any));
    this._text_102 = this.renderer.createText(this._el_89,'\n                    ',(null as any));
    this._el_103 = this.renderer.createElement(this._el_89,'button',(null as any));
    this.renderer.setElementAttribute(this._el_103,'class','btn btn-default btn-sm');
    this.renderer.setElementAttribute(this._el_103,'data-toggle','tooltip');
    this.renderer.setElementAttribute(this._el_103,'title','music');
    this.renderer.setElementAttribute(this._el_103,'type','button');
    this._text_104 = this.renderer.createText(this._el_103,'\n                      ',(null as any));
    this._el_105 = this.renderer.createElement(this._el_103,'i',(null as any));
    this.renderer.setElementAttribute(this._el_105,'class','fa fa-music');
    this._text_106 = this.renderer.createText(this._el_103,'\n                    ',(null as any));
    this._text_107 = this.renderer.createText(this._el_89,'\n                    ',(null as any));
    this._el_108 = this.renderer.createElement(this._el_89,'button',(null as any));
    this.renderer.setElementAttribute(this._el_108,'class','btn btn-default btn-sm');
    this.renderer.setElementAttribute(this._el_108,'data-toggle','tooltip');
    this.renderer.setElementAttribute(this._el_108,'title','film');
    this.renderer.setElementAttribute(this._el_108,'type','button');
    this._text_109 = this.renderer.createText(this._el_108,'\n                      ',(null as any));
    this._el_110 = this.renderer.createElement(this._el_108,'i',(null as any));
    this.renderer.setElementAttribute(this._el_110,'aria-hidden','true');
    this.renderer.setElementAttribute(this._el_110,'class','fa fa-film');
    this._text_111 = this.renderer.createText(this._el_108,'\n                    ',(null as any));
    this._text_112 = this.renderer.createText(this._el_89,'\n                    ',(null as any));
    this._el_113 = this.renderer.createElement(this._el_89,'button',(null as any));
    this.renderer.setElementAttribute(this._el_113,'class','btn btn-default btn-sm');
    this.renderer.setElementAttribute(this._el_113,'data-toggle','tooltip');
    this.renderer.setElementAttribute(this._el_113,'title','Bold');
    this.renderer.setElementAttribute(this._el_113,'type','button');
    this._text_114 = this.renderer.createText(this._el_113,'\n                      ',(null as any));
    this._el_115 = this.renderer.createElement(this._el_113,'i',(null as any));
    this.renderer.setElementAttribute(this._el_115,'class','fa fa-bold');
    this._text_116 = this.renderer.createText(this._el_113,'\n                    ',(null as any));
    this._text_117 = this.renderer.createText(this._el_89,'\n                    ',(null as any));
    this._el_118 = this.renderer.createElement(this._el_89,'button',(null as any));
    this.renderer.setElementAttribute(this._el_118,'class','btn btn-default btn-sm');
    this.renderer.setElementAttribute(this._el_118,'data-toggle','tooltip');
    this.renderer.setElementAttribute(this._el_118,'title','Italic');
    this.renderer.setElementAttribute(this._el_118,'type','button');
    this._text_119 = this.renderer.createText(this._el_118,'\n                      ',(null as any));
    this._el_120 = this.renderer.createElement(this._el_118,'i',(null as any));
    this.renderer.setElementAttribute(this._el_120,'class','fa fa-italic');
    this._text_121 = this.renderer.createText(this._el_118,'\n                    ',(null as any));
    this._text_122 = this.renderer.createText(this._el_89,'\n                    ',(null as any));
    this._el_123 = this.renderer.createElement(this._el_89,'button',(null as any));
    this.renderer.setElementAttribute(this._el_123,'class','btn btn-default btn-sm');
    this.renderer.setElementAttribute(this._el_123,'data-toggle','tooltip');
    this.renderer.setElementAttribute(this._el_123,'title','Underline');
    this.renderer.setElementAttribute(this._el_123,'type','button');
    this._text_124 = this.renderer.createText(this._el_123,'\n                      ',(null as any));
    this._el_125 = this.renderer.createElement(this._el_123,'i',(null as any));
    this.renderer.setElementAttribute(this._el_125,'class','fa fa-underline');
    this._text_126 = this.renderer.createText(this._el_123,'\n                    ',(null as any));
    this._text_127 = this.renderer.createText(this._el_89,'\n                    ',(null as any));
    this._text_128 = this.renderer.createText(this._el_89,'\n                    ',(null as any));
    this._el_129 = this.renderer.createElement(this._el_89,'button',(null as any));
    this.renderer.setElementAttribute(this._el_129,'class','btn btn-default btn-sm');
    this.renderer.setElementAttribute(this._el_129,'data-toggle','tooltip');
    this.renderer.setElementAttribute(this._el_129,'title','Bulleted list');
    this.renderer.setElementAttribute(this._el_129,'type','button');
    this._text_130 = this.renderer.createText(this._el_129,'\n                      ',(null as any));
    this._el_131 = this.renderer.createElement(this._el_129,'i',(null as any));
    this.renderer.setElementAttribute(this._el_131,'class','fa fa-list-ul');
    this._text_132 = this.renderer.createText(this._el_129,'\n                    ',(null as any));
    this._text_133 = this.renderer.createText(this._el_89,'\n                    ',(null as any));
    this._el_134 = this.renderer.createElement(this._el_89,'button',(null as any));
    this.renderer.setElementAttribute(this._el_134,'class','btn btn-default btn-sm');
    this.renderer.setElementAttribute(this._el_134,'data-toggle','tooltip');
    this.renderer.setElementAttribute(this._el_134,'title','Link');
    this.renderer.setElementAttribute(this._el_134,'type','button');
    this._text_135 = this.renderer.createText(this._el_134,'\n                      ',(null as any));
    this._el_136 = this.renderer.createElement(this._el_134,'i',(null as any));
    this.renderer.setElementAttribute(this._el_136,'class','fa fa-link');
    this._text_137 = this.renderer.createText(this._el_134,'\n                    ',(null as any));
    this._text_138 = this.renderer.createText(this._el_89,'\n                    ',(null as any));
    this._el_139 = this.renderer.createElement(this._el_89,'button',(null as any));
    this.renderer.setElementAttribute(this._el_139,'class','btn btn-default btn-sm');
    this.renderer.setElementAttribute(this._el_139,'data-toggle','tooltip');
    this.renderer.setElementAttribute(this._el_139,'title','Unlink');
    this.renderer.setElementAttribute(this._el_139,'type','button');
    this._text_140 = this.renderer.createText(this._el_139,'\n                      ',(null as any));
    this._el_141 = this.renderer.createElement(this._el_139,'i',(null as any));
    this.renderer.setElementAttribute(this._el_141,'class','fa fa-unlink');
    this._text_142 = this.renderer.createText(this._el_139,'\n                    ',(null as any));
    this._text_143 = this.renderer.createText(this._el_89,'\n                  ',(null as any));
    this._text_144 = this.renderer.createText(this._el_87,'\n                  ',(null as any));
    this._text_145 = this.renderer.createText(this._el_87,'\n                ',(null as any));
    this._text_146 = this.renderer.createText(this._el_82,'\n                ',(null as any));
    this._el_147 = this.renderer.createElement(this._el_82,'div',(null as any));
    this.renderer.setElementAttribute(this._el_147,'class','panel-body');
    this._text_148 = this.renderer.createText(this._el_147,'\n                  ',(null as any));
    this._el_149 = this.renderer.createElement(this._el_147,'textarea',(null as any));
    this._text_150 = this.renderer.createText(this._el_149,'Lorem ipsum dolor sit amet',(null as any));
    this._text_151 = this.renderer.createText(this._el_147,'\n                ',(null as any));
    this._text_152 = this.renderer.createText(this._el_82,'\n              ',(null as any));
    this._text_153 = this.renderer.createText(this._el_80,'\n            ',(null as any));
    this._text_154 = this.renderer.createText(this._el_78,'\n          ',(null as any));
    this._text_155 = this.renderer.createText(this._el_21,'\n          ',(null as any));
    this._el_156 = this.renderer.createElement(this._el_21,'div',(null as any));
    this.renderer.setElementAttribute(this._el_156,'class','row');
    this._text_157 = this.renderer.createText(this._el_156,'\n            ',(null as any));
    this._el_158 = this.renderer.createElement(this._el_156,'div',(null as any));
    this.renderer.setElementAttribute(this._el_158,'class','col-lg-6');
    this._text_159 = this.renderer.createText(this._el_158,'\n              ',(null as any));
    this._el_160 = this.renderer.createElement(this._el_158,'div',(null as any));
    this.renderer.setElementAttribute(this._el_160,'class','form-group ');
    this._text_161 = this.renderer.createText(this._el_160,'\n                ',(null as any));
    this._el_162 = this.renderer.createElement(this._el_160,'input',(null as any));
    this.renderer.setElementAttribute(this._el_162,'checked','checked');
    this.renderer.setElementAttribute(this._el_162,'id','check-1');
    this.renderer.setElementAttribute(this._el_162,'name','check-1');
    this.renderer.setElementAttribute(this._el_162,'type','checkbox');
    this._text_163 = this.renderer.createText(this._el_160,'\n                ',(null as any));
    this._el_164 = this.renderer.createElement(this._el_160,'label',(null as any));
    this.renderer.setElementAttribute(this._el_164,'for','check-1');
    this._text_165 = this.renderer.createText(this._el_164,'Показывать в ленте команды',(null as any));
    this._text_166 = this.renderer.createText(this._el_160,'\n              ',(null as any));
    this._text_167 = this.renderer.createText(this._el_158,'\n            ',(null as any));
    this._text_168 = this.renderer.createText(this._el_156,'\n            ',(null as any));
    this._el_169 = this.renderer.createElement(this._el_156,'div',(null as any));
    this.renderer.setElementAttribute(this._el_169,'class','col-lg-6');
    this._text_170 = this.renderer.createText(this._el_169,'\n              ',(null as any));
    this._el_171 = this.renderer.createElement(this._el_169,'div',(null as any));
    this.renderer.setElementAttribute(this._el_171,'class','form-group ');
    this._text_172 = this.renderer.createText(this._el_171,'\n\n                ',(null as any));
    this._el_173 = this.renderer.createElement(this._el_171,'input',(null as any));
    this.renderer.setElementAttribute(this._el_173,'id','check-2');
    this.renderer.setElementAttribute(this._el_173,'name','check-1');
    this.renderer.setElementAttribute(this._el_173,'type','checkbox');
    this._text_174 = this.renderer.createText(this._el_171,'\n                ',(null as any));
    this._el_175 = this.renderer.createElement(this._el_171,'label',(null as any));
    this.renderer.setElementAttribute(this._el_175,'for','check-2');
    this._text_176 = this.renderer.createText(this._el_175,'Показывать в вашей ленте',(null as any));
    this._text_177 = this.renderer.createText(this._el_171,'\n              ',(null as any));
    this._text_178 = this.renderer.createText(this._el_169,'\n            ',(null as any));
    this._text_179 = this.renderer.createText(this._el_156,'\n          ',(null as any));
    this._text_180 = this.renderer.createText(this._el_21,'\n\n          ',(null as any));
    this._el_181 = this.renderer.createElement(this._el_21,'h3',(null as any));
    this.renderer.setElementAttribute(this._el_181,'class','mt-1');
    this._text_182 = this.renderer.createText(this._el_181,'Теги',(null as any));
    this._text_183 = this.renderer.createText(this._el_21,'\n          ',(null as any));
    this._el_184 = this.renderer.createElement(this._el_21,'div',(null as any));
    this.renderer.setElementAttribute(this._el_184,'class','row');
    this._text_185 = this.renderer.createText(this._el_184,'\n            ',(null as any));
    this._el_186 = this.renderer.createElement(this._el_184,'div',(null as any));
    this.renderer.setElementAttribute(this._el_186,'class','col-lg-12');
    this._text_187 = this.renderer.createText(this._el_186,'\n              ',(null as any));
    this._el_188 = this.renderer.createElement(this._el_186,'div',(null as any));
    this.renderer.setElementAttribute(this._el_188,'class','form-group');
    this._text_189 = this.renderer.createText(this._el_188,'\n                ',(null as any));
    this._el_190 = this.renderer.createElement(this._el_188,'div',(null as any));
    this.renderer.setElementAttribute(this._el_190,'class','tagsinput');
    this._text_191 = this.renderer.createText(this._el_190,'\n                  ',(null as any));
    this._el_192 = this.renderer.createElement(this._el_190,'span',(null as any));
    this.renderer.setElementAttribute(this._el_192,'class','tag label label-info');
    this._text_193 = this.renderer.createText(this._el_192,'Sydney',(null as any));
    this._el_194 = this.renderer.createElement(this._el_192,'span',(null as any));
    this.renderer.setElementAttribute(this._el_194,'data-role','remove');
    this._text_195 = this.renderer.createText(this._el_190,'\n                  ',(null as any));
    this._el_196 = this.renderer.createElement(this._el_190,'span',(null as any));
    this.renderer.setElementAttribute(this._el_196,'class','tag label label-info');
    this._text_197 = this.renderer.createText(this._el_196,'Beijing',(null as any));
    this._el_198 = this.renderer.createElement(this._el_196,'span',(null as any));
    this.renderer.setElementAttribute(this._el_198,'data-role','remove');
    this._text_199 = this.renderer.createText(this._el_190,'\n                  ',(null as any));
    this._el_200 = this.renderer.createElement(this._el_190,'span',(null as any));
    this.renderer.setElementAttribute(this._el_200,'class','tag label label-info');
    this._text_201 = this.renderer.createText(this._el_200,'Cairo',(null as any));
    this._el_202 = this.renderer.createElement(this._el_200,'span',(null as any));
    this.renderer.setElementAttribute(this._el_202,'data-role','remove');
    this._text_203 = this.renderer.createText(this._el_190,'\n                  ',(null as any));
    this._el_204 = this.renderer.createElement(this._el_190,'input',(null as any));
    this.renderer.setElementAttribute(this._el_204,'placeholder','');
    this.renderer.setElementAttribute(this._el_204,'size','1');
    this.renderer.setElementAttribute(this._el_204,'type','text');
    this._text_205 = this.renderer.createText(this._el_188,'\n              ',(null as any));
    this._text_206 = this.renderer.createText(this._el_186,'\n            ',(null as any));
    this._text_207 = this.renderer.createText(this._el_184,'\n          ',(null as any));
    this._text_208 = this.renderer.createText(this._el_21,'\n          ',(null as any));
    this._el_209 = this.renderer.createElement(this._el_21,'div',(null as any));
    this.renderer.setElementAttribute(this._el_209,'class','row');
    this._text_210 = this.renderer.createText(this._el_209,'\n            ',(null as any));
    this._el_211 = this.renderer.createElement(this._el_209,'div',(null as any));
    this.renderer.setElementAttribute(this._el_211,'class','col-lg-12');
    this._text_212 = this.renderer.createText(this._el_211,'\n              ',(null as any));
    this._el_213 = this.renderer.createElement(this._el_211,'p',(null as any));
    this.renderer.setElementAttribute(this._el_213,'class','preview-news caption caption-gray text-xs-center');
    this._text_214 = this.renderer.createText(this._el_213,'После добавления публикации она появится в ленте новостей.',(null as any));
    this._text_215 = this.renderer.createText(this._el_211,'\n            ',(null as any));
    this._text_216 = this.renderer.createText(this._el_209,'\n          ',(null as any));
    this._text_217 = this.renderer.createText(this._el_21,'\n\n        ',(null as any));
    this._text_218 = this.renderer.createText(this._el_19,'\n      ',(null as any));
    this._text_219 = this.renderer.createText(this._el_5,'\n      ',(null as any));
    this._el_220 = this.renderer.createElement(this._el_5,'div',(null as any));
    this.renderer.setElementAttribute(this._el_220,'class','modal-footer');
    this._text_221 = this.renderer.createText(this._el_220,'\n        ',(null as any));
    this._el_222 = this.renderer.createElement(this._el_220,'div',(null as any));
    this.renderer.setElementAttribute(this._el_222,'class','container-fulid');
    this._text_223 = this.renderer.createText(this._el_222,'\n          ',(null as any));
    this._el_224 = this.renderer.createElement(this._el_222,'div',(null as any));
    this.renderer.setElementAttribute(this._el_224,'class','row-flex');
    this._text_225 = this.renderer.createText(this._el_224,'\n            ',(null as any));
    this._el_226 = this.renderer.createElement(this._el_224,'div',(null as any));
    this.renderer.setElementAttribute(this._el_226,'class','col');
    this._text_227 = this.renderer.createText(this._el_226,'\n              ',(null as any));
    this._el_228 = this.renderer.createElement(this._el_226,'button',(null as any));
    this.renderer.setElementAttribute(this._el_228,'class','btn btn-secondary');
    this.renderer.setElementAttribute(this._el_228,'type','button');
    this._text_229 = this.renderer.createText(this._el_228,'УДАЛИТЬ',(null as any));
    this._text_230 = this.renderer.createText(this._el_226,'\n            ',(null as any));
    this._text_231 = this.renderer.createText(this._el_224,'\n            ',(null as any));
    this._el_232 = this.renderer.createElement(this._el_224,'div',(null as any));
    this.renderer.setElementAttribute(this._el_232,'class','col');
    this._text_233 = this.renderer.createText(this._el_232,'\n              ',(null as any));
    this._el_234 = this.renderer.createElement(this._el_232,'button',(null as any));
    this.renderer.setElementAttribute(this._el_234,'class','btn btn-secondary');
    this.renderer.setElementAttribute(this._el_234,'type','button');
    this._text_235 = this.renderer.createText(this._el_234,'СОХРАНИТЬ',(null as any));
    this._text_236 = this.renderer.createText(this._el_232,'\n            ',(null as any));
    this._text_237 = this.renderer.createText(this._el_224,'\n            ',(null as any));
    this._el_238 = this.renderer.createElement(this._el_224,'div',(null as any));
    this.renderer.setElementAttribute(this._el_238,'class','col');
    this._text_239 = this.renderer.createText(this._el_238,'\n              ',(null as any));
    this._el_240 = this.renderer.createElement(this._el_238,'button',(null as any));
    this.renderer.setElementAttribute(this._el_240,'class','btn btn-transparent');
    this.renderer.setElementAttribute(this._el_240,'type','button');
    this._text_241 = this.renderer.createText(this._el_240,'ПРЕДПРОСМОТР',(null as any));
    this._text_242 = this.renderer.createText(this._el_238,'\n            ',(null as any));
    this._text_243 = this.renderer.createText(this._el_224,'\n            ',(null as any));
    this._el_244 = this.renderer.createElement(this._el_224,'div',(null as any));
    this.renderer.setElementAttribute(this._el_244,'class','col');
    this._text_245 = this.renderer.createText(this._el_244,'\n              ',(null as any));
    this._el_246 = this.renderer.createElement(this._el_244,'button',(null as any));
    this.renderer.setElementAttribute(this._el_246,'class','btn btn-primary');
    this.renderer.setElementAttribute(this._el_246,'type','button');
    this._text_247 = this.renderer.createText(this._el_246,'ОПУБЛИКОВАТЬ',(null as any));
    this._text_248 = this.renderer.createText(this._el_244,'\n            ',(null as any));
    this._text_249 = this.renderer.createText(this._el_224,'\n          ',(null as any));
    this._text_250 = this.renderer.createText(this._el_222,'\n        ',(null as any));
    this._text_251 = this.renderer.createText(this._el_220,'\n      ',(null as any));
    this._text_252 = this.renderer.createText(this._el_5,'\n    ',(null as any));
    this._text_253 = this.renderer.createText(this._el_2,'\n    ',(null as any));
    this._text_254 = this.renderer.createText(this._el_2,'\n  ',(null as any));
    this._text_255 = this.renderer.createText(this._el_0,'\n',(null as any));
    this._text_256 = this.renderer.createText(parentRenderNode,'\n',(null as any));
    var disposable_0:Function = this.renderer.listen(this._el_9,'click',this.eventHandler(this._handle_click_9_0.bind(this)));
    var disposable_1:Function = this.renderer.listen(this._el_11,'click',this.eventHandler(this._handle_click_11_0.bind(this)));
    var disposable_2:Function = this.renderer.listen(this._el_21,'submit',this.eventHandler(this._handle_submit_21_0.bind(this)));
    var disposable_3:Function = this.renderer.listen(this._el_21,'reset',this.eventHandler(this._handle_reset_21_1.bind(this)));
    this._expr_4 = import7.UNINITIALIZED;
    this._expr_5 = import7.UNINITIALIZED;
    this._expr_6 = import7.UNINITIALIZED;
    this._expr_7 = import7.UNINITIALIZED;
    this._expr_8 = import7.UNINITIALIZED;
    this._expr_9 = import7.UNINITIALIZED;
    var disposable_4:Function = this.renderer.listen(this._el_228,'click',this.eventHandler(this._handle_click_228_0.bind(this)));
    this.init([],[
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._text_4,
      this._el_5,
      this._text_6,
      this._el_7,
      this._text_8,
      this._el_9,
      this._text_10,
      this._el_11,
      this._text_12,
      this._text_13,
      this._text_14,
      this._el_15,
      this._text_16,
      this._text_17,
      this._text_18,
      this._el_19,
      this._text_20,
      this._el_21,
      this._text_22,
      this._el_23,
      this._text_24,
      this._text_25,
      this._el_26,
      this._text_27,
      this._el_28,
      this._text_29,
      this._el_30,
      this._text_31,
      this._el_32,
      this._el_33,
      this._text_34,
      this._text_35,
      this._el_36,
      this._el_37,
      this._text_38,
      this._text_39,
      this._text_40,
      this._text_41,
      this._el_42,
      this._text_43,
      this._el_44,
      this._text_45,
      this._el_46,
      this._text_47,
      this._text_48,
      this._el_49,
      this._text_50,
      this._text_51,
      this._el_52,
      this._text_53,
      this._text_54,
      this._el_55,
      this._text_56,
      this._text_57,
      this._el_58,
      this._text_59,
      this._text_60,
      this._text_61,
      this._text_62,
      this._text_63,
      this._el_64,
      this._text_65,
      this._text_66,
      this._el_67,
      this._text_68,
      this._el_69,
      this._text_70,
      this._el_71,
      this._text_72,
      this._el_73,
      this._text_74,
      this._text_75,
      this._text_76,
      this._text_77,
      this._el_78,
      this._text_79,
      this._el_80,
      this._text_81,
      this._el_82,
      this._text_83,
      this._el_84,
      this._text_85,
      this._text_86,
      this._el_87,
      this._text_88,
      this._el_89,
      this._text_90,
      this._el_91,
      this._text_92,
      this._el_93,
      this._el_94,
      this._text_95,
      this._text_96,
      this._text_97,
      this._el_98,
      this._text_99,
      this._el_100,
      this._text_101,
      this._text_102,
      this._el_103,
      this._text_104,
      this._el_105,
      this._text_106,
      this._text_107,
      this._el_108,
      this._text_109,
      this._el_110,
      this._text_111,
      this._text_112,
      this._el_113,
      this._text_114,
      this._el_115,
      this._text_116,
      this._text_117,
      this._el_118,
      this._text_119,
      this._el_120,
      this._text_121,
      this._text_122,
      this._el_123,
      this._text_124,
      this._el_125,
      this._text_126,
      this._text_127,
      this._text_128,
      this._el_129,
      this._text_130,
      this._el_131,
      this._text_132,
      this._text_133,
      this._el_134,
      this._text_135,
      this._el_136,
      this._text_137,
      this._text_138,
      this._el_139,
      this._text_140,
      this._el_141,
      this._text_142,
      this._text_143,
      this._text_144,
      this._text_145,
      this._text_146,
      this._el_147,
      this._text_148,
      this._el_149,
      this._text_150,
      this._text_151,
      this._text_152,
      this._text_153,
      this._text_154,
      this._text_155,
      this._el_156,
      this._text_157,
      this._el_158,
      this._text_159,
      this._el_160,
      this._text_161,
      this._el_162,
      this._text_163,
      this._el_164,
      this._text_165,
      this._text_166,
      this._text_167,
      this._text_168,
      this._el_169,
      this._text_170,
      this._el_171,
      this._text_172,
      this._el_173,
      this._text_174,
      this._el_175,
      this._text_176,
      this._text_177,
      this._text_178,
      this._text_179,
      this._text_180,
      this._el_181,
      this._text_182,
      this._text_183,
      this._el_184,
      this._text_185,
      this._el_186,
      this._text_187,
      this._el_188,
      this._text_189,
      this._el_190,
      this._text_191,
      this._el_192,
      this._text_193,
      this._el_194,
      this._text_195,
      this._el_196,
      this._text_197,
      this._el_198,
      this._text_199,
      this._el_200,
      this._text_201,
      this._el_202,
      this._text_203,
      this._el_204,
      this._text_205,
      this._text_206,
      this._text_207,
      this._text_208,
      this._el_209,
      this._text_210,
      this._el_211,
      this._text_212,
      this._el_213,
      this._text_214,
      this._text_215,
      this._text_216,
      this._text_217,
      this._text_218,
      this._text_219,
      this._el_220,
      this._text_221,
      this._el_222,
      this._text_223,
      this._el_224,
      this._text_225,
      this._el_226,
      this._text_227,
      this._el_228,
      this._text_229,
      this._text_230,
      this._text_231,
      this._el_232,
      this._text_233,
      this._el_234,
      this._text_235,
      this._text_236,
      this._text_237,
      this._el_238,
      this._text_239,
      this._el_240,
      this._text_241,
      this._text_242,
      this._text_243,
      this._el_244,
      this._text_245,
      this._el_246,
      this._text_247,
      this._text_248,
      this._text_249,
      this._text_250,
      this._text_251,
      this._text_252,
      this._text_253,
      this._text_254,
      this._text_255,
      this._text_256
    ]
    ,[
      disposable_0,
      disposable_1,
      disposable_2,
      disposable_3,
      disposable_4
    ]
    ,[]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import16.NgSelectOption) && ((46 <= requestNodeIndex) && (requestNodeIndex <= 47)))) { return this._NgSelectOption_46_3; }
    if (((token === import17.NgSelectMultipleOption) && ((46 <= requestNodeIndex) && (requestNodeIndex <= 47)))) { return this._NgSelectMultipleOption_46_4; }
    if (((token === import16.NgSelectOption) && ((49 <= requestNodeIndex) && (requestNodeIndex <= 50)))) { return this._NgSelectOption_49_3; }
    if (((token === import17.NgSelectMultipleOption) && ((49 <= requestNodeIndex) && (requestNodeIndex <= 50)))) { return this._NgSelectMultipleOption_49_4; }
    if (((token === import16.NgSelectOption) && ((52 <= requestNodeIndex) && (requestNodeIndex <= 53)))) { return this._NgSelectOption_52_3; }
    if (((token === import17.NgSelectMultipleOption) && ((52 <= requestNodeIndex) && (requestNodeIndex <= 53)))) { return this._NgSelectMultipleOption_52_4; }
    if (((token === import16.NgSelectOption) && ((55 <= requestNodeIndex) && (requestNodeIndex <= 56)))) { return this._NgSelectOption_55_3; }
    if (((token === import17.NgSelectMultipleOption) && ((55 <= requestNodeIndex) && (requestNodeIndex <= 56)))) { return this._NgSelectMultipleOption_55_4; }
    if (((token === import16.NgSelectOption) && ((58 <= requestNodeIndex) && (requestNodeIndex <= 59)))) { return this._NgSelectOption_58_3; }
    if (((token === import17.NgSelectMultipleOption) && ((58 <= requestNodeIndex) && (requestNodeIndex <= 59)))) { return this._NgSelectMultipleOption_58_4; }
    if (((token === import14.NgForm) && ((21 <= requestNodeIndex) && (requestNodeIndex <= 217)))) { return this._NgForm_21_3; }
    if (((token === import19.ControlContainer) && ((21 <= requestNodeIndex) && (requestNodeIndex <= 217)))) { return this._ControlContainer_21_4; }
    if (((token === import15.NgControlStatusGroup) && ((21 <= requestNodeIndex) && (requestNodeIndex <= 217)))) { return this._NgControlStatusGroup_21_5; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this.detectContentChildrenChanges(throwOnChange);
    const currVal_4:any = this._NgControlStatusGroup_21_5.ngClassUntouched;
    if (import4.checkBinding(throwOnChange,this._expr_4,currVal_4)) {
      this.renderer.setElementClass(this._el_21,'ng-untouched',currVal_4);
      this._expr_4 = currVal_4;
    }
    const currVal_5:any = this._NgControlStatusGroup_21_5.ngClassTouched;
    if (import4.checkBinding(throwOnChange,this._expr_5,currVal_5)) {
      this.renderer.setElementClass(this._el_21,'ng-touched',currVal_5);
      this._expr_5 = currVal_5;
    }
    const currVal_6:any = this._NgControlStatusGroup_21_5.ngClassPristine;
    if (import4.checkBinding(throwOnChange,this._expr_6,currVal_6)) {
      this.renderer.setElementClass(this._el_21,'ng-pristine',currVal_6);
      this._expr_6 = currVal_6;
    }
    const currVal_7:any = this._NgControlStatusGroup_21_5.ngClassDirty;
    if (import4.checkBinding(throwOnChange,this._expr_7,currVal_7)) {
      this.renderer.setElementClass(this._el_21,'ng-dirty',currVal_7);
      this._expr_7 = currVal_7;
    }
    const currVal_8:any = this._NgControlStatusGroup_21_5.ngClassValid;
    if (import4.checkBinding(throwOnChange,this._expr_8,currVal_8)) {
      this.renderer.setElementClass(this._el_21,'ng-valid',currVal_8);
      this._expr_8 = currVal_8;
    }
    const currVal_9:any = this._NgControlStatusGroup_21_5.ngClassInvalid;
    if (import4.checkBinding(throwOnChange,this._expr_9,currVal_9)) {
      this.renderer.setElementClass(this._el_21,'ng-invalid',currVal_9);
      this._expr_9 = currVal_9;
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
  destroyInternal():void {
    this._NgSelectOption_46_3.ngOnDestroy();
    this._NgSelectMultipleOption_46_4.ngOnDestroy();
    this._NgSelectOption_49_3.ngOnDestroy();
    this._NgSelectMultipleOption_49_4.ngOnDestroy();
    this._NgSelectOption_52_3.ngOnDestroy();
    this._NgSelectMultipleOption_52_4.ngOnDestroy();
    this._NgSelectOption_55_3.ngOnDestroy();
    this._NgSelectMultipleOption_55_4.ngOnDestroy();
    this._NgSelectOption_58_3.ngOnDestroy();
    this._NgSelectMultipleOption_58_4.ngOnDestroy();
  }
  private _handle_click_9_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.context.hideRegistrationModal()) !== false);
    return (true && pd_0);
  }
  private _handle_click_11_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.context.hideConfirmEmailModal()) !== false);
    return (true && pd_0);
  }
  private _handle_submit_21_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._NgForm_21_3.onSubmit()) !== false);
    return (true && pd_0);
  }
  private _handle_reset_21_1($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._NgForm_21_3.onReset()) !== false);
    return (true && pd_0);
  }
  private _handle_click_228_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.context.hideConfirmEmailModal()) !== false);
    return (true && pd_0);
  }
}
export function viewFactory_AddNewsModal0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<import3.AddNewsModal> {
  if ((renderType_AddNewsModal === (null as any))) { (renderType_AddNewsModal = viewUtils.createRenderComponentType('',0,import12.ViewEncapsulation.None,styles_AddNewsModal,{})); }
  return new _View_AddNewsModal0(viewUtils,parentInjector,declarationEl);
}