/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

import * as import0 from '@angular/core/src/render/api';
import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/linker/element';
import * as import3 from './News';
import * as import4 from '@angular/core/src/linker/view_utils';
import * as import5 from '@angular/core/src/di/injector';
import * as import6 from '@angular/core/src/linker/view_type';
import * as import7 from '@angular/core/src/change_detection/change_detection';
import * as import8 from '../../../services/NewsService';
import * as import9 from '@angular/core/src/metadata/view';
import * as import10 from '@angular/core/src/linker/component_factory';
import * as import11 from './addNews/AddNews';
import * as import12 from './showNews/ShowNews';
import * as import13 from './addNews/AddNews.ngfactory';
import * as import14 from '../../../services/LocalizationService';
import * as import15 from '../../../services/AuthService';
import * as import16 from '../../../services/UserInformationService';
import * as import17 from '../../../services/ModalService';
import * as import18 from './showNews/ShowNews.ngfactory';
import * as import19 from '@angular/platform-browser/src/security/dom_sanitization_service';
import * as import20 from '@angular/core/src/linker/element_ref';
var renderType_News_Host:import0.RenderComponentType = (null as any);
class _View_News_Host0 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import2.AppElement;
  _News_0_4:import3.News;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_News_Host0,renderType_News_Host,import6.ViewType.HOST,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.selectOrCreateHostElement('news',rootSelector,(null as any));
    this._appEl_0 = new import2.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = viewFactory_News0(this.viewUtils,this.injector(0),this._appEl_0);
    this._News_0_4 = new import3.News(this.parentInjector.get(import8.NewsService));
    this._appEl_0.initComponent(this._News_0_4,[],compView_0);
    compView_0.create(this._News_0_4,this.projectableNodes,(null as any));
    this.init([].concat([this._el_0]),[this._el_0],[],[]);
    return this._appEl_0;
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import3.News) && (0 === requestNodeIndex))) { return this._News_0_4; }
    return notFoundResult;
  }
}
function viewFactory_News_Host0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  if ((renderType_News_Host === (null as any))) { (renderType_News_Host = viewUtils.createRenderComponentType('',0,import9.ViewEncapsulation.None,[],{})); }
  return new _View_News_Host0(viewUtils,parentInjector,declarationEl);
}
export const NewsNgFactory:import10.ComponentFactory<import3.News> = new import10.ComponentFactory<import3.News>('news',viewFactory_News_Host0,import3.News);
const styles_News:any[] = [];
var renderType_News:import0.RenderComponentType = (null as any);
class _View_News0 extends import1.AppView<import3.News> {
  _el_0:any;
  _text_1:any;
  _el_2:any;
  _text_3:any;
  _el_4:any;
  /*private*/ _appEl_4:import2.AppElement;
  _AddNews_4_4:import11.AddNews;
  _text_5:any;
  _el_6:any;
  /*private*/ _appEl_6:import2.AppElement;
  _ShowNews_6_4:import12.ShowNews;
  _text_7:any;
  _text_8:any;
  /*private*/ _expr_0:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_News0,renderType_News,import6.ViewType.COMPONENT,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    const parentRenderNode:any = this.renderer.createViewRoot(this.declarationAppElement.nativeElement);
    this._el_0 = this.renderer.createElement(parentRenderNode,'div',(null as any));
    this.renderer.setElementAttribute(this._el_0,'class','container-fluid');
    this._text_1 = this.renderer.createText(this._el_0,'\n  ',(null as any));
    this._el_2 = this.renderer.createElement(this._el_0,'div',(null as any));
    this.renderer.setElementAttribute(this._el_2,'class','row');
    this._text_3 = this.renderer.createText(this._el_2,'\n    ',(null as any));
    this._el_4 = this.renderer.createElement(this._el_2,'add-news',(null as any));
    this._appEl_4 = new import2.AppElement(4,2,this,this._el_4);
    var compView_4:any = import13.viewFactory_AddNews0(this.viewUtils,this.injector(4),this._appEl_4);
    this._AddNews_4_4 = new import11.AddNews(this.parentInjector.get(import8.NewsService),this.parentInjector.get(import14.LocalizationService),this.parentInjector.get(import15.AuthService),this.parentInjector.get(import16.UserInformationService),this.parentInjector.get(import17.ModalService));
    this._appEl_4.initComponent(this._AddNews_4_4,[],compView_4);
    compView_4.create(this._AddNews_4_4,[],(null as any));
    this._text_5 = this.renderer.createText(this._el_2,'\n    ',(null as any));
    this._el_6 = this.renderer.createElement(this._el_2,'show-news',(null as any));
    this._appEl_6 = new import2.AppElement(6,2,this,this._el_6);
    var compView_6:any = import18.viewFactory_ShowNews0(this.viewUtils,this.injector(6),this._appEl_6);
    this._ShowNews_6_4 = new import12.ShowNews(this.parentInjector.get(import8.NewsService),this.parentInjector.get(import14.LocalizationService),this.parentInjector.get(import15.AuthService),this.parentInjector.get(import16.UserInformationService),this.parentInjector.get(import19.DomSanitizer),new import20.ElementRef(this._el_6),this.renderer);
    this._appEl_6.initComponent(this._ShowNews_6_4,[],compView_6);
    compView_6.create(this._ShowNews_6_4,[],(null as any));
    this._text_7 = this.renderer.createText(this._el_2,'\n  ',(null as any));
    this._text_8 = this.renderer.createText(this._el_0,'\n',(null as any));
    this._expr_0 = import7.UNINITIALIZED;
    this.init([],[
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._el_4,
      this._text_5,
      this._el_6,
      this._text_7,
      this._text_8
    ]
    ,[],[]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import11.AddNews) && (4 === requestNodeIndex))) { return this._AddNews_4_4; }
    if (((token === import12.ShowNews) && (6 === requestNodeIndex))) { return this._ShowNews_6_4; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_0:any = this.context.newsService.news;
    if (import4.checkBinding(throwOnChange,this._expr_0,currVal_0)) {
      this._ShowNews_6_4.news = currVal_0;
      this._expr_0 = currVal_0;
    }
    this.detectContentChildrenChanges(throwOnChange);
    this.detectViewChildrenChanges(throwOnChange);
  }
}
export function viewFactory_News0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<import3.News> {
  if ((renderType_News === (null as any))) { (renderType_News = viewUtils.createRenderComponentType('',0,import9.ViewEncapsulation.None,styles_News,{})); }
  return new _View_News0(viewUtils,parentInjector,declarationEl);
}