/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

import * as import0 from '@angular/core/src/render/api';
import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/linker/element';
import * as import3 from './ConfirmEmail';
import * as import4 from '@angular/core/src/linker/view_utils';
import * as import5 from '@angular/core/src/di/injector';
import * as import6 from '@angular/core/src/linker/view_type';
import * as import7 from '@angular/core/src/change_detection/change_detection';
import * as import8 from '@angular/http/src/http';
import * as import9 from '../../../services/LocalizationService';
import * as import10 from '../../../services/ModalService';
import * as import11 from '../../../services/UserInformationService';
import * as import12 from '@angular/router/src/router';
import * as import13 from '@angular/core/src/metadata/view';
import * as import14 from '@angular/core/src/linker/component_factory';
var renderType_ConfirmEmail_Host:import0.RenderComponentType = (null as any);
class _View_ConfirmEmail_Host0 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import2.AppElement;
  _ConfirmEmail_0_4:import3.ConfirmEmail;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_ConfirmEmail_Host0,renderType_ConfirmEmail_Host,import6.ViewType.HOST,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.selectOrCreateHostElement('confirm-email',rootSelector,(null as any));
    this._appEl_0 = new import2.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = viewFactory_ConfirmEmail0(this.viewUtils,this.injector(0),this._appEl_0);
    this._ConfirmEmail_0_4 = new import3.ConfirmEmail(this.parentInjector.get(import8.Http),this.parentInjector.get(import9.LocalizationService),this.parentInjector.get(import10.ModalService),this.parentInjector.get(import11.UserInformationService),this.parentInjector.get(import12.Router));
    this._appEl_0.initComponent(this._ConfirmEmail_0_4,[],compView_0);
    compView_0.create(this._ConfirmEmail_0_4,this.projectableNodes,(null as any));
    this.init([].concat([this._el_0]),[this._el_0],[],[]);
    return this._appEl_0;
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import3.ConfirmEmail) && (0 === requestNodeIndex))) { return this._ConfirmEmail_0_4; }
    return notFoundResult;
  }
}
function viewFactory_ConfirmEmail_Host0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  if ((renderType_ConfirmEmail_Host === (null as any))) { (renderType_ConfirmEmail_Host = viewUtils.createRenderComponentType('',0,import13.ViewEncapsulation.None,[],{})); }
  return new _View_ConfirmEmail_Host0(viewUtils,parentInjector,declarationEl);
}
export const ConfirmEmailNgFactory:import14.ComponentFactory<import3.ConfirmEmail> = new import14.ComponentFactory<import3.ConfirmEmail>('confirm-email',viewFactory_ConfirmEmail_Host0,import3.ConfirmEmail);
const styles_ConfirmEmail:any[] = [];
var renderType_ConfirmEmail:import0.RenderComponentType = (null as any);
class _View_ConfirmEmail0 extends import1.AppView<import3.ConfirmEmail> {
  _el_0:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_ConfirmEmail0,renderType_ConfirmEmail,import6.ViewType.COMPONENT,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    const parentRenderNode:any = this.renderer.createViewRoot(this.declarationAppElement.nativeElement);
    this._el_0 = this.renderer.createElement(parentRenderNode,'div',(null as any));
    this.init([],[this._el_0],[],[]);
    return (null as any);
  }
}
export function viewFactory_ConfirmEmail0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<import3.ConfirmEmail> {
  if ((renderType_ConfirmEmail === (null as any))) { (renderType_ConfirmEmail = viewUtils.createRenderComponentType('',0,import13.ViewEncapsulation.None,styles_ConfirmEmail,{})); }
  return new _View_ConfirmEmail0(viewUtils,parentInjector,declarationEl);
}