/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

import * as import0 from '@angular/core/src/render/api';
import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/linker/element';
import * as import3 from './LoginModal';
import * as import4 from '@angular/core/src/linker/view_utils';
import * as import5 from '@angular/core/src/di/injector';
import * as import6 from '@angular/core/src/linker/view_type';
import * as import7 from '@angular/core/src/change_detection/change_detection';
import * as import8 from '@angular/http/src/http';
import * as import9 from '../../../services/ModalService';
import * as import10 from '../../../services/AuthService';
import * as import11 from '@angular/core/src/metadata/view';
import * as import12 from '@angular/core/src/linker/component_factory';
import * as import13 from '@angular/forms/src/directives/ng_form';
import * as import14 from '@angular/forms/src/directives/ng_control_status';
import * as import15 from '@angular/forms/src/directives/default_value_accessor';
import * as import16 from '@angular/forms/src/directives/ng_model';
import * as import17 from '@angular/core/src/linker/element_ref';
import * as import18 from '@angular/forms/src/directives/control_value_accessor';
import * as import19 from '@angular/forms/src/directives/ng_control';
import * as import20 from '@angular/forms/src/directives/control_container';
import * as import21 from '@angular/core/src/security';
var renderType_LoginModal_Host:import0.RenderComponentType = (null as any);
class _View_LoginModal_Host0 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import2.AppElement;
  _LoginModal_0_4:import3.LoginModal;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_LoginModal_Host0,renderType_LoginModal_Host,import6.ViewType.HOST,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.selectOrCreateHostElement('login-modal',rootSelector,(null as any));
    this._appEl_0 = new import2.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = viewFactory_LoginModal0(this.viewUtils,this.injector(0),this._appEl_0);
    this._LoginModal_0_4 = new import3.LoginModal(this.parentInjector.get(import8.Http),this.parentInjector.get(import9.ModalService),this.parentInjector.get(import10.AuthService));
    this._appEl_0.initComponent(this._LoginModal_0_4,[],compView_0);
    compView_0.create(this._LoginModal_0_4,this.projectableNodes,(null as any));
    this.init([].concat([this._el_0]),[this._el_0],[],[]);
    return this._appEl_0;
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import3.LoginModal) && (0 === requestNodeIndex))) { return this._LoginModal_0_4; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    if (((this.numberOfChecks === 0) && !throwOnChange)) { this._LoginModal_0_4.ngOnInit(); }
    this.detectContentChildrenChanges(throwOnChange);
    this.detectViewChildrenChanges(throwOnChange);
  }
}
function viewFactory_LoginModal_Host0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  if ((renderType_LoginModal_Host === (null as any))) { (renderType_LoginModal_Host = viewUtils.createRenderComponentType('',0,import11.ViewEncapsulation.None,[],{})); }
  return new _View_LoginModal_Host0(viewUtils,parentInjector,declarationEl);
}
export const LoginModalNgFactory:import12.ComponentFactory<import3.LoginModal> = new import12.ComponentFactory<import3.LoginModal>('login-modal',viewFactory_LoginModal_Host0,import3.LoginModal);
const styles_LoginModal:any[] = [];
var renderType_LoginModal:import0.RenderComponentType = (null as any);
class _View_LoginModal0 extends import1.AppView<import3.LoginModal> {
  _el_0:any;
  _text_1:any;
  _el_2:any;
  _text_3:any;
  _el_4:any;
  _text_5:any;
  _el_6:any;
  _text_7:any;
  _el_8:any;
  _text_9:any;
  _el_10:any;
  _text_11:any;
  _text_12:any;
  _text_13:any;
  _el_14:any;
  _text_15:any;
  _text_16:any;
  _text_17:any;
  _el_18:any;
  _text_19:any;
  _el_20:any;
  _NgForm_20_3:import13.NgForm;
  _ControlContainer_20_4:any;
  _NgControlStatusGroup_20_5:import14.NgControlStatusGroup;
  _text_21:any;
  _el_22:any;
  _text_23:any;
  _el_24:any;
  _text_25:any;
  _text_26:any;
  _el_27:any;
  _DefaultValueAccessor_27_3:import15.DefaultValueAccessor;
  _NG_VALUE_ACCESSOR_27_4:any[];
  _NgModel_27_5:import16.NgModel;
  _NgControl_27_6:any;
  _NgControlStatus_27_7:import14.NgControlStatus;
  _text_28:any;
  _text_29:any;
  _el_30:any;
  _text_31:any;
  _el_32:any;
  _text_33:any;
  _text_34:any;
  _el_35:any;
  _DefaultValueAccessor_35_3:import15.DefaultValueAccessor;
  _NG_VALUE_ACCESSOR_35_4:any[];
  _NgModel_35_5:import16.NgModel;
  _NgControl_35_6:any;
  _NgControlStatus_35_7:import14.NgControlStatus;
  _text_36:any;
  _text_37:any;
  _text_38:any;
  _el_39:any;
  _text_40:any;
  _text_41:any;
  _text_42:any;
  _el_43:any;
  _text_44:any;
  _el_45:any;
  _text_46:any;
  _text_47:any;
  _el_48:any;
  _text_49:any;
  _text_50:any;
  _text_51:any;
  _text_52:any;
  _text_53:any;
  _text_54:any;
  /*private*/ _expr_3:any;
  /*private*/ _expr_4:any;
  /*private*/ _expr_5:any;
  /*private*/ _expr_6:any;
  /*private*/ _expr_7:any;
  /*private*/ _expr_8:any;
  /*private*/ _expr_12:any;
  _map_0:any;
  /*private*/ _expr_13:any;
  /*private*/ _expr_14:any;
  /*private*/ _expr_15:any;
  /*private*/ _expr_16:any;
  /*private*/ _expr_17:any;
  /*private*/ _expr_18:any;
  /*private*/ _expr_19:any;
  /*private*/ _expr_23:any;
  _map_1:any;
  /*private*/ _expr_24:any;
  /*private*/ _expr_25:any;
  /*private*/ _expr_26:any;
  /*private*/ _expr_27:any;
  /*private*/ _expr_28:any;
  /*private*/ _expr_29:any;
  /*private*/ _expr_30:any;
  /*private*/ _expr_31:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_LoginModal0,renderType_LoginModal,import6.ViewType.COMPONENT,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    const parentRenderNode:any = this.renderer.createViewRoot(this.declarationAppElement.nativeElement);
    this._el_0 = this.renderer.createElement(parentRenderNode,'div',(null as any));
    this.renderer.setElementAttribute(this._el_0,'aria-labelledby','exampleModalLabel');
    this.renderer.setElementAttribute(this._el_0,'class','modal');
    this.renderer.setElementAttribute(this._el_0,'id','exampleModal');
    this.renderer.setElementAttribute(this._el_0,'role','dialog');
    this.renderer.setElementAttribute(this._el_0,'tabindex','-1');
    this._text_1 = this.renderer.createText(this._el_0,'\n  ',(null as any));
    this._el_2 = this.renderer.createElement(this._el_0,'div',(null as any));
    this.renderer.setElementAttribute(this._el_2,'class','modal-dialog');
    this.renderer.setElementAttribute(this._el_2,'role','document');
    this._text_3 = this.renderer.createText(this._el_2,'\n    ',(null as any));
    this._el_4 = this.renderer.createElement(this._el_2,'div',(null as any));
    this.renderer.setElementAttribute(this._el_4,'class','modal-content');
    this._text_5 = this.renderer.createText(this._el_4,'\n      ',(null as any));
    this._el_6 = this.renderer.createElement(this._el_4,'div',(null as any));
    this.renderer.setElementAttribute(this._el_6,'class','modal-header ');
    this._text_7 = this.renderer.createText(this._el_6,'\n        ',(null as any));
    this._el_8 = this.renderer.createElement(this._el_6,'button',(null as any));
    this.renderer.setElementAttribute(this._el_8,'aria-label','Close');
    this.renderer.setElementAttribute(this._el_8,'class','close');
    this.renderer.setElementAttribute(this._el_8,'type','button');
    this._text_9 = this.renderer.createText(this._el_8,'\n          ',(null as any));
    this._el_10 = this.renderer.createElement(this._el_8,'span',(null as any));
    this.renderer.setElementAttribute(this._el_10,'aria-hidden','true');
    this._text_11 = this.renderer.createText(this._el_10,'×',(null as any));
    this._text_12 = this.renderer.createText(this._el_8,'\n        ',(null as any));
    this._text_13 = this.renderer.createText(this._el_6,'\n        ',(null as any));
    this._el_14 = this.renderer.createElement(this._el_6,'h4',(null as any));
    this.renderer.setElementAttribute(this._el_14,'class','modal-title');
    this.renderer.setElementAttribute(this._el_14,'id','exampleModalLabel');
    this._text_15 = this.renderer.createText(this._el_14,'Логин',(null as any));
    this._text_16 = this.renderer.createText(this._el_6,'\n      ',(null as any));
    this._text_17 = this.renderer.createText(this._el_4,'\n      ',(null as any));
    this._el_18 = this.renderer.createElement(this._el_4,'div',(null as any));
    this.renderer.setElementAttribute(this._el_18,'class','modal-body');
    this._text_19 = this.renderer.createText(this._el_18,'\n        ',(null as any));
    this._el_20 = this.renderer.createElement(this._el_18,'form',(null as any));
    this._NgForm_20_3 = new import13.NgForm((null as any),(null as any));
    this._ControlContainer_20_4 = this._NgForm_20_3;
    this._NgControlStatusGroup_20_5 = new import14.NgControlStatusGroup(this._ControlContainer_20_4);
    this._text_21 = this.renderer.createText(this._el_20,'\n          ',(null as any));
    this._el_22 = this.renderer.createElement(this._el_20,'div',(null as any));
    this.renderer.setElementAttribute(this._el_22,'class','form-group');
    this._text_23 = this.renderer.createText(this._el_22,'\n            ',(null as any));
    this._el_24 = this.renderer.createElement(this._el_22,'label',(null as any));
    this.renderer.setElementAttribute(this._el_24,'class','form-control-label');
    this.renderer.setElementAttribute(this._el_24,'for','email');
    this._text_25 = this.renderer.createText(this._el_24,'Адресс електронной почты:',(null as any));
    this._text_26 = this.renderer.createText(this._el_22,'\n            ',(null as any));
    this._el_27 = this.renderer.createElement(this._el_22,'input',(null as any));
    this.renderer.setElementAttribute(this._el_27,'class','form-control');
    this.renderer.setElementAttribute(this._el_27,'id','email');
    this.renderer.setElementAttribute(this._el_27,'type','text');
    this._DefaultValueAccessor_27_3 = new import15.DefaultValueAccessor(this.renderer,new import17.ElementRef(this._el_27));
    this._NG_VALUE_ACCESSOR_27_4 = [this._DefaultValueAccessor_27_3];
    this._NgModel_27_5 = new import16.NgModel(this._ControlContainer_20_4,(null as any),(null as any),this._NG_VALUE_ACCESSOR_27_4);
    this._NgControl_27_6 = this._NgModel_27_5;
    this._NgControlStatus_27_7 = new import14.NgControlStatus(this._NgControl_27_6);
    this._text_28 = this.renderer.createText(this._el_22,'\n          ',(null as any));
    this._text_29 = this.renderer.createText(this._el_20,'\n          ',(null as any));
    this._el_30 = this.renderer.createElement(this._el_20,'div',(null as any));
    this.renderer.setElementAttribute(this._el_30,'class','form-group');
    this._text_31 = this.renderer.createText(this._el_30,'\n            ',(null as any));
    this._el_32 = this.renderer.createElement(this._el_30,'label',(null as any));
    this.renderer.setElementAttribute(this._el_32,'class','form-control-label');
    this.renderer.setElementAttribute(this._el_32,'for','password');
    this._text_33 = this.renderer.createText(this._el_32,'Пароль:',(null as any));
    this._text_34 = this.renderer.createText(this._el_30,'\n            ',(null as any));
    this._el_35 = this.renderer.createElement(this._el_30,'input',(null as any));
    this.renderer.setElementAttribute(this._el_35,'class','form-control');
    this.renderer.setElementAttribute(this._el_35,'id','password');
    this.renderer.setElementAttribute(this._el_35,'type','password');
    this._DefaultValueAccessor_35_3 = new import15.DefaultValueAccessor(this.renderer,new import17.ElementRef(this._el_35));
    this._NG_VALUE_ACCESSOR_35_4 = [this._DefaultValueAccessor_35_3];
    this._NgModel_35_5 = new import16.NgModel(this._ControlContainer_20_4,(null as any),(null as any),this._NG_VALUE_ACCESSOR_35_4);
    this._NgControl_35_6 = this._NgModel_35_5;
    this._NgControlStatus_35_7 = new import14.NgControlStatus(this._NgControl_35_6);
    this._text_36 = this.renderer.createText(this._el_30,'\n          ',(null as any));
    this._text_37 = this.renderer.createText(this._el_20,'\n        ',(null as any));
    this._text_38 = this.renderer.createText(this._el_18,'\n        ',(null as any));
    this._el_39 = this.renderer.createElement(this._el_18,'a',(null as any));
    this._text_40 = this.renderer.createText(this._el_39,'Steam',(null as any));
    this._text_41 = this.renderer.createText(this._el_18,'\n      ',(null as any));
    this._text_42 = this.renderer.createText(this._el_4,'\n      ',(null as any));
    this._el_43 = this.renderer.createElement(this._el_4,'div',(null as any));
    this.renderer.setElementAttribute(this._el_43,'class','modal-footer');
    this._text_44 = this.renderer.createText(this._el_43,'\n        ',(null as any));
    this._el_45 = this.renderer.createElement(this._el_43,'button',(null as any));
    this.renderer.setElementAttribute(this._el_45,'class','btn btn-secondary');
    this.renderer.setElementAttribute(this._el_45,'data-dismiss','modal');
    this.renderer.setElementAttribute(this._el_45,'type','button');
    this._text_46 = this.renderer.createText(this._el_45,'\n          Закрыть\n        ',(null as any));
    this._text_47 = this.renderer.createText(this._el_43,'\n        ',(null as any));
    this._el_48 = this.renderer.createElement(this._el_43,'button',(null as any));
    this.renderer.setElementAttribute(this._el_48,'class','btn btn-primary');
    this.renderer.setElementAttribute(this._el_48,'type','button');
    this._text_49 = this.renderer.createText(this._el_48,'Войти',(null as any));
    this._text_50 = this.renderer.createText(this._el_43,'\n      ',(null as any));
    this._text_51 = this.renderer.createText(this._el_4,'\n    ',(null as any));
    this._text_52 = this.renderer.createText(this._el_2,'\n  ',(null as any));
    this._text_53 = this.renderer.createText(this._el_0,'\n',(null as any));
    this._text_54 = this.renderer.createText(parentRenderNode,'\n',(null as any));
    var disposable_0:Function = this.renderer.listen(this._el_8,'click',this.eventHandler(this._handle_click_8_0.bind(this)));
    var disposable_1:Function = this.renderer.listen(this._el_20,'submit',this.eventHandler(this._handle_submit_20_0.bind(this)));
    var disposable_2:Function = this.renderer.listen(this._el_20,'reset',this.eventHandler(this._handle_reset_20_1.bind(this)));
    this._expr_3 = import7.UNINITIALIZED;
    this._expr_4 = import7.UNINITIALIZED;
    this._expr_5 = import7.UNINITIALIZED;
    this._expr_6 = import7.UNINITIALIZED;
    this._expr_7 = import7.UNINITIALIZED;
    this._expr_8 = import7.UNINITIALIZED;
    var disposable_3:Function = this.renderer.listen(this._el_27,'ngModelChange',this.eventHandler(this._handle_ngModelChange_27_0.bind(this)));
    var disposable_4:Function = this.renderer.listen(this._el_27,'input',this.eventHandler(this._handle_input_27_1.bind(this)));
    var disposable_5:Function = this.renderer.listen(this._el_27,'blur',this.eventHandler(this._handle_blur_27_2.bind(this)));
    this._expr_12 = import7.UNINITIALIZED;
    this._map_0 = import4.pureProxy1((p0:any):{[key: string]:any} => {
      return {standalone: p0};
    });
    this._expr_13 = import7.UNINITIALIZED;
    const subscription_0:any = this._NgModel_27_5.update.subscribe(this.eventHandler(this._handle_ngModelChange_27_0.bind(this)));
    this._expr_14 = import7.UNINITIALIZED;
    this._expr_15 = import7.UNINITIALIZED;
    this._expr_16 = import7.UNINITIALIZED;
    this._expr_17 = import7.UNINITIALIZED;
    this._expr_18 = import7.UNINITIALIZED;
    this._expr_19 = import7.UNINITIALIZED;
    var disposable_6:Function = this.renderer.listen(this._el_35,'ngModelChange',this.eventHandler(this._handle_ngModelChange_35_0.bind(this)));
    var disposable_7:Function = this.renderer.listen(this._el_35,'input',this.eventHandler(this._handle_input_35_1.bind(this)));
    var disposable_8:Function = this.renderer.listen(this._el_35,'blur',this.eventHandler(this._handle_blur_35_2.bind(this)));
    this._expr_23 = import7.UNINITIALIZED;
    this._map_1 = import4.pureProxy1((p0:any):{[key: string]:any} => {
      return {standalone: p0};
    });
    this._expr_24 = import7.UNINITIALIZED;
    const subscription_1:any = this._NgModel_35_5.update.subscribe(this.eventHandler(this._handle_ngModelChange_35_0.bind(this)));
    this._expr_25 = import7.UNINITIALIZED;
    this._expr_26 = import7.UNINITIALIZED;
    this._expr_27 = import7.UNINITIALIZED;
    this._expr_28 = import7.UNINITIALIZED;
    this._expr_29 = import7.UNINITIALIZED;
    this._expr_30 = import7.UNINITIALIZED;
    this._expr_31 = import7.UNINITIALIZED;
    var disposable_9:Function = this.renderer.listen(this._el_45,'click',this.eventHandler(this._handle_click_45_0.bind(this)));
    var disposable_10:Function = this.renderer.listen(this._el_48,'click',this.eventHandler(this._handle_click_48_0.bind(this)));
    this.init([],[
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._el_4,
      this._text_5,
      this._el_6,
      this._text_7,
      this._el_8,
      this._text_9,
      this._el_10,
      this._text_11,
      this._text_12,
      this._text_13,
      this._el_14,
      this._text_15,
      this._text_16,
      this._text_17,
      this._el_18,
      this._text_19,
      this._el_20,
      this._text_21,
      this._el_22,
      this._text_23,
      this._el_24,
      this._text_25,
      this._text_26,
      this._el_27,
      this._text_28,
      this._text_29,
      this._el_30,
      this._text_31,
      this._el_32,
      this._text_33,
      this._text_34,
      this._el_35,
      this._text_36,
      this._text_37,
      this._text_38,
      this._el_39,
      this._text_40,
      this._text_41,
      this._text_42,
      this._el_43,
      this._text_44,
      this._el_45,
      this._text_46,
      this._text_47,
      this._el_48,
      this._text_49,
      this._text_50,
      this._text_51,
      this._text_52,
      this._text_53,
      this._text_54
    ]
    ,[
      disposable_0,
      disposable_1,
      disposable_2,
      disposable_3,
      disposable_4,
      disposable_5,
      disposable_6,
      disposable_7,
      disposable_8,
      disposable_9,
      disposable_10
    ]
    ,[
      subscription_0,
      subscription_1
    ]
    );
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import15.DefaultValueAccessor) && (27 === requestNodeIndex))) { return this._DefaultValueAccessor_27_3; }
    if (((token === import18.NG_VALUE_ACCESSOR) && (27 === requestNodeIndex))) { return this._NG_VALUE_ACCESSOR_27_4; }
    if (((token === import16.NgModel) && (27 === requestNodeIndex))) { return this._NgModel_27_5; }
    if (((token === import19.NgControl) && (27 === requestNodeIndex))) { return this._NgControl_27_6; }
    if (((token === import14.NgControlStatus) && (27 === requestNodeIndex))) { return this._NgControlStatus_27_7; }
    if (((token === import15.DefaultValueAccessor) && (35 === requestNodeIndex))) { return this._DefaultValueAccessor_35_3; }
    if (((token === import18.NG_VALUE_ACCESSOR) && (35 === requestNodeIndex))) { return this._NG_VALUE_ACCESSOR_35_4; }
    if (((token === import16.NgModel) && (35 === requestNodeIndex))) { return this._NgModel_35_5; }
    if (((token === import19.NgControl) && (35 === requestNodeIndex))) { return this._NgControl_35_6; }
    if (((token === import14.NgControlStatus) && (35 === requestNodeIndex))) { return this._NgControlStatus_35_7; }
    if (((token === import13.NgForm) && ((20 <= requestNodeIndex) && (requestNodeIndex <= 37)))) { return this._NgForm_20_3; }
    if (((token === import20.ControlContainer) && ((20 <= requestNodeIndex) && (requestNodeIndex <= 37)))) { return this._ControlContainer_20_4; }
    if (((token === import14.NgControlStatusGroup) && ((20 <= requestNodeIndex) && (requestNodeIndex <= 37)))) { return this._NgControlStatusGroup_20_5; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    var changes:{[key: string]:import7.SimpleChange} = (null as any);
    changes = (null as any);
    const currVal_12:any = this.context.email;
    if (import4.checkBinding(throwOnChange,this._expr_12,currVal_12)) {
      this._NgModel_27_5.model = currVal_12;
      if ((changes === (null as any))) { (changes = {}); }
      changes['model'] = new import7.SimpleChange(this._expr_12,currVal_12);
      this._expr_12 = currVal_12;
    }
    const currVal_13:any = this._map_0(true);
    if (import4.checkBinding(throwOnChange,this._expr_13,currVal_13)) {
      this._NgModel_27_5.options = currVal_13;
      if ((changes === (null as any))) { (changes = {}); }
      changes['options'] = new import7.SimpleChange(this._expr_13,currVal_13);
      this._expr_13 = currVal_13;
    }
    if ((changes !== (null as any))) { this._NgModel_27_5.ngOnChanges(changes); }
    changes = (null as any);
    const currVal_23:any = this.context.password;
    if (import4.checkBinding(throwOnChange,this._expr_23,currVal_23)) {
      this._NgModel_35_5.model = currVal_23;
      if ((changes === (null as any))) { (changes = {}); }
      changes['model'] = new import7.SimpleChange(this._expr_23,currVal_23);
      this._expr_23 = currVal_23;
    }
    const currVal_24:any = this._map_1(true);
    if (import4.checkBinding(throwOnChange,this._expr_24,currVal_24)) {
      this._NgModel_35_5.options = currVal_24;
      if ((changes === (null as any))) { (changes = {}); }
      changes['options'] = new import7.SimpleChange(this._expr_24,currVal_24);
      this._expr_24 = currVal_24;
    }
    if ((changes !== (null as any))) { this._NgModel_35_5.ngOnChanges(changes); }
    this.detectContentChildrenChanges(throwOnChange);
    const currVal_3:any = this._NgControlStatusGroup_20_5.ngClassUntouched;
    if (import4.checkBinding(throwOnChange,this._expr_3,currVal_3)) {
      this.renderer.setElementClass(this._el_20,'ng-untouched',currVal_3);
      this._expr_3 = currVal_3;
    }
    const currVal_4:any = this._NgControlStatusGroup_20_5.ngClassTouched;
    if (import4.checkBinding(throwOnChange,this._expr_4,currVal_4)) {
      this.renderer.setElementClass(this._el_20,'ng-touched',currVal_4);
      this._expr_4 = currVal_4;
    }
    const currVal_5:any = this._NgControlStatusGroup_20_5.ngClassPristine;
    if (import4.checkBinding(throwOnChange,this._expr_5,currVal_5)) {
      this.renderer.setElementClass(this._el_20,'ng-pristine',currVal_5);
      this._expr_5 = currVal_5;
    }
    const currVal_6:any = this._NgControlStatusGroup_20_5.ngClassDirty;
    if (import4.checkBinding(throwOnChange,this._expr_6,currVal_6)) {
      this.renderer.setElementClass(this._el_20,'ng-dirty',currVal_6);
      this._expr_6 = currVal_6;
    }
    const currVal_7:any = this._NgControlStatusGroup_20_5.ngClassValid;
    if (import4.checkBinding(throwOnChange,this._expr_7,currVal_7)) {
      this.renderer.setElementClass(this._el_20,'ng-valid',currVal_7);
      this._expr_7 = currVal_7;
    }
    const currVal_8:any = this._NgControlStatusGroup_20_5.ngClassInvalid;
    if (import4.checkBinding(throwOnChange,this._expr_8,currVal_8)) {
      this.renderer.setElementClass(this._el_20,'ng-invalid',currVal_8);
      this._expr_8 = currVal_8;
    }
    const currVal_14:any = this._NgControlStatus_27_7.ngClassUntouched;
    if (import4.checkBinding(throwOnChange,this._expr_14,currVal_14)) {
      this.renderer.setElementClass(this._el_27,'ng-untouched',currVal_14);
      this._expr_14 = currVal_14;
    }
    const currVal_15:any = this._NgControlStatus_27_7.ngClassTouched;
    if (import4.checkBinding(throwOnChange,this._expr_15,currVal_15)) {
      this.renderer.setElementClass(this._el_27,'ng-touched',currVal_15);
      this._expr_15 = currVal_15;
    }
    const currVal_16:any = this._NgControlStatus_27_7.ngClassPristine;
    if (import4.checkBinding(throwOnChange,this._expr_16,currVal_16)) {
      this.renderer.setElementClass(this._el_27,'ng-pristine',currVal_16);
      this._expr_16 = currVal_16;
    }
    const currVal_17:any = this._NgControlStatus_27_7.ngClassDirty;
    if (import4.checkBinding(throwOnChange,this._expr_17,currVal_17)) {
      this.renderer.setElementClass(this._el_27,'ng-dirty',currVal_17);
      this._expr_17 = currVal_17;
    }
    const currVal_18:any = this._NgControlStatus_27_7.ngClassValid;
    if (import4.checkBinding(throwOnChange,this._expr_18,currVal_18)) {
      this.renderer.setElementClass(this._el_27,'ng-valid',currVal_18);
      this._expr_18 = currVal_18;
    }
    const currVal_19:any = this._NgControlStatus_27_7.ngClassInvalid;
    if (import4.checkBinding(throwOnChange,this._expr_19,currVal_19)) {
      this.renderer.setElementClass(this._el_27,'ng-invalid',currVal_19);
      this._expr_19 = currVal_19;
    }
    const currVal_25:any = this._NgControlStatus_35_7.ngClassUntouched;
    if (import4.checkBinding(throwOnChange,this._expr_25,currVal_25)) {
      this.renderer.setElementClass(this._el_35,'ng-untouched',currVal_25);
      this._expr_25 = currVal_25;
    }
    const currVal_26:any = this._NgControlStatus_35_7.ngClassTouched;
    if (import4.checkBinding(throwOnChange,this._expr_26,currVal_26)) {
      this.renderer.setElementClass(this._el_35,'ng-touched',currVal_26);
      this._expr_26 = currVal_26;
    }
    const currVal_27:any = this._NgControlStatus_35_7.ngClassPristine;
    if (import4.checkBinding(throwOnChange,this._expr_27,currVal_27)) {
      this.renderer.setElementClass(this._el_35,'ng-pristine',currVal_27);
      this._expr_27 = currVal_27;
    }
    const currVal_28:any = this._NgControlStatus_35_7.ngClassDirty;
    if (import4.checkBinding(throwOnChange,this._expr_28,currVal_28)) {
      this.renderer.setElementClass(this._el_35,'ng-dirty',currVal_28);
      this._expr_28 = currVal_28;
    }
    const currVal_29:any = this._NgControlStatus_35_7.ngClassValid;
    if (import4.checkBinding(throwOnChange,this._expr_29,currVal_29)) {
      this.renderer.setElementClass(this._el_35,'ng-valid',currVal_29);
      this._expr_29 = currVal_29;
    }
    const currVal_30:any = this._NgControlStatus_35_7.ngClassInvalid;
    if (import4.checkBinding(throwOnChange,this._expr_30,currVal_30)) {
      this.renderer.setElementClass(this._el_35,'ng-invalid',currVal_30);
      this._expr_30 = currVal_30;
    }
    const currVal_31:any = (this.context.restUrl + '/auth/steam');
    if (import4.checkBinding(throwOnChange,this._expr_31,currVal_31)) {
      this.renderer.setElementProperty(this._el_39,'href',this.viewUtils.sanitizer.sanitize(import21.SecurityContext.URL,currVal_31));
      this._expr_31 = currVal_31;
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
  destroyInternal():void {
    this._NgModel_27_5.ngOnDestroy();
    this._NgModel_35_5.ngOnDestroy();
  }
  private _handle_click_8_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.context.hideRegistrationModal()) !== false);
    return (true && pd_0);
  }
  private _handle_submit_20_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._NgForm_20_3.onSubmit()) !== false);
    return (true && pd_0);
  }
  private _handle_reset_20_1($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._NgForm_20_3.onReset()) !== false);
    return (true && pd_0);
  }
  private _handle_ngModelChange_27_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>(this.context.email = $event)) !== false);
    return (true && pd_0);
  }
  private _handle_input_27_1($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._DefaultValueAccessor_27_3.onChange($event.target.value)) !== false);
    return (true && pd_0);
  }
  private _handle_blur_27_2($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._DefaultValueAccessor_27_3.onTouched()) !== false);
    return (true && pd_0);
  }
  private _handle_ngModelChange_35_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>(this.context.password = $event)) !== false);
    return (true && pd_0);
  }
  private _handle_input_35_1($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._DefaultValueAccessor_35_3.onChange($event.target.value)) !== false);
    return (true && pd_0);
  }
  private _handle_blur_35_2($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._DefaultValueAccessor_35_3.onTouched()) !== false);
    return (true && pd_0);
  }
  private _handle_click_45_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.context.hideRegistrationModal()) !== false);
    return (true && pd_0);
  }
  private _handle_click_48_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.context.onSubmit()) !== false);
    return (true && pd_0);
  }
}
export function viewFactory_LoginModal0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<import3.LoginModal> {
  if ((renderType_LoginModal === (null as any))) { (renderType_LoginModal = viewUtils.createRenderComponentType('',0,import11.ViewEncapsulation.None,styles_LoginModal,{})); }
  return new _View_LoginModal0(viewUtils,parentInjector,declarationEl);
}