/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

import * as import0 from '@angular/core/src/render/api';
import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/linker/element';
import * as import3 from './ShowNews';
import * as import4 from '@angular/core/src/linker/view_utils';
import * as import5 from '@angular/core/src/di/injector';
import * as import6 from '@angular/core/src/linker/view_type';
import * as import7 from '@angular/core/src/change_detection/change_detection';
import * as import8 from '../../../../services/NewsService';
import * as import9 from '../../../../services/LocalizationService';
import * as import10 from '../../../../services/AuthService';
import * as import11 from '../../../../services/UserInformationService';
import * as import12 from '@angular/platform-browser/src/security/dom_sanitization_service';
import * as import13 from '@angular/core/src/linker/element_ref';
import * as import14 from '@angular/core/src/metadata/view';
import * as import15 from '@angular/core/src/linker/component_factory';
import * as import16 from '@angular/common/src/directives/ng_for';
import * as import17 from '@angular/common/src/directives/ng_if';
import * as import18 from '../../../../pipes/NewsVideoChanger';
import * as import19 from '@angular/core/src/linker/template_ref';
import * as import20 from '@angular/core/src/change_detection/differs/iterable_differs';
import * as import21 from '@angular/common/src/directives/ng_style';
import * as import22 from '@angular/router/src/directives/router_link';
import * as import23 from '@ng-bootstrap/ng-bootstrap/popover/popover';
import * as import24 from '@angular/core/src/change_detection/differs/keyvalue_differs';
import * as import25 from '@angular/router/src/router';
import * as import26 from '@angular/router/src/router_state';
import * as import27 from '@angular/common/src/location/location_strategy';
import * as import28 from '@angular/core/src/linker/component_factory_resolver';
import * as import29 from '@ng-bootstrap/ng-bootstrap/popover/popover-config';
import * as import30 from '@angular/core/src/zone/ng_zone';
import * as import31 from '@angular/core/src/security';
import * as import32 from '../newsVideoPopup/NewsVideoPopup';
import * as import33 from '../newsVideoPopup/NewsVideoPopup.ngfactory';
var renderType_ShowNews_Host:import0.RenderComponentType = (null as any);
class _View_ShowNews_Host0 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import2.AppElement;
  _ShowNews_0_4:import3.ShowNews;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_ShowNews_Host0,renderType_ShowNews_Host,import6.ViewType.HOST,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.selectOrCreateHostElement('show-news',rootSelector,(null as any));
    this._appEl_0 = new import2.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = viewFactory_ShowNews0(this.viewUtils,this.injector(0),this._appEl_0);
    this._ShowNews_0_4 = new import3.ShowNews(this.parentInjector.get(import8.NewsService),this.parentInjector.get(import9.LocalizationService),this.parentInjector.get(import10.AuthService),this.parentInjector.get(import11.UserInformationService),this.parentInjector.get(import12.DomSanitizer),new import13.ElementRef(this._el_0),this.renderer);
    this._appEl_0.initComponent(this._ShowNews_0_4,[],compView_0);
    compView_0.create(this._ShowNews_0_4,this.projectableNodes,(null as any));
    this.init([].concat([this._el_0]),[this._el_0],[],[]);
    return this._appEl_0;
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import3.ShowNews) && (0 === requestNodeIndex))) { return this._ShowNews_0_4; }
    return notFoundResult;
  }
}
function viewFactory_ShowNews_Host0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  if ((renderType_ShowNews_Host === (null as any))) { (renderType_ShowNews_Host = viewUtils.createRenderComponentType('',0,import14.ViewEncapsulation.None,[],{})); }
  return new _View_ShowNews_Host0(viewUtils,parentInjector,declarationEl);
}
export const ShowNewsNgFactory:import15.ComponentFactory<import3.ShowNews> = new import15.ComponentFactory<import3.ShowNews>('show-news',viewFactory_ShowNews_Host0,import3.ShowNews);
const styles_ShowNews:any[] = [];
var renderType_ShowNews:import0.RenderComponentType = (null as any);
class _View_ShowNews0 extends import1.AppView<import3.ShowNews> {
  _anchor_0:any;
  /*private*/ _appEl_0:import2.AppElement;
  _TemplateRef_0_5:any;
  _NgFor_0_6:import16.NgFor;
  _text_1:any;
  _anchor_2:any;
  /*private*/ _appEl_2:import2.AppElement;
  _TemplateRef_2_5:any;
  _NgIf_2_6:import17.NgIf;
  _text_3:any;
  /*private*/ _expr_0:any;
  _pipe_newsVideoChanger_0:import18.NewsVideoChanger;
  /*private*/ _expr_1:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_ShowNews0,renderType_ShowNews,import6.ViewType.COMPONENT,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    const parentRenderNode:any = this.renderer.createViewRoot(this.declarationAppElement.nativeElement);
    this._anchor_0 = this.renderer.createTemplateAnchor(parentRenderNode,(null as any));
    this._appEl_0 = new import2.AppElement(0,(null as any),this,this._anchor_0);
    this._TemplateRef_0_5 = new import19.TemplateRef_(this._appEl_0,viewFactory_ShowNews1);
    this._NgFor_0_6 = new import16.NgFor(this._appEl_0.vcRef,this._TemplateRef_0_5,this.parentInjector.get(import20.IterableDiffers),this.ref);
    this._text_1 = this.renderer.createText(parentRenderNode,'\n\n',(null as any));
    this._anchor_2 = this.renderer.createTemplateAnchor(parentRenderNode,(null as any));
    this._appEl_2 = new import2.AppElement(2,(null as any),this,this._anchor_2);
    this._TemplateRef_2_5 = new import19.TemplateRef_(this._appEl_2,viewFactory_ShowNews9);
    this._NgIf_2_6 = new import17.NgIf(this._appEl_2.vcRef,this._TemplateRef_2_5);
    this._text_3 = this.renderer.createText(parentRenderNode,'\n',(null as any));
    this._expr_0 = import7.UNINITIALIZED;
    this._pipe_newsVideoChanger_0 = new import18.NewsVideoChanger();
    this._expr_1 = import7.UNINITIALIZED;
    this.init([],[
      this._anchor_0,
      this._text_1,
      this._anchor_2,
      this._text_3
    ]
    ,[],[]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import19.TemplateRef) && (0 === requestNodeIndex))) { return this._TemplateRef_0_5; }
    if (((token === import16.NgFor) && (0 === requestNodeIndex))) { return this._NgFor_0_6; }
    if (((token === import19.TemplateRef) && (2 === requestNodeIndex))) { return this._TemplateRef_2_5; }
    if (((token === import17.NgIf) && (2 === requestNodeIndex))) { return this._NgIf_2_6; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    var changes:{[key: string]:import7.SimpleChange} = (null as any);
    changes = (null as any);
    const currVal_0:any = this.context.news;
    if (import4.checkBinding(throwOnChange,this._expr_0,currVal_0)) {
      this._NgFor_0_6.ngForOf = currVal_0;
      if ((changes === (null as any))) { (changes = {}); }
      changes['ngForOf'] = new import7.SimpleChange(this._expr_0,currVal_0);
      this._expr_0 = currVal_0;
    }
    if ((changes !== (null as any))) { this._NgFor_0_6.ngOnChanges(changes); }
    if (!throwOnChange) { this._NgFor_0_6.ngDoCheck(); }
    const currVal_1:any = (this.context.showVideo && this.context.activeVideoUrl);
    if (import4.checkBinding(throwOnChange,this._expr_1,currVal_1)) {
      this._NgIf_2_6.ngIf = currVal_1;
      this._expr_1 = currVal_1;
    }
    this.detectContentChildrenChanges(throwOnChange);
    this.detectViewChildrenChanges(throwOnChange);
  }
}
export function viewFactory_ShowNews0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<import3.ShowNews> {
  if ((renderType_ShowNews === (null as any))) { (renderType_ShowNews = viewUtils.createRenderComponentType('',0,import14.ViewEncapsulation.None,styles_ShowNews,{})); }
  return new _View_ShowNews0(viewUtils,parentInjector,declarationEl);
}
class _View_ShowNews1 extends import1.AppView<any> {
  _el_0:any;
  _text_1:any;
  _el_2:any;
  _text_3:any;
  _el_4:any;
  _text_5:any;
  _el_6:any;
  _text_7:any;
  _el_8:any;
  _text_9:any;
  _text_10:any;
  _el_11:any;
  _text_12:any;
  _text_13:any;
  _el_14:any;
  _text_15:any;
  _text_16:any;
  _text_17:any;
  _el_18:any;
  _text_19:any;
  _el_20:any;
  _text_21:any;
  _text_22:any;
  _text_23:any;
  _el_24:any;
  _text_25:any;
  _el_26:any;
  _text_27:any;
  _el_28:any;
  _NgStyle_28_3:import21.NgStyle;
  _text_29:any;
  _el_30:any;
  _text_31:any;
  _anchor_32:any;
  /*private*/ _appEl_32:import2.AppElement;
  _TemplateRef_32_5:any;
  _NgFor_32_6:import16.NgFor;
  _text_33:any;
  _text_34:any;
  _el_35:any;
  _text_36:any;
  _anchor_37:any;
  /*private*/ _appEl_37:import2.AppElement;
  _TemplateRef_37_5:any;
  _NgIf_37_6:import17.NgIf;
  _text_38:any;
  _el_39:any;
  _text_40:any;
  _anchor_41:any;
  /*private*/ _appEl_41:import2.AppElement;
  _TemplateRef_41_5:any;
  _NgFor_41_6:import16.NgFor;
  _text_42:any;
  _el_43:any;
  _RouterLinkWithHref_43_3:import22.RouterLinkWithHref;
  _text_44:any;
  _text_45:any;
  _text_46:any;
  _text_47:any;
  _text_48:any;
  _text_49:any;
  _text_50:any;
  _el_51:any;
  _text_52:any;
  _el_53:any;
  _text_54:any;
  _el_55:any;
  _el_56:any;
  _text_57:any;
  _text_58:any;
  _el_59:any;
  _el_60:any;
  _text_61:any;
  _text_62:any;
  _text_63:any;
  _el_64:any;
  _text_65:any;
  _el_66:any;
  _text_67:any;
  _el_68:any;
  _text_69:any;
  _text_70:any;
  _anchor_71:any;
  /*private*/ _appEl_71:import2.AppElement;
  _TemplateRef_71_4:any;
  _text_72:any;
  _el_73:any;
  /*private*/ _appEl_73:import2.AppElement;
  _NgbPopover_73_5:import23.NgbPopover;
  _text_74:any;
  _el_75:any;
  _text_76:any;
  _text_77:any;
  _text_78:any;
  _text_79:any;
  /*private*/ _expr_0:any;
  /*private*/ _expr_1:any;
  /*private*/ _expr_2:any;
  /*private*/ _expr_3:any;
  /*private*/ _expr_4:any;
  /*private*/ _expr_5:any;
  _pipe_newsVideoChanger_0_0:any;
  /*private*/ _expr_6:any;
  /*private*/ _expr_8:any;
  /*private*/ _expr_9:any;
  /*private*/ _expr_10:any;
  /*private*/ _expr_12:any;
  /*private*/ _expr_14:any;
  /*private*/ _expr_15:any;
  /*private*/ _expr_16:any;
  /*private*/ _expr_17:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_ShowNews1,renderType_ShowNews,import6.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'div',(null as any));
    this.renderer.setElementAttribute(this._el_0,'class','col-md-12 news-add');
    this._text_1 = this.renderer.createText(this._el_0,'\n\n  ',(null as any));
    this._el_2 = this.renderer.createElement(this._el_0,'div',(null as any));
    this.renderer.setElementAttribute(this._el_2,'class','news-head clearfix');
    this._text_3 = this.renderer.createText(this._el_2,'\n    ',(null as any));
    this._el_4 = this.renderer.createElement(this._el_2,'div',(null as any));
    this.renderer.setElementAttribute(this._el_4,'class','col-md-2 nopadding clearfix');
    this._text_5 = this.renderer.createText(this._el_4,'\n      ',(null as any));
    this._el_6 = this.renderer.createElement(this._el_4,'div',(null as any));
    this.renderer.setElementAttribute(this._el_6,'class','mr-1 pull-left');
    this._text_7 = this.renderer.createText(this._el_6,'\n        ',(null as any));
    this._el_8 = this.renderer.createElement(this._el_6,'img',(null as any));
    this.renderer.setElementAttribute(this._el_8,'alt','');
    this.renderer.setElementAttribute(this._el_8,'class','img-responsive');
    this._text_9 = this.renderer.createText(this._el_6,'\n      ',(null as any));
    this._text_10 = this.renderer.createText(this._el_4,'\n      ',(null as any));
    this._el_11 = this.renderer.createElement(this._el_4,'h4',(null as any));
    this.renderer.setElementAttribute(this._el_11,'class','blue');
    this._text_12 = this.renderer.createText(this._el_11,'',(null as any));
    this._text_13 = this.renderer.createText(this._el_4,'\n      ',(null as any));
    this._el_14 = this.renderer.createElement(this._el_4,'p',(null as any));
    this.renderer.setElementAttribute(this._el_14,'class','puny mb-0');
    this._text_15 = this.renderer.createText(this._el_14,'',(null as any));
    this._text_16 = this.renderer.createText(this._el_4,'\n    ',(null as any));
    this._text_17 = this.renderer.createText(this._el_2,'\n    ',(null as any));
    this._el_18 = this.renderer.createElement(this._el_2,'div',(null as any));
    this.renderer.setElementAttribute(this._el_18,'class','col-md-2 offset-md-8 nopadding text-right clearfix');
    this._text_19 = this.renderer.createText(this._el_18,'\n      ',(null as any));
    this._el_20 = this.renderer.createElement(this._el_18,'span',(null as any));
    this.renderer.setElementAttribute(this._el_20,'class','dropdown-menu-dots');
    this._text_21 = this.renderer.createText(this._el_18,'\n    ',(null as any));
    this._text_22 = this.renderer.createText(this._el_2,'\n  ',(null as any));
    this._text_23 = this.renderer.createText(this._el_0,'\n\n  ',(null as any));
    this._el_24 = this.renderer.createElement(this._el_0,'div',(null as any));
    this.renderer.setElementAttribute(this._el_24,'class','news-body clearfix nopadding');
    this._text_25 = this.renderer.createText(this._el_24,'\n    ',(null as any));
    this._el_26 = this.renderer.createElement(this._el_24,'div',(null as any));
    this.renderer.setElementAttribute(this._el_26,'class','block-info');
    this._text_27 = this.renderer.createText(this._el_26,'\n      ',(null as any));
    this._el_28 = this.renderer.createElement(this._el_26,'div',(null as any));
    this.renderer.setElementAttribute(this._el_28,'class','block-info-image');
    this._NgStyle_28_3 = new import21.NgStyle(this.parentInjector.get(import24.KeyValueDiffers),new import13.ElementRef(this._el_28),this.renderer);
    this._text_29 = this.renderer.createText(this._el_28,'\n        ',(null as any));
    this._el_30 = this.renderer.createElement(this._el_28,'div',(null as any));
    this.renderer.setElementAttribute(this._el_30,'class','tags');
    this._text_31 = this.renderer.createText(this._el_30,'\n          ',(null as any));
    this._anchor_32 = this.renderer.createTemplateAnchor(this._el_30,(null as any));
    this._appEl_32 = new import2.AppElement(32,30,this,this._anchor_32);
    this._TemplateRef_32_5 = new import19.TemplateRef_(this._appEl_32,viewFactory_ShowNews2);
    this._NgFor_32_6 = new import16.NgFor(this._appEl_32.vcRef,this._TemplateRef_32_5,this.parentInjector.get(import20.IterableDiffers),this.parent.ref);
    this._text_33 = this.renderer.createText(this._el_30,'\n        ',(null as any));
    this._text_34 = this.renderer.createText(this._el_28,'\n\n        ',(null as any));
    this._el_35 = this.renderer.createElement(this._el_28,'div',(null as any));
    this.renderer.setElementAttribute(this._el_35,'class','block-info-content');
    this._text_36 = this.renderer.createText(this._el_35,'\n          ',(null as any));
    this._anchor_37 = this.renderer.createTemplateAnchor(this._el_35,(null as any));
    this._appEl_37 = new import2.AppElement(37,35,this,this._anchor_37);
    this._TemplateRef_37_5 = new import19.TemplateRef_(this._appEl_37,viewFactory_ShowNews3);
    this._NgIf_37_6 = new import17.NgIf(this._appEl_37.vcRef,this._TemplateRef_37_5);
    this._text_38 = this.renderer.createText(this._el_35,'\n          ',(null as any));
    this._el_39 = this.renderer.createElement(this._el_35,'div',(null as any));
    this.renderer.setElementAttribute(this._el_39,'class','block-info-text body mb-0');
    this._text_40 = this.renderer.createText(this._el_39,'\n            ',(null as any));
    this._anchor_41 = this.renderer.createTemplateAnchor(this._el_39,(null as any));
    this._appEl_41 = new import2.AppElement(41,39,this,this._anchor_41);
    this._TemplateRef_41_5 = new import19.TemplateRef_(this._appEl_41,viewFactory_ShowNews4);
    this._NgFor_41_6 = new import16.NgFor(this._appEl_41.vcRef,this._TemplateRef_41_5,this.parentInjector.get(import20.IterableDiffers),this.parent.ref);
    this._text_42 = this.renderer.createText(this._el_39,'\n\n            ',(null as any));
    this._el_43 = this.renderer.createElement(this._el_39,'a',(null as any));
    this.renderer.setElementAttribute(this._el_43,'class','block-info-more');
    this._RouterLinkWithHref_43_3 = new import22.RouterLinkWithHref(this.parentInjector.get(import25.Router),this.parentInjector.get(import26.ActivatedRoute),this.parentInjector.get(import27.LocationStrategy));
    this._text_44 = this.renderer.createText(this._el_43,'читать дальше',(null as any));
    this._text_45 = this.renderer.createText(this._el_39,'\n          ',(null as any));
    this._text_46 = this.renderer.createText(this._el_35,'\n        ',(null as any));
    this._text_47 = this.renderer.createText(this._el_28,'\n      ',(null as any));
    this._text_48 = this.renderer.createText(this._el_26,'\n    ',(null as any));
    this._text_49 = this.renderer.createText(this._el_24,'\n  ',(null as any));
    this._text_50 = this.renderer.createText(this._el_0,'\n\n  ',(null as any));
    this._el_51 = this.renderer.createElement(this._el_0,'div',(null as any));
    this.renderer.setElementAttribute(this._el_51,'class','news-footer clearfix ');
    this._text_52 = this.renderer.createText(this._el_51,'\n    ',(null as any));
    this._el_53 = this.renderer.createElement(this._el_51,'div',(null as any));
    this.renderer.setElementAttribute(this._el_53,'class','col-md-6 nopadding clearfix');
    this._text_54 = this.renderer.createText(this._el_53,'\n      ',(null as any));
    this._el_55 = this.renderer.createElement(this._el_53,'span',(null as any));
    this.renderer.setElementAttribute(this._el_55,'class','comment caption');
    this._el_56 = this.renderer.createElement(this._el_55,'i',(null as any));
    this.renderer.setElementAttribute(this._el_56,'class','icon-comment');
    this._text_57 = this.renderer.createText(this._el_55,'22',(null as any));
    this._text_58 = this.renderer.createText(this._el_53,'\n      ',(null as any));
    this._el_59 = this.renderer.createElement(this._el_53,'span',(null as any));
    this.renderer.setElementAttribute(this._el_59,'class','viewed caption');
    this._el_60 = this.renderer.createElement(this._el_59,'i',(null as any));
    this.renderer.setElementAttribute(this._el_60,'class','icon-eye');
    this._text_61 = this.renderer.createText(this._el_59,'',(null as any));
    this._text_62 = this.renderer.createText(this._el_53,'\n    ',(null as any));
    this._text_63 = this.renderer.createText(this._el_51,'\n    ',(null as any));
    this._el_64 = this.renderer.createElement(this._el_51,'div',(null as any));
    this.renderer.setElementAttribute(this._el_64,'class','col-md-6 nopadding clearfix text-right');
    this._text_65 = this.renderer.createText(this._el_64,'\n      ',(null as any));
    this._el_66 = this.renderer.createElement(this._el_64,'span',(null as any));
    this.renderer.setElementAttribute(this._el_66,'class','btn comment caption');
    this._text_67 = this.renderer.createText(this._el_66,'\n        ',(null as any));
    this._el_68 = this.renderer.createElement(this._el_66,'i',(null as any));
    this.renderer.setElementAttribute(this._el_68,'class','icon-like');
    this._text_69 = this.renderer.createText(this._el_66,'',(null as any));
    this._text_70 = this.renderer.createText(this._el_64,'\n      ',(null as any));
    this._anchor_71 = this.renderer.createTemplateAnchor(this._el_64,(null as any));
    this._appEl_71 = new import2.AppElement(71,64,this,this._anchor_71);
    this._TemplateRef_71_4 = new import19.TemplateRef_(this._appEl_71,viewFactory_ShowNews7);
    this._text_72 = this.renderer.createText(this._el_64,'\n      ',(null as any));
    this._el_73 = this.renderer.createElement(this._el_64,'button',(null as any));
    this.renderer.setElementAttribute(this._el_73,'class','btn viewed caption');
    this.renderer.setElementAttribute(this._el_73,'triggers','mouseenter:mouseleave');
    this._appEl_73 = new import2.AppElement(73,64,this,this._el_73);
    this._NgbPopover_73_5 = new import23.NgbPopover(new import13.ElementRef(this._el_73),this.renderer,this.injector(73),this.parentInjector.get(import28.ComponentFactoryResolver),this._appEl_73.vcRef,this.parentInjector.get(import29.NgbPopoverConfig),this.parentInjector.get(import30.NgZone));
    this._text_74 = this.renderer.createText(this._el_73,'\n        ',(null as any));
    this._el_75 = this.renderer.createElement(this._el_73,'i',(null as any));
    this.renderer.setElementAttribute(this._el_75,'class','icon-share');
    this._text_76 = this.renderer.createText(this._el_73,'',(null as any));
    this._text_77 = this.renderer.createText(this._el_64,'\n    ',(null as any));
    this._text_78 = this.renderer.createText(this._el_51,'\n  ',(null as any));
    this._text_79 = this.renderer.createText(this._el_0,'\n',(null as any));
    this._expr_0 = import7.UNINITIALIZED;
    this._expr_1 = import7.UNINITIALIZED;
    this._expr_2 = import7.UNINITIALIZED;
    this._expr_3 = import7.UNINITIALIZED;
    this._expr_4 = import7.UNINITIALIZED;
    this._expr_5 = import7.UNINITIALIZED;
    this._pipe_newsVideoChanger_0_0 = import4.pureProxy1((<_View_ShowNews0>this.parent)._pipe_newsVideoChanger_0.transform.bind((<_View_ShowNews0>this.parent)._pipe_newsVideoChanger_0));
    this._expr_6 = import7.UNINITIALIZED;
    var disposable_0:Function = this.renderer.listen(this._el_43,'click',this.eventHandler(this._handle_click_43_0.bind(this)));
    this._expr_8 = import7.UNINITIALIZED;
    this._expr_9 = import7.UNINITIALIZED;
    this._expr_10 = import7.UNINITIALIZED;
    var disposable_1:Function = this.renderer.listen(this._el_66,'click',this.eventHandler(this._handle_click_66_0.bind(this)));
    this._expr_12 = import7.UNINITIALIZED;
    var disposable_2:Function = this.renderer.listen(this._el_73,'click',this.eventHandler(this._handle_click_73_0.bind(this)));
    this._expr_14 = import7.UNINITIALIZED;
    this._expr_15 = import7.UNINITIALIZED;
    this._expr_16 = import7.UNINITIALIZED;
    this._expr_17 = import7.UNINITIALIZED;
    this.init([].concat([this._el_0]),[
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._el_4,
      this._text_5,
      this._el_6,
      this._text_7,
      this._el_8,
      this._text_9,
      this._text_10,
      this._el_11,
      this._text_12,
      this._text_13,
      this._el_14,
      this._text_15,
      this._text_16,
      this._text_17,
      this._el_18,
      this._text_19,
      this._el_20,
      this._text_21,
      this._text_22,
      this._text_23,
      this._el_24,
      this._text_25,
      this._el_26,
      this._text_27,
      this._el_28,
      this._text_29,
      this._el_30,
      this._text_31,
      this._anchor_32,
      this._text_33,
      this._text_34,
      this._el_35,
      this._text_36,
      this._anchor_37,
      this._text_38,
      this._el_39,
      this._text_40,
      this._anchor_41,
      this._text_42,
      this._el_43,
      this._text_44,
      this._text_45,
      this._text_46,
      this._text_47,
      this._text_48,
      this._text_49,
      this._text_50,
      this._el_51,
      this._text_52,
      this._el_53,
      this._text_54,
      this._el_55,
      this._el_56,
      this._text_57,
      this._text_58,
      this._el_59,
      this._el_60,
      this._text_61,
      this._text_62,
      this._text_63,
      this._el_64,
      this._text_65,
      this._el_66,
      this._text_67,
      this._el_68,
      this._text_69,
      this._text_70,
      this._anchor_71,
      this._text_72,
      this._el_73,
      this._text_74,
      this._el_75,
      this._text_76,
      this._text_77,
      this._text_78,
      this._text_79
    ]
    ,[
      disposable_0,
      disposable_1,
      disposable_2
    ]
    ,[]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import19.TemplateRef) && (32 === requestNodeIndex))) { return this._TemplateRef_32_5; }
    if (((token === import16.NgFor) && (32 === requestNodeIndex))) { return this._NgFor_32_6; }
    if (((token === import19.TemplateRef) && (37 === requestNodeIndex))) { return this._TemplateRef_37_5; }
    if (((token === import17.NgIf) && (37 === requestNodeIndex))) { return this._NgIf_37_6; }
    if (((token === import19.TemplateRef) && (41 === requestNodeIndex))) { return this._TemplateRef_41_5; }
    if (((token === import16.NgFor) && (41 === requestNodeIndex))) { return this._NgFor_41_6; }
    if (((token === import22.RouterLinkWithHref) && ((43 <= requestNodeIndex) && (requestNodeIndex <= 44)))) { return this._RouterLinkWithHref_43_3; }
    if (((token === import21.NgStyle) && ((28 <= requestNodeIndex) && (requestNodeIndex <= 47)))) { return this._NgStyle_28_3; }
    if (((token === import19.TemplateRef) && (71 === requestNodeIndex))) { return this._TemplateRef_71_4; }
    if (((token === import23.NgbPopover) && ((73 <= requestNodeIndex) && (requestNodeIndex <= 76)))) { return this._NgbPopover_73_5; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    var changes:{[key: string]:import7.SimpleChange} = (null as any);
    const valUnwrapper:any = new import7.ValueUnwrapper();
    const currVal_3:any = this.parent.context.getNewsStyles(this.context.$implicit);
    if (import4.checkBinding(throwOnChange,this._expr_3,currVal_3)) {
      this._NgStyle_28_3.ngStyle = currVal_3;
      this._expr_3 = currVal_3;
    }
    if (!throwOnChange) { this._NgStyle_28_3.ngDoCheck(); }
    changes = (null as any);
    const currVal_4:any = this.context.$implicit.tags;
    if (import4.checkBinding(throwOnChange,this._expr_4,currVal_4)) {
      this._NgFor_32_6.ngForOf = currVal_4;
      if ((changes === (null as any))) { (changes = {}); }
      changes['ngForOf'] = new import7.SimpleChange(this._expr_4,currVal_4);
      this._expr_4 = currVal_4;
    }
    if ((changes !== (null as any))) { this._NgFor_32_6.ngOnChanges(changes); }
    if (!throwOnChange) { this._NgFor_32_6.ngDoCheck(); }
    const currVal_5:any = this.context.$implicit.title;
    if (import4.checkBinding(throwOnChange,this._expr_5,currVal_5)) {
      this._NgIf_37_6.ngIf = currVal_5;
      this._expr_5 = currVal_5;
    }
    changes = (null as any);
    valUnwrapper.reset();
    const currVal_6:any = valUnwrapper.unwrap(import4.castByValue(this._pipe_newsVideoChanger_0_0,(<_View_ShowNews0>this.parent)._pipe_newsVideoChanger_0.transform)(this.context.$implicit.content)).split(this.parent.context.SPLIT_VIDEO_CONTENT_BY);
    if ((valUnwrapper.hasWrappedValue || import4.checkBinding(throwOnChange,this._expr_6,currVal_6))) {
      this._NgFor_41_6.ngForOf = currVal_6;
      if ((changes === (null as any))) { (changes = {}); }
      changes['ngForOf'] = new import7.SimpleChange(this._expr_6,currVal_6);
      this._expr_6 = currVal_6;
    }
    if ((changes !== (null as any))) { this._NgFor_41_6.ngOnChanges(changes); }
    if (!throwOnChange) { this._NgFor_41_6.ngDoCheck(); }
    changes = (null as any);
    const currVal_8:any = import4.interpolate(1,'/news/',this.context.$implicit.id,'');
    if (import4.checkBinding(throwOnChange,this._expr_8,currVal_8)) {
      this._RouterLinkWithHref_43_3.routerLink = currVal_8;
      if ((changes === (null as any))) { (changes = {}); }
      changes['routerLink'] = new import7.SimpleChange(this._expr_8,currVal_8);
      this._expr_8 = currVal_8;
    }
    if ((changes !== (null as any))) { this._RouterLinkWithHref_43_3.ngOnChanges(changes); }
    const currVal_14:any = this._TemplateRef_71_4;
    if (import4.checkBinding(throwOnChange,this._expr_14,currVal_14)) {
      this._NgbPopover_73_5.ngbPopover = currVal_14;
      this._expr_14 = currVal_14;
    }
    const currVal_15:any = this.parent.context.lS.translateByKey('pages.news.whoShared');
    if (import4.checkBinding(throwOnChange,this._expr_15,currVal_15)) {
      this._NgbPopover_73_5.popoverTitle = currVal_15;
      this._expr_15 = currVal_15;
    }
    const currVal_16:any = 'mouseenter:mouseleave';
    if (import4.checkBinding(throwOnChange,this._expr_16,currVal_16)) {
      this._NgbPopover_73_5.triggers = currVal_16;
      this._expr_16 = currVal_16;
    }
    if (((this.numberOfChecks === 0) && !throwOnChange)) { this._NgbPopover_73_5.ngOnInit(); }
    this.detectContentChildrenChanges(throwOnChange);
    const currVal_0:any = this.parent.context.userInformationService.showUserProfileAvatar();
    if (import4.checkBinding(throwOnChange,this._expr_0,currVal_0)) {
      this.renderer.setElementProperty(this._el_8,'src',this.viewUtils.sanitizer.sanitize(import31.SecurityContext.URL,currVal_0));
      this._expr_0 = currVal_0;
    }
    const currVal_1:any = import4.interpolate(1,'',((this.parent.context.userInformationService.userInformation == (null as any))? (null as any): this.parent.context.userInformationService.userInformation.name),'');
    if (import4.checkBinding(throwOnChange,this._expr_1,currVal_1)) {
      this.renderer.setText(this._text_12,currVal_1);
      this._expr_1 = currVal_1;
    }
    const currVal_2:any = import4.interpolate(1,'',this.parent.context.getTime(this.context.$implicit.created_at),'');
    if (import4.checkBinding(throwOnChange,this._expr_2,currVal_2)) {
      this.renderer.setText(this._text_15,currVal_2);
      this._expr_2 = currVal_2;
    }
    const currVal_9:any = this._RouterLinkWithHref_43_3.href;
    if (import4.checkBinding(throwOnChange,this._expr_9,currVal_9)) {
      this.renderer.setElementProperty(this._el_43,'href',this.viewUtils.sanitizer.sanitize(import31.SecurityContext.URL,currVal_9));
      this._expr_9 = currVal_9;
    }
    const currVal_10:any = import4.interpolate(1,'',this.context.$implicit.views_count,'');
    if (import4.checkBinding(throwOnChange,this._expr_10,currVal_10)) {
      this.renderer.setText(this._text_61,currVal_10);
      this._expr_10 = currVal_10;
    }
    const currVal_12:any = import4.interpolate(1,' ',this.context.$implicit.like_count,'\n      ');
    if (import4.checkBinding(throwOnChange,this._expr_12,currVal_12)) {
      this.renderer.setText(this._text_69,currVal_12);
      this._expr_12 = currVal_12;
    }
    const currVal_17:any = import4.interpolate(1,'',this.context.$implicit.share_count,'\n      ');
    if (import4.checkBinding(throwOnChange,this._expr_17,currVal_17)) {
      this.renderer.setText(this._text_76,currVal_17);
      this._expr_17 = currVal_17;
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
  destroyInternal():void {
    this._RouterLinkWithHref_43_3.ngOnDestroy();
    this._NgbPopover_73_5.ngOnDestroy();
  }
  private _handle_click_43_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._RouterLinkWithHref_43_3.onClick($event.button,$event.ctrlKey,$event.metaKey)) !== false);
    return (true && pd_0);
  }
  private _handle_click_66_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.parent.context.newsService.likeNews(this.context.$implicit.id)) !== false);
    return (true && pd_0);
  }
  private _handle_click_73_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.parent.context.newsService.shareNews(this.context.$implicit.id)) !== false);
    return (true && pd_0);
  }
}
function viewFactory_ShowNews1(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  return new _View_ShowNews1(viewUtils,parentInjector,declarationEl);
}
class _View_ShowNews2 extends import1.AppView<any> {
  _el_0:any;
  _RouterLinkWithHref_0_3:import22.RouterLinkWithHref;
  _text_1:any;
  _map_0:any;
  _arr_0:any;
  /*private*/ _expr_1:any;
  /*private*/ _expr_2:any;
  /*private*/ _expr_3:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_ShowNews2,renderType_ShowNews,import6.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'a',(null as any));
    this.renderer.setElementAttribute(this._el_0,'class','label label-info');
    this._RouterLinkWithHref_0_3 = new import22.RouterLinkWithHref(this.parent.parentInjector.get(import25.Router),this.parent.parentInjector.get(import26.ActivatedRoute),this.parent.parentInjector.get(import27.LocationStrategy));
    this._text_1 = this.renderer.createText(this._el_0,'',(null as any));
    var disposable_0:Function = this.renderer.listen(this._el_0,'click',this.eventHandler(this._handle_click_0_0.bind(this)));
    this._map_0 = import4.pureProxy1((p0:any):{[key: string]:any} => {
      return {tags: p0};
    });
    this._arr_0 = import4.pureProxy2((p0:any,p1:any):any[] => {
      return [
        p0,
        p1
      ]
      ;
    });
    this._expr_1 = import7.UNINITIALIZED;
    this._expr_2 = import7.UNINITIALIZED;
    this._expr_3 = import7.UNINITIALIZED;
    this.init([].concat([this._el_0]),[
      this._el_0,
      this._text_1
    ]
    ,[disposable_0],[]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import22.RouterLinkWithHref) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 1)))) { return this._RouterLinkWithHref_0_3; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    var changes:{[key: string]:import7.SimpleChange} = (null as any);
    changes = (null as any);
    const currVal_1:any = this._arr_0('/search',this._map_0((this.context.$implicit.name || this.context.$implicit)));
    if (import4.checkBinding(throwOnChange,this._expr_1,currVal_1)) {
      this._RouterLinkWithHref_0_3.routerLink = currVal_1;
      if ((changes === (null as any))) { (changes = {}); }
      changes['routerLink'] = new import7.SimpleChange(this._expr_1,currVal_1);
      this._expr_1 = currVal_1;
    }
    if ((changes !== (null as any))) { this._RouterLinkWithHref_0_3.ngOnChanges(changes); }
    this.detectContentChildrenChanges(throwOnChange);
    const currVal_2:any = this._RouterLinkWithHref_0_3.href;
    if (import4.checkBinding(throwOnChange,this._expr_2,currVal_2)) {
      this.renderer.setElementProperty(this._el_0,'href',this.viewUtils.sanitizer.sanitize(import31.SecurityContext.URL,currVal_2));
      this._expr_2 = currVal_2;
    }
    const currVal_3:any = import4.interpolate(1,'\n            ',(this.context.$implicit.name || this.context.$implicit),'\n          ');
    if (import4.checkBinding(throwOnChange,this._expr_3,currVal_3)) {
      this.renderer.setText(this._text_1,currVal_3);
      this._expr_3 = currVal_3;
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
  destroyInternal():void {
    this._RouterLinkWithHref_0_3.ngOnDestroy();
  }
  private _handle_click_0_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._RouterLinkWithHref_0_3.onClick($event.button,$event.ctrlKey,$event.metaKey)) !== false);
    return (true && pd_0);
  }
}
function viewFactory_ShowNews2(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  return new _View_ShowNews2(viewUtils,parentInjector,declarationEl);
}
class _View_ShowNews3 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _expr_0:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_ShowNews3,renderType_ShowNews,import6.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'h1',(null as any));
    this._expr_0 = import7.UNINITIALIZED;
    this.init([].concat([this._el_0]),[this._el_0],[],[]);
    return (null as any);
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this.detectContentChildrenChanges(throwOnChange);
    const currVal_0:any = this.parent.context.$implicit.title;
    if (import4.checkBinding(throwOnChange,this._expr_0,currVal_0)) {
      this.renderer.setElementProperty(this._el_0,'innerHTML',this.viewUtils.sanitizer.sanitize(import31.SecurityContext.HTML,currVal_0));
      this._expr_0 = currVal_0;
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
}
function viewFactory_ShowNews3(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  return new _View_ShowNews3(viewUtils,parentInjector,declarationEl);
}
class _View_ShowNews4 extends import1.AppView<any> {
  _el_0:any;
  _text_1:any;
  _anchor_2:any;
  /*private*/ _appEl_2:import2.AppElement;
  _TemplateRef_2_5:any;
  _NgIf_2_6:import17.NgIf;
  _text_3:any;
  _anchor_4:any;
  /*private*/ _appEl_4:import2.AppElement;
  _TemplateRef_4_5:any;
  _NgIf_4_6:import17.NgIf;
  _text_5:any;
  /*private*/ _expr_0:any;
  /*private*/ _expr_1:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_ShowNews4,renderType_ShowNews,import6.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'div',(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'\n              ',(null as any));
    this._anchor_2 = this.renderer.createTemplateAnchor(this._el_0,(null as any));
    this._appEl_2 = new import2.AppElement(2,0,this,this._anchor_2);
    this._TemplateRef_2_5 = new import19.TemplateRef_(this._appEl_2,viewFactory_ShowNews5);
    this._NgIf_2_6 = new import17.NgIf(this._appEl_2.vcRef,this._TemplateRef_2_5);
    this._text_3 = this.renderer.createText(this._el_0,'\n              ',(null as any));
    this._anchor_4 = this.renderer.createTemplateAnchor(this._el_0,(null as any));
    this._appEl_4 = new import2.AppElement(4,0,this,this._anchor_4);
    this._TemplateRef_4_5 = new import19.TemplateRef_(this._appEl_4,viewFactory_ShowNews6);
    this._NgIf_4_6 = new import17.NgIf(this._appEl_4.vcRef,this._TemplateRef_4_5);
    this._text_5 = this.renderer.createText(this._el_0,'\n            ',(null as any));
    this._expr_0 = import7.UNINITIALIZED;
    this._expr_1 = import7.UNINITIALIZED;
    this.init([].concat([this._el_0]),[
      this._el_0,
      this._text_1,
      this._anchor_2,
      this._text_3,
      this._anchor_4,
      this._text_5
    ]
    ,[],[]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import19.TemplateRef) && (2 === requestNodeIndex))) { return this._TemplateRef_2_5; }
    if (((token === import17.NgIf) && (2 === requestNodeIndex))) { return this._NgIf_2_6; }
    if (((token === import19.TemplateRef) && (4 === requestNodeIndex))) { return this._TemplateRef_4_5; }
    if (((token === import17.NgIf) && (4 === requestNodeIndex))) { return this._NgIf_4_6; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_0:any = this.parent.parent.context.isContentHTML(this.context.$implicit);
    if (import4.checkBinding(throwOnChange,this._expr_0,currVal_0)) {
      this._NgIf_2_6.ngIf = currVal_0;
      this._expr_0 = currVal_0;
    }
    const currVal_1:any = this.parent.parent.context.isContentImg(this.context.$implicit);
    if (import4.checkBinding(throwOnChange,this._expr_1,currVal_1)) {
      this._NgIf_4_6.ngIf = currVal_1;
      this._expr_1 = currVal_1;
    }
    this.detectContentChildrenChanges(throwOnChange);
    this.detectViewChildrenChanges(throwOnChange);
  }
}
function viewFactory_ShowNews4(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  return new _View_ShowNews4(viewUtils,parentInjector,declarationEl);
}
class _View_ShowNews5 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _expr_0:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_ShowNews5,renderType_ShowNews,import6.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'div',(null as any));
    this._expr_0 = import7.UNINITIALIZED;
    this.init([].concat([this._el_0]),[this._el_0],[],[]);
    return (null as any);
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this.detectContentChildrenChanges(throwOnChange);
    const currVal_0:any = this.parent.parent.parent.context.sanitizer.bypassSecurityTrustHtml(this.parent.context.$implicit);
    if (import4.checkBinding(throwOnChange,this._expr_0,currVal_0)) {
      this.renderer.setElementProperty(this._el_0,'innerHTML',this.viewUtils.sanitizer.sanitize(import31.SecurityContext.HTML,currVal_0));
      this._expr_0 = currVal_0;
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
}
function viewFactory_ShowNews5(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  return new _View_ShowNews5(viewUtils,parentInjector,declarationEl);
}
class _View_ShowNews6 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _expr_1:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_ShowNews6,renderType_ShowNews,import6.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'img',(null as any));
    this._expr_1 = import7.UNINITIALIZED;
    var disposable_0:Function = this.renderer.listen(this._el_0,'click',this.eventHandler(this._handle_click_0_0.bind(this)));
    this.init([].concat([this._el_0]),[this._el_0],[disposable_0],[]);
    return (null as any);
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this.detectContentChildrenChanges(throwOnChange);
    const currVal_1:any = this.parent.parent.parent.context.getImageUrl(this.parent.context.$implicit);
    if (import4.checkBinding(throwOnChange,this._expr_1,currVal_1)) {
      this.renderer.setElementProperty(this._el_0,'src',this.viewUtils.sanitizer.sanitize(import31.SecurityContext.URL,currVal_1));
      this._expr_1 = currVal_1;
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
  private _handle_click_0_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.parent.parent.parent.context.handlePlayVideoClick(this.parent.context.$implicit)) !== false);
    return (true && pd_0);
  }
}
function viewFactory_ShowNews6(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  return new _View_ShowNews6(viewUtils,parentInjector,declarationEl);
}
class _View_ShowNews7 extends import1.AppView<any> {
  _text_0:any;
  _anchor_1:any;
  /*private*/ _appEl_1:import2.AppElement;
  _TemplateRef_1_5:any;
  _NgFor_1_6:import16.NgFor;
  _text_2:any;
  /*private*/ _expr_0:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_ShowNews7,renderType_ShowNews,import6.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._text_0 = this.renderer.createText((null as any),'\n        ',(null as any));
    this._anchor_1 = this.renderer.createTemplateAnchor((null as any),(null as any));
    this._appEl_1 = new import2.AppElement(1,(null as any),this,this._anchor_1);
    this._TemplateRef_1_5 = new import19.TemplateRef_(this._appEl_1,viewFactory_ShowNews8);
    this._NgFor_1_6 = new import16.NgFor(this._appEl_1.vcRef,this._TemplateRef_1_5,this.parent.parentInjector.get(import20.IterableDiffers),this.parent.parent.ref);
    this._text_2 = this.renderer.createText((null as any),'\n      ',(null as any));
    this._expr_0 = import7.UNINITIALIZED;
    this.init([].concat([
      this._text_0,
      this._appEl_1,
      this._text_2
    ]
    ),[
      this._text_0,
      this._anchor_1,
      this._text_2
    ]
    ,[],[]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import19.TemplateRef) && (1 === requestNodeIndex))) { return this._TemplateRef_1_5; }
    if (((token === import16.NgFor) && (1 === requestNodeIndex))) { return this._NgFor_1_6; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    var changes:{[key: string]:import7.SimpleChange} = (null as any);
    changes = (null as any);
    const currVal_0:any = this.parent.parent.context.whoShared(this.parent.context.$implicit.id);
    if (import4.checkBinding(throwOnChange,this._expr_0,currVal_0)) {
      this._NgFor_1_6.ngForOf = currVal_0;
      if ((changes === (null as any))) { (changes = {}); }
      changes['ngForOf'] = new import7.SimpleChange(this._expr_0,currVal_0);
      this._expr_0 = currVal_0;
    }
    if ((changes !== (null as any))) { this._NgFor_1_6.ngOnChanges(changes); }
    if (!throwOnChange) { this._NgFor_1_6.ngDoCheck(); }
    this.detectContentChildrenChanges(throwOnChange);
    this.detectViewChildrenChanges(throwOnChange);
  }
}
function viewFactory_ShowNews7(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  return new _View_ShowNews7(viewUtils,parentInjector,declarationEl);
}
class _View_ShowNews8 extends import1.AppView<any> {
  _el_0:any;
  _text_1:any;
  _text_2:any;
  /*private*/ _expr_0:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_ShowNews8,renderType_ShowNews,import6.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'span',(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'\n          ',(null as any));
    this._text_2 = this.renderer.createText(this._el_0,'',(null as any));
    this._expr_0 = import7.UNINITIALIZED;
    this.init([].concat([this._el_0]),[
      this._el_0,
      this._text_1,
      this._text_2
    ]
    ,[],[]);
    return (null as any);
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this.detectContentChildrenChanges(throwOnChange);
    const currVal_0:any = import4.interpolate(1,'\n          ',this.context.$implicit.nickname,'\n        ');
    if (import4.checkBinding(throwOnChange,this._expr_0,currVal_0)) {
      this.renderer.setText(this._text_2,currVal_0);
      this._expr_0 = currVal_0;
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
}
function viewFactory_ShowNews8(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  return new _View_ShowNews8(viewUtils,parentInjector,declarationEl);
}
class _View_ShowNews9 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import2.AppElement;
  _NewsVideoPopup_0_4:import32.NewsVideoPopup;
  /*private*/ _expr_1:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_ShowNews9,renderType_ShowNews,import6.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'news-video-popup',(null as any));
    this._appEl_0 = new import2.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = import33.viewFactory_NewsVideoPopup0(this.viewUtils,this.injector(0),this._appEl_0);
    this._NewsVideoPopup_0_4 = new import32.NewsVideoPopup(compView_0.ref,this.parentInjector.get(import12.DomSanitizer));
    this._appEl_0.initComponent(this._NewsVideoPopup_0_4,[],compView_0);
    compView_0.create(this._NewsVideoPopup_0_4,[],(null as any));
    var disposable_0:Function = this.renderer.listen(this._el_0,'hideVideoPopup',this.eventHandler(this._handle_hideVideoPopup_0_0.bind(this)));
    this._expr_1 = import7.UNINITIALIZED;
    const subscription_0:any = this._NewsVideoPopup_0_4.hideVideoPopup.subscribe(this.eventHandler(this._handle_hideVideoPopup_0_0.bind(this)));
    this.init([].concat([this._el_0]),[this._el_0],[disposable_0],[subscription_0]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import32.NewsVideoPopup) && (0 === requestNodeIndex))) { return this._NewsVideoPopup_0_4; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_1:any = this.parent.context.activeVideoUrl;
    if (import4.checkBinding(throwOnChange,this._expr_1,currVal_1)) {
      this._NewsVideoPopup_0_4.activeVideoUrl = currVal_1;
      this._expr_1 = currVal_1;
    }
    this.detectContentChildrenChanges(throwOnChange);
    this.detectViewChildrenChanges(throwOnChange);
    if (!throwOnChange) { if ((this.numberOfChecks === 0)) { this._NewsVideoPopup_0_4.ngAfterViewInit(); } }
  }
  private _handle_hideVideoPopup_0_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.parent.context.newsVideoPopupClose($event)) !== false);
    return (true && pd_0);
  }
}
function viewFactory_ShowNews9(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  return new _View_ShowNews9(viewUtils,parentInjector,declarationEl);
}