/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

import * as import0 from '@angular/core/src/render/api';
import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/linker/element';
import * as import3 from './Search';
import * as import4 from '@angular/core/src/linker/view_utils';
import * as import5 from '@angular/core/src/di/injector';
import * as import6 from '@angular/core/src/linker/view_type';
import * as import7 from '@angular/core/src/change_detection/change_detection';
import * as import8 from '@angular/router/src/router_state';
import * as import9 from '../../../services/NewsService';
import * as import10 from 'ng2-toastr/src/toast-manager';
import * as import11 from '@angular/common/src/location/location';
import * as import12 from '@angular/core/src/metadata/view';
import * as import13 from '@angular/core/src/linker/component_factory';
import * as import14 from '../../../editors/tagInput/components/tag-input/TagInput';
import * as import15 from '@angular/forms/src/directives/ng_model';
import * as import16 from '@angular/forms/src/directives/ng_control_status';
import * as import17 from '../news/showNews/ShowNews';
import * as import18 from '../../../editors/tagInput/components/tag-input/TagInput.ngfactory';
import * as import19 from '@angular/forms/src/form_builder';
import * as import20 from '@angular/core/src/linker/element_ref';
import * as import21 from '../news/showNews/ShowNews.ngfactory';
import * as import22 from '../../../services/LocalizationService';
import * as import23 from '../../../services/AuthService';
import * as import24 from '../../../services/UserInformationService';
import * as import25 from '@angular/platform-browser/src/security/dom_sanitization_service';
import * as import26 from '@angular/forms/src/directives/control_value_accessor';
import * as import27 from '@angular/forms/src/directives/ng_control';
var renderType_Search_Host:import0.RenderComponentType = (null as any);
class _View_Search_Host0 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import2.AppElement;
  _Search_0_4:import3.Search;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_Search_Host0,renderType_Search_Host,import6.ViewType.HOST,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.selectOrCreateHostElement('search',rootSelector,(null as any));
    this._appEl_0 = new import2.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = viewFactory_Search0(this.viewUtils,this.injector(0),this._appEl_0);
    this._Search_0_4 = new import3.Search(this.parentInjector.get(import8.ActivatedRoute),this.parentInjector.get(import9.NewsService),this.parentInjector.get(import10.ToastsManager),this.parentInjector.get(import11.Location));
    this._appEl_0.initComponent(this._Search_0_4,[],compView_0);
    compView_0.create(this._Search_0_4,this.projectableNodes,(null as any));
    this.init([].concat([this._el_0]),[this._el_0],[],[]);
    return this._appEl_0;
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import3.Search) && (0 === requestNodeIndex))) { return this._Search_0_4; }
    return notFoundResult;
  }
}
function viewFactory_Search_Host0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  if ((renderType_Search_Host === (null as any))) { (renderType_Search_Host = viewUtils.createRenderComponentType('',0,import12.ViewEncapsulation.None,[],{})); }
  return new _View_Search_Host0(viewUtils,parentInjector,declarationEl);
}
export const SearchNgFactory:import13.ComponentFactory<import3.Search> = new import13.ComponentFactory<import3.Search>('search',viewFactory_Search_Host0,import3.Search);
const styles_Search:any[] = [];
var renderType_Search:import0.RenderComponentType = (null as any);
class _View_Search0 extends import1.AppView<import3.Search> {
  _el_0:any;
  /*private*/ _appEl_0:import2.AppElement;
  _TagInputComponent_0_4:import14.TagInputComponent;
  _NG_VALUE_ACCESSOR_0_5:any[];
  _NgModel_0_6:import15.NgModel;
  _NgControl_0_7:any;
  _NgControlStatus_0_8:import16.NgControlStatus;
  _text_1:any;
  _text_2:any;
  _el_3:any;
  /*private*/ _appEl_3:import2.AppElement;
  _ShowNews_3_4:import17.ShowNews;
  /*private*/ _expr_4:any;
  /*private*/ _expr_5:any;
  /*private*/ _expr_6:any;
  /*private*/ _expr_7:any;
  /*private*/ _expr_8:any;
  /*private*/ _expr_9:any;
  /*private*/ _expr_10:any;
  /*private*/ _expr_11:any;
  /*private*/ _expr_12:any;
  /*private*/ _expr_13:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_Search0,renderType_Search,import6.ViewType.COMPONENT,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    const parentRenderNode:any = this.renderer.createViewRoot(this.declarationAppElement.nativeElement);
    this._el_0 = this.renderer.createElement(parentRenderNode,'rl-tag-input',(null as any));
    this.renderer.setElementAttribute(this._el_0,'placeholder','Поиск по тегам');
    this._appEl_0 = new import2.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = import18.viewFactory_TagInputComponent0(this.viewUtils,this.injector(0),this._appEl_0);
    this._TagInputComponent_0_4 = new import14.TagInputComponent(this.parentInjector.get(import19.FormBuilder),new import20.ElementRef(this._el_0));
    this._NG_VALUE_ACCESSOR_0_5 = [this._TagInputComponent_0_4];
    this._NgModel_0_6 = new import15.NgModel((null as any),(null as any),(null as any),this._NG_VALUE_ACCESSOR_0_5);
    this._NgControl_0_7 = this._NgModel_0_6;
    this._NgControlStatus_0_8 = new import16.NgControlStatus(this._NgControl_0_7);
    this._appEl_0.initComponent(this._TagInputComponent_0_4,[],compView_0);
    this._text_1 = this.renderer.createText((null as any),'\n',(null as any));
    compView_0.create(this._TagInputComponent_0_4,[],(null as any));
    this._text_2 = this.renderer.createText(parentRenderNode,'\n',(null as any));
    this._el_3 = this.renderer.createElement(parentRenderNode,'show-news',(null as any));
    this._appEl_3 = new import2.AppElement(3,(null as any),this,this._el_3);
    var compView_3:any = import21.viewFactory_ShowNews0(this.viewUtils,this.injector(3),this._appEl_3);
    this._ShowNews_3_4 = new import17.ShowNews(this.parentInjector.get(import9.NewsService),this.parentInjector.get(import22.LocalizationService),this.parentInjector.get(import23.AuthService),this.parentInjector.get(import24.UserInformationService),this.parentInjector.get(import25.DomSanitizer),new import20.ElementRef(this._el_3),this.renderer);
    this._appEl_3.initComponent(this._ShowNews_3_4,[],compView_3);
    compView_3.create(this._ShowNews_3_4,[],(null as any));
    var disposable_0:Function = this.renderer.listen(this._el_0,'ngModelChange',this.eventHandler(this._handle_ngModelChange_0_0.bind(this)));
    var disposable_1:Function = this.renderer.listen(this._el_0,'removeTag',this.eventHandler(this._handle_removeTag_0_1.bind(this)));
    var disposable_2:Function = this.renderer.listen(this._el_0,'addTag',this.eventHandler(this._handle_addTag_0_2.bind(this)));
    var disposable_3:Function = this.renderer.listenGlobal('document','click',this.eventHandler(this._handle_click_0_3.bind(this)));
    this._expr_4 = import7.UNINITIALIZED;
    this._expr_5 = import7.UNINITIALIZED;
    const subscription_0:any = this._TagInputComponent_0_4.addTag.subscribe(this.eventHandler(this._handle_addTag_0_2.bind(this)));
    const subscription_1:any = this._TagInputComponent_0_4.removeTag.subscribe(this.eventHandler(this._handle_removeTag_0_1.bind(this)));
    this._expr_6 = import7.UNINITIALIZED;
    const subscription_2:any = this._NgModel_0_6.update.subscribe(this.eventHandler(this._handle_ngModelChange_0_0.bind(this)));
    this._expr_7 = import7.UNINITIALIZED;
    this._expr_8 = import7.UNINITIALIZED;
    this._expr_9 = import7.UNINITIALIZED;
    this._expr_10 = import7.UNINITIALIZED;
    this._expr_11 = import7.UNINITIALIZED;
    this._expr_12 = import7.UNINITIALIZED;
    this._expr_13 = import7.UNINITIALIZED;
    this.init([],[
      this._el_0,
      this._text_1,
      this._text_2,
      this._el_3
    ]
    ,[
      disposable_0,
      disposable_1,
      disposable_2,
      disposable_3
    ]
    ,[
      subscription_0,
      subscription_1,
      subscription_2
    ]
    );
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import14.TagInputComponent) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 1)))) { return this._TagInputComponent_0_4; }
    if (((token === import26.NG_VALUE_ACCESSOR) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 1)))) { return this._NG_VALUE_ACCESSOR_0_5; }
    if (((token === import15.NgModel) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 1)))) { return this._NgModel_0_6; }
    if (((token === import27.NgControl) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 1)))) { return this._NgControl_0_7; }
    if (((token === import16.NgControlStatus) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 1)))) { return this._NgControlStatus_0_8; }
    if (((token === import17.ShowNews) && (3 === requestNodeIndex))) { return this._ShowNews_3_4; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    var changes:{[key: string]:import7.SimpleChange} = (null as any);
    const currVal_4:any = 'Поиск по тегам';
    if (import4.checkBinding(throwOnChange,this._expr_4,currVal_4)) {
      this._TagInputComponent_0_4.placeholder = currVal_4;
      this._expr_4 = currVal_4;
    }
    if (((this.numberOfChecks === 0) && !throwOnChange)) { this._TagInputComponent_0_4.ngOnInit(); }
    changes = (null as any);
    const currVal_6:any = this.context.tags;
    if (import4.checkBinding(throwOnChange,this._expr_6,currVal_6)) {
      this._NgModel_0_6.model = currVal_6;
      if ((changes === (null as any))) { (changes = {}); }
      changes['model'] = new import7.SimpleChange(this._expr_6,currVal_6);
      this._expr_6 = currVal_6;
    }
    if ((changes !== (null as any))) { this._NgModel_0_6.ngOnChanges(changes); }
    const currVal_13:any = this.context.filteredNews;
    if (import4.checkBinding(throwOnChange,this._expr_13,currVal_13)) {
      this._ShowNews_3_4.news = currVal_13;
      this._expr_13 = currVal_13;
    }
    this.detectContentChildrenChanges(throwOnChange);
    const currVal_5:any = this._TagInputComponent_0_4.isFocused;
    if (import4.checkBinding(throwOnChange,this._expr_5,currVal_5)) {
      this.renderer.setElementClass(this._el_0,'ng2-tag-input-focus',currVal_5);
      this._expr_5 = currVal_5;
    }
    const currVal_7:any = this._NgControlStatus_0_8.ngClassUntouched;
    if (import4.checkBinding(throwOnChange,this._expr_7,currVal_7)) {
      this.renderer.setElementClass(this._el_0,'ng-untouched',currVal_7);
      this._expr_7 = currVal_7;
    }
    const currVal_8:any = this._NgControlStatus_0_8.ngClassTouched;
    if (import4.checkBinding(throwOnChange,this._expr_8,currVal_8)) {
      this.renderer.setElementClass(this._el_0,'ng-touched',currVal_8);
      this._expr_8 = currVal_8;
    }
    const currVal_9:any = this._NgControlStatus_0_8.ngClassPristine;
    if (import4.checkBinding(throwOnChange,this._expr_9,currVal_9)) {
      this.renderer.setElementClass(this._el_0,'ng-pristine',currVal_9);
      this._expr_9 = currVal_9;
    }
    const currVal_10:any = this._NgControlStatus_0_8.ngClassDirty;
    if (import4.checkBinding(throwOnChange,this._expr_10,currVal_10)) {
      this.renderer.setElementClass(this._el_0,'ng-dirty',currVal_10);
      this._expr_10 = currVal_10;
    }
    const currVal_11:any = this._NgControlStatus_0_8.ngClassValid;
    if (import4.checkBinding(throwOnChange,this._expr_11,currVal_11)) {
      this.renderer.setElementClass(this._el_0,'ng-valid',currVal_11);
      this._expr_11 = currVal_11;
    }
    const currVal_12:any = this._NgControlStatus_0_8.ngClassInvalid;
    if (import4.checkBinding(throwOnChange,this._expr_12,currVal_12)) {
      this.renderer.setElementClass(this._el_0,'ng-invalid',currVal_12);
      this._expr_12 = currVal_12;
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
  destroyInternal():void {
    this._TagInputComponent_0_4.ngOnDestroy();
    this._NgModel_0_6.ngOnDestroy();
  }
  private _handle_ngModelChange_0_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>(this.context.tags = $event)) !== false);
    return (true && pd_0);
  }
  private _handle_removeTag_0_1($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.context.filterNews(this.context.tags)) !== false);
    return (true && pd_0);
  }
  private _handle_addTag_0_2($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.context.filterNews(this.context.tags)) !== false);
    return (true && pd_0);
  }
  private _handle_click_0_3($event:any):boolean {
    this._appEl_0.componentView.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._TagInputComponent_0_4.onDocumentClick($event,$event.target)) !== false);
    return (true && pd_0);
  }
}
export function viewFactory_Search0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<import3.Search> {
  if ((renderType_Search === (null as any))) { (renderType_Search = viewUtils.createRenderComponentType('',0,import12.ViewEncapsulation.None,styles_Search,{})); }
  return new _View_Search0(viewUtils,parentInjector,declarationEl);
}