/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

import * as import0 from '@angular/core/src/render/api';
import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/linker/element';
import * as import3 from './ModalAdapter';
import * as import4 from '@angular/core/src/linker/view_utils';
import * as import5 from '@angular/core/src/di/injector';
import * as import6 from '@angular/core/src/linker/view_type';
import * as import7 from '@angular/core/src/change_detection/change_detection';
import * as import8 from '../../services/ModalService';
import * as import9 from '@angular/core/src/metadata/view';
import * as import10 from '@angular/core/src/linker/component_factory';
import * as import11 from '@angular/common/src/directives/ng_switch';
import * as import12 from '@angular/core/src/linker/template_ref';
import * as import13 from './registrationModal/RegistrationModal';
import * as import14 from './registrationModal/RegistrationModal.ngfactory';
import * as import15 from '@angular/http/src/http';
import * as import16 from '../../services/UserInformationService';
import * as import17 from '../../services/AuthService';
import * as import18 from '../../services/LocalStorageService';
import * as import19 from 'ng2-toastr/src/toast-manager';
import * as import20 from './loginModal/LoginModal';
import * as import21 from './loginModal/LoginModal.ngfactory';
import * as import22 from './confirmEmailModal/ConfirmEmailModal';
import * as import23 from './confirmEmailModal/ConfirmEmailModal.ngfactory';
import * as import24 from '../../services/LocalizationService';
import * as import25 from './addNewsModal/addNewsModal';
import * as import26 from './addNewsModal/addNewsModal.ngfactory';
var renderType_ModalAdapter_Host:import0.RenderComponentType = (null as any);
class _View_ModalAdapter_Host0 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import2.AppElement;
  _ModalAdapter_0_4:import3.ModalAdapter;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_ModalAdapter_Host0,renderType_ModalAdapter_Host,import6.ViewType.HOST,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.selectOrCreateHostElement('modal-adapter',rootSelector,(null as any));
    this._appEl_0 = new import2.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = viewFactory_ModalAdapter0(this.viewUtils,this.injector(0),this._appEl_0);
    this._ModalAdapter_0_4 = new import3.ModalAdapter(this.parentInjector.get(import8.ModalService));
    this._appEl_0.initComponent(this._ModalAdapter_0_4,[],compView_0);
    compView_0.create(this._ModalAdapter_0_4,this.projectableNodes,(null as any));
    this.init([].concat([this._el_0]),[this._el_0],[],[]);
    return this._appEl_0;
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import3.ModalAdapter) && (0 === requestNodeIndex))) { return this._ModalAdapter_0_4; }
    return notFoundResult;
  }
}
function viewFactory_ModalAdapter_Host0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  if ((renderType_ModalAdapter_Host === (null as any))) { (renderType_ModalAdapter_Host = viewUtils.createRenderComponentType('',0,import9.ViewEncapsulation.None,[],{})); }
  return new _View_ModalAdapter_Host0(viewUtils,parentInjector,declarationEl);
}
export const ModalAdapterNgFactory:import10.ComponentFactory<import3.ModalAdapter> = new import10.ComponentFactory<import3.ModalAdapter>('modal-adapter',viewFactory_ModalAdapter_Host0,import3.ModalAdapter);
const styles_ModalAdapter:any[] = [];
var renderType_ModalAdapter:import0.RenderComponentType = (null as any);
class _View_ModalAdapter0 extends import1.AppView<import3.ModalAdapter> {
  _el_0:any;
  _NgSwitch_0_3:import11.NgSwitch;
  _text_1:any;
  _anchor_2:any;
  /*private*/ _appEl_2:import2.AppElement;
  _TemplateRef_2_5:any;
  _NgSwitchCase_2_6:import11.NgSwitchCase;
  _text_3:any;
  _anchor_4:any;
  /*private*/ _appEl_4:import2.AppElement;
  _TemplateRef_4_5:any;
  _NgSwitchCase_4_6:import11.NgSwitchCase;
  _text_5:any;
  _anchor_6:any;
  /*private*/ _appEl_6:import2.AppElement;
  _TemplateRef_6_5:any;
  _NgSwitchCase_6_6:import11.NgSwitchCase;
  _text_7:any;
  _anchor_8:any;
  /*private*/ _appEl_8:import2.AppElement;
  _TemplateRef_8_5:any;
  _NgSwitchCase_8_6:import11.NgSwitchCase;
  _text_9:any;
  /*private*/ _expr_0:any;
  /*private*/ _expr_1:any;
  /*private*/ _expr_2:any;
  /*private*/ _expr_3:any;
  /*private*/ _expr_4:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_ModalAdapter0,renderType_ModalAdapter,import6.ViewType.COMPONENT,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    const parentRenderNode:any = this.renderer.createViewRoot(this.declarationAppElement.nativeElement);
    this._el_0 = this.renderer.createElement(parentRenderNode,'div',(null as any));
    this._NgSwitch_0_3 = new import11.NgSwitch();
    this._text_1 = this.renderer.createText(this._el_0,'\n  ',(null as any));
    this._anchor_2 = this.renderer.createTemplateAnchor(this._el_0,(null as any));
    this._appEl_2 = new import2.AppElement(2,0,this,this._anchor_2);
    this._TemplateRef_2_5 = new import12.TemplateRef_(this._appEl_2,viewFactory_ModalAdapter1);
    this._NgSwitchCase_2_6 = new import11.NgSwitchCase(this._appEl_2.vcRef,this._TemplateRef_2_5,this._NgSwitch_0_3);
    this._text_3 = this.renderer.createText(this._el_0,'\n  ',(null as any));
    this._anchor_4 = this.renderer.createTemplateAnchor(this._el_0,(null as any));
    this._appEl_4 = new import2.AppElement(4,0,this,this._anchor_4);
    this._TemplateRef_4_5 = new import12.TemplateRef_(this._appEl_4,viewFactory_ModalAdapter2);
    this._NgSwitchCase_4_6 = new import11.NgSwitchCase(this._appEl_4.vcRef,this._TemplateRef_4_5,this._NgSwitch_0_3);
    this._text_5 = this.renderer.createText(this._el_0,'\n  ',(null as any));
    this._anchor_6 = this.renderer.createTemplateAnchor(this._el_0,(null as any));
    this._appEl_6 = new import2.AppElement(6,0,this,this._anchor_6);
    this._TemplateRef_6_5 = new import12.TemplateRef_(this._appEl_6,viewFactory_ModalAdapter3);
    this._NgSwitchCase_6_6 = new import11.NgSwitchCase(this._appEl_6.vcRef,this._TemplateRef_6_5,this._NgSwitch_0_3);
    this._text_7 = this.renderer.createText(this._el_0,'\n  ',(null as any));
    this._anchor_8 = this.renderer.createTemplateAnchor(this._el_0,(null as any));
    this._appEl_8 = new import2.AppElement(8,0,this,this._anchor_8);
    this._TemplateRef_8_5 = new import12.TemplateRef_(this._appEl_8,viewFactory_ModalAdapter4);
    this._NgSwitchCase_8_6 = new import11.NgSwitchCase(this._appEl_8.vcRef,this._TemplateRef_8_5,this._NgSwitch_0_3);
    this._text_9 = this.renderer.createText(this._el_0,'\n',(null as any));
    this._expr_0 = import7.UNINITIALIZED;
    this._expr_1 = import7.UNINITIALIZED;
    this._expr_2 = import7.UNINITIALIZED;
    this._expr_3 = import7.UNINITIALIZED;
    this._expr_4 = import7.UNINITIALIZED;
    this.init([],[
      this._el_0,
      this._text_1,
      this._anchor_2,
      this._text_3,
      this._anchor_4,
      this._text_5,
      this._anchor_6,
      this._text_7,
      this._anchor_8,
      this._text_9
    ]
    ,[],[]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import12.TemplateRef) && (2 === requestNodeIndex))) { return this._TemplateRef_2_5; }
    if (((token === import11.NgSwitchCase) && (2 === requestNodeIndex))) { return this._NgSwitchCase_2_6; }
    if (((token === import12.TemplateRef) && (4 === requestNodeIndex))) { return this._TemplateRef_4_5; }
    if (((token === import11.NgSwitchCase) && (4 === requestNodeIndex))) { return this._NgSwitchCase_4_6; }
    if (((token === import12.TemplateRef) && (6 === requestNodeIndex))) { return this._TemplateRef_6_5; }
    if (((token === import11.NgSwitchCase) && (6 === requestNodeIndex))) { return this._NgSwitchCase_6_6; }
    if (((token === import12.TemplateRef) && (8 === requestNodeIndex))) { return this._TemplateRef_8_5; }
    if (((token === import11.NgSwitchCase) && (8 === requestNodeIndex))) { return this._NgSwitchCase_8_6; }
    if (((token === import11.NgSwitch) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 9)))) { return this._NgSwitch_0_3; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_0:any = this.context.modalService.activeModal;
    if (import4.checkBinding(throwOnChange,this._expr_0,currVal_0)) {
      this._NgSwitch_0_3.ngSwitch = currVal_0;
      this._expr_0 = currVal_0;
    }
    const currVal_1:any = this.context.Modal.REGISTRATION;
    if (import4.checkBinding(throwOnChange,this._expr_1,currVal_1)) {
      this._NgSwitchCase_2_6.ngSwitchCase = currVal_1;
      this._expr_1 = currVal_1;
    }
    const currVal_2:any = this.context.Modal.LOGIN;
    if (import4.checkBinding(throwOnChange,this._expr_2,currVal_2)) {
      this._NgSwitchCase_4_6.ngSwitchCase = currVal_2;
      this._expr_2 = currVal_2;
    }
    const currVal_3:any = this.context.Modal.CONFIRM_EMAIL;
    if (import4.checkBinding(throwOnChange,this._expr_3,currVal_3)) {
      this._NgSwitchCase_6_6.ngSwitchCase = currVal_3;
      this._expr_3 = currVal_3;
    }
    const currVal_4:any = this.context.Modal.ADD_NEWS_MODAL;
    if (import4.checkBinding(throwOnChange,this._expr_4,currVal_4)) {
      this._NgSwitchCase_8_6.ngSwitchCase = currVal_4;
      this._expr_4 = currVal_4;
    }
    this.detectContentChildrenChanges(throwOnChange);
    this.detectViewChildrenChanges(throwOnChange);
  }
}
export function viewFactory_ModalAdapter0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<import3.ModalAdapter> {
  if ((renderType_ModalAdapter === (null as any))) { (renderType_ModalAdapter = viewUtils.createRenderComponentType('',0,import9.ViewEncapsulation.None,styles_ModalAdapter,{})); }
  return new _View_ModalAdapter0(viewUtils,parentInjector,declarationEl);
}
class _View_ModalAdapter1 extends import1.AppView<any> {
  _text_0:any;
  _el_1:any;
  /*private*/ _appEl_1:import2.AppElement;
  _RegistrationModal_1_4:import13.RegistrationModal;
  _text_2:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_ModalAdapter1,renderType_ModalAdapter,import6.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._text_0 = this.renderer.createText((null as any),'\n    ',(null as any));
    this._el_1 = this.renderer.createElement((null as any),'registration-modal',(null as any));
    this._appEl_1 = new import2.AppElement(1,(null as any),this,this._el_1);
    var compView_1:any = import14.viewFactory_RegistrationModal0(this.viewUtils,this.injector(1),this._appEl_1);
    this._RegistrationModal_1_4 = new import13.RegistrationModal(this.parent.parentInjector.get(import15.Http),this.parent.parentInjector.get(import8.ModalService),this.parent.parentInjector.get(import16.UserInformationService),this.parent.parentInjector.get(import17.AuthService),this.parent.parentInjector.get(import18.LocalStorageService),this.parent.parentInjector.get(import19.ToastsManager));
    this._appEl_1.initComponent(this._RegistrationModal_1_4,[],compView_1);
    compView_1.create(this._RegistrationModal_1_4,[],(null as any));
    this._text_2 = this.renderer.createText((null as any),'\n  ',(null as any));
    this.init([].concat([
      this._text_0,
      this._el_1,
      this._text_2
    ]
    ),[
      this._text_0,
      this._el_1,
      this._text_2
    ]
    ,[],[]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import13.RegistrationModal) && (1 === requestNodeIndex))) { return this._RegistrationModal_1_4; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    if (((this.numberOfChecks === 0) && !throwOnChange)) { this._RegistrationModal_1_4.ngOnInit(); }
    this.detectContentChildrenChanges(throwOnChange);
    this.detectViewChildrenChanges(throwOnChange);
  }
}
function viewFactory_ModalAdapter1(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  return new _View_ModalAdapter1(viewUtils,parentInjector,declarationEl);
}
class _View_ModalAdapter2 extends import1.AppView<any> {
  _text_0:any;
  _el_1:any;
  /*private*/ _appEl_1:import2.AppElement;
  _LoginModal_1_4:import20.LoginModal;
  _text_2:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_ModalAdapter2,renderType_ModalAdapter,import6.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._text_0 = this.renderer.createText((null as any),'\n    ',(null as any));
    this._el_1 = this.renderer.createElement((null as any),'login-modal',(null as any));
    this._appEl_1 = new import2.AppElement(1,(null as any),this,this._el_1);
    var compView_1:any = import21.viewFactory_LoginModal0(this.viewUtils,this.injector(1),this._appEl_1);
    this._LoginModal_1_4 = new import20.LoginModal(this.parent.parentInjector.get(import15.Http),this.parent.parentInjector.get(import8.ModalService),this.parent.parentInjector.get(import17.AuthService));
    this._appEl_1.initComponent(this._LoginModal_1_4,[],compView_1);
    compView_1.create(this._LoginModal_1_4,[],(null as any));
    this._text_2 = this.renderer.createText((null as any),'\n  ',(null as any));
    this.init([].concat([
      this._text_0,
      this._el_1,
      this._text_2
    ]
    ),[
      this._text_0,
      this._el_1,
      this._text_2
    ]
    ,[],[]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import20.LoginModal) && (1 === requestNodeIndex))) { return this._LoginModal_1_4; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    if (((this.numberOfChecks === 0) && !throwOnChange)) { this._LoginModal_1_4.ngOnInit(); }
    this.detectContentChildrenChanges(throwOnChange);
    this.detectViewChildrenChanges(throwOnChange);
  }
}
function viewFactory_ModalAdapter2(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  return new _View_ModalAdapter2(viewUtils,parentInjector,declarationEl);
}
class _View_ModalAdapter3 extends import1.AppView<any> {
  _text_0:any;
  _el_1:any;
  /*private*/ _appEl_1:import2.AppElement;
  _ConfirmEmailModal_1_4:import22.ConfirmEmailModal;
  _text_2:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_ModalAdapter3,renderType_ModalAdapter,import6.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._text_0 = this.renderer.createText((null as any),'\n    ',(null as any));
    this._el_1 = this.renderer.createElement((null as any),'confirm-email-modal',(null as any));
    this._appEl_1 = new import2.AppElement(1,(null as any),this,this._el_1);
    var compView_1:any = import23.viewFactory_ConfirmEmailModal0(this.viewUtils,this.injector(1),this._appEl_1);
    this._ConfirmEmailModal_1_4 = new import22.ConfirmEmailModal(this.parent.parentInjector.get(import15.Http),this.parent.parentInjector.get(import8.ModalService),this.parent.parentInjector.get(import24.LocalizationService),this.parent.parentInjector.get(import16.UserInformationService));
    this._appEl_1.initComponent(this._ConfirmEmailModal_1_4,[],compView_1);
    compView_1.create(this._ConfirmEmailModal_1_4,[],(null as any));
    this._text_2 = this.renderer.createText((null as any),'\n  ',(null as any));
    this.init([].concat([
      this._text_0,
      this._el_1,
      this._text_2
    ]
    ),[
      this._text_0,
      this._el_1,
      this._text_2
    ]
    ,[],[]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import22.ConfirmEmailModal) && (1 === requestNodeIndex))) { return this._ConfirmEmailModal_1_4; }
    return notFoundResult;
  }
}
function viewFactory_ModalAdapter3(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  return new _View_ModalAdapter3(viewUtils,parentInjector,declarationEl);
}
class _View_ModalAdapter4 extends import1.AppView<any> {
  _text_0:any;
  _el_1:any;
  /*private*/ _appEl_1:import2.AppElement;
  _AddNewsModal_1_4:import25.AddNewsModal;
  _text_2:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_ModalAdapter4,renderType_ModalAdapter,import6.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._text_0 = this.renderer.createText((null as any),'\n    ',(null as any));
    this._el_1 = this.renderer.createElement((null as any),'add-news-modal',(null as any));
    this._appEl_1 = new import2.AppElement(1,(null as any),this,this._el_1);
    var compView_1:any = import26.viewFactory_AddNewsModal0(this.viewUtils,this.injector(1),this._appEl_1);
    this._AddNewsModal_1_4 = new import25.AddNewsModal(this.parent.parentInjector.get(import15.Http),this.parent.parentInjector.get(import8.ModalService),this.parent.parentInjector.get(import24.LocalizationService),this.parent.parentInjector.get(import16.UserInformationService));
    this._appEl_1.initComponent(this._AddNewsModal_1_4,[],compView_1);
    compView_1.create(this._AddNewsModal_1_4,[],(null as any));
    this._text_2 = this.renderer.createText((null as any),'\n  ',(null as any));
    this.init([].concat([
      this._text_0,
      this._el_1,
      this._text_2
    ]
    ),[
      this._text_0,
      this._el_1,
      this._text_2
    ]
    ,[],[]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import25.AddNewsModal) && (1 === requestNodeIndex))) { return this._AddNewsModal_1_4; }
    return notFoundResult;
  }
}
function viewFactory_ModalAdapter4(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  return new _View_ModalAdapter4(viewUtils,parentInjector,declarationEl);
}