/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

import * as import0 from '@angular/core/src/linker/ng_module_factory';
import * as import1 from './PagesModule';
import * as import2 from '@angular/common/src/common_module';
import * as import3 from '@angular/core/src/application_module';
import * as import4 from '@angular/platform-browser/src/browser';
import * as import5 from '@angular/forms/src/directives';
import * as import6 from '@angular/forms/src/form_providers';
import * as import7 from '../../editors/tagInput/TagInputModel';
import * as import8 from '@angular/router/src/router_module';
import * as import9 from '@ng-bootstrap/ng-bootstrap/accordion/accordion.module';
import * as import10 from '@ng-bootstrap/ng-bootstrap/alert/alert.module';
import * as import11 from '@ng-bootstrap/ng-bootstrap/buttons/radio.module';
import * as import12 from '@ng-bootstrap/ng-bootstrap/carousel/carousel.module';
import * as import13 from '@ng-bootstrap/ng-bootstrap/collapse/collapse.module';
import * as import14 from '@ng-bootstrap/ng-bootstrap/datepicker/datepicker.module';
import * as import15 from '@ng-bootstrap/ng-bootstrap/dropdown/dropdown.module';
import * as import16 from '@ng-bootstrap/ng-bootstrap/modal/modal.module';
import * as import17 from '@ng-bootstrap/ng-bootstrap/pagination/pagination.module';
import * as import18 from '@ng-bootstrap/ng-bootstrap/popover/popover.module';
import * as import19 from '@ng-bootstrap/ng-bootstrap/progressbar/progressbar.module';
import * as import20 from '@ng-bootstrap/ng-bootstrap/rating/rating.module';
import * as import21 from '@ng-bootstrap/ng-bootstrap/tabset/tabset.module';
import * as import22 from '@ng-bootstrap/ng-bootstrap/timepicker/timepicker.module';
import * as import23 from '@ng-bootstrap/ng-bootstrap/tooltip/tooltip.module';
import * as import24 from '@ng-bootstrap/ng-bootstrap/typeahead/typeahead.module';
import * as import25 from '@ng-bootstrap/ng-bootstrap/index';
import * as import26 from '@angular/common/src/localization';
import * as import27 from '@angular/core/src/application_init';
import * as import28 from '@angular/core/src/testability/testability';
import * as import29 from '@angular/core/src/application_ref';
import * as import30 from '@angular/core/src/linker/compiler';
import * as import31 from '@angular/platform-browser/src/dom/events/hammer_gestures';
import * as import32 from '@angular/platform-browser/src/dom/events/event_manager';
import * as import33 from '@angular/platform-browser/src/dom/shared_styles_host';
import * as import34 from '@angular/platform-browser/src/dom/dom_renderer';
import * as import35 from '@angular/platform-browser/src/security/dom_sanitization_service';
import * as import36 from '@angular/core/src/linker/view_utils';
import * as import37 from '@angular/platform-browser/src/browser/title';
import * as import38 from '@angular/forms/src/directives/radio_control_value_accessor';
import * as import39 from '@angular/forms/src/form_builder';
import * as import40 from '@ng-bootstrap/ng-bootstrap/modal/modal';
import * as import41 from '@angular/common/src/location/location';
import * as import42 from '@angular/router/src/url_tree';
import * as import43 from '@angular/router/src/router_outlet_map';
import * as import44 from '@angular/core/src/linker/system_js_ng_module_factory_loader';
import * as import45 from '../../services/NewsService';
import * as import46 from '../../services/TeamService';
import * as import47 from '@angular/core/src/di/injector';
import * as import48 from '../../../../node_modules/@ng-bootstrap/ng-bootstrap/alert/alert.ngfactory';
import * as import49 from '../../../../node_modules/@ng-bootstrap/ng-bootstrap/datepicker/datepicker.ngfactory';
import * as import50 from '../../../../node_modules/@ng-bootstrap/ng-bootstrap/modal/modal-backdrop.ngfactory';
import * as import51 from '../../../../node_modules/@ng-bootstrap/ng-bootstrap/modal/modal-window.ngfactory';
import * as import52 from '../../../../node_modules/@ng-bootstrap/ng-bootstrap/popover/popover.ngfactory';
import * as import53 from '../../../../node_modules/@ng-bootstrap/ng-bootstrap/tooltip/tooltip.ngfactory';
import * as import54 from '../../../../node_modules/@ng-bootstrap/ng-bootstrap/typeahead/typeahead-window.ngfactory';
import * as import55 from './news/News.ngfactory';
import * as import56 from './search/Search.ngfactory';
import * as import57 from './singleNews/SingleNews.ngfactory';
import * as import58 from './userSettings/UserSettings.ngfactory';
import * as import59 from './confirmEmail/ConfirmEmail.ngfactory';
import * as import60 from './confirmDataChange/ConfirmDataChange.ngfactory';
import * as import61 from './userNotifications/UserNotifications.ngfactory';
import * as import62 from './user/UserPage.ngfactory';
import * as import63 from '@angular/core/src/application_tokens';
import * as import64 from '@angular/platform-browser/src/dom/events/dom_events';
import * as import65 from '@angular/platform-browser/src/dom/events/key_events';
import * as import66 from '@angular/core/src/zone/ng_zone';
import * as import67 from '@angular/platform-browser/src/dom/debug/ng_probe';
import * as import68 from '@ng-bootstrap/ng-bootstrap/modal/modal-stack';
import * as import69 from '@angular/common/src/location/platform_location';
import * as import70 from '@angular/common/src/location/location_strategy';
import * as import71 from './news/News';
import * as import72 from './search/Search';
import * as import73 from './singleNews/SingleNews';
import * as import74 from './userSettings/UserSettings';
import * as import75 from './confirmEmail/ConfirmEmail';
import * as import76 from './confirmDataChange/ConfirmDataChange';
import * as import77 from './userNotifications/UserNotifications';
import * as import78 from './user/UserPage';
import * as import79 from 'ng2-toastr/src/toast-manager';
import * as import80 from '@angular/http/src/http';
import * as import81 from '../../services/SocketService';
import * as import82 from '../../services/UserInformationService';
import * as import83 from '../../services/LocalizationService';
import * as import84 from '@angular/router/src/router';
import * as import85 from '@angular/core/src/console';
import * as import86 from '@angular/core/src/i18n/tokens';
import * as import87 from '@angular/core/src/error_handler';
import * as import88 from '@angular/platform-browser/src/dom/dom_tokens';
import * as import89 from '@angular/platform-browser/src/dom/animation_driver';
import * as import90 from '@angular/core/src/render/api';
import * as import91 from '@angular/core/src/security';
import * as import92 from '@angular/core/src/change_detection/differs/iterable_differs';
import * as import93 from '@angular/core/src/change_detection/differs/keyvalue_differs';
import * as import94 from '@angular/core/src/linker/ng_module_factory_loader';
import * as import95 from '@angular/router/src/router_config_loader';
import * as import96 from '@angular/router/src/router_state';
class PagesModuleInjector extends import0.NgModuleInjector<import1.PagesModule> {
  _CommonModule_0:import2.CommonModule;
  _ApplicationModule_1:import3.ApplicationModule;
  _BrowserModule_2:import4.BrowserModule;
  _InternalFormsSharedModule_3:import5.InternalFormsSharedModule;
  _FormsModule_4:import6.FormsModule;
  _ReactiveFormsModule_5:import6.ReactiveFormsModule;
  _RlTagInputModule_6:import7.RlTagInputModule;
  _ROUTER_FORROOT_GUARD_7:any;
  _RouterModule_8:import8.RouterModule;
  _NgbAccordionModule_9:import9.NgbAccordionModule;
  _NgbAlertModule_10:import10.NgbAlertModule;
  _NgbButtonsModule_11:import11.NgbButtonsModule;
  _NgbCarouselModule_12:import12.NgbCarouselModule;
  _NgbCollapseModule_13:import13.NgbCollapseModule;
  _NgbDatepickerModule_14:import14.NgbDatepickerModule;
  _NgbDropdownModule_15:import15.NgbDropdownModule;
  _NgbModalModule_16:import16.NgbModalModule;
  _NgbPaginationModule_17:import17.NgbPaginationModule;
  _NgbPopoverModule_18:import18.NgbPopoverModule;
  _NgbProgressbarModule_19:import19.NgbProgressbarModule;
  _NgbRatingModule_20:import20.NgbRatingModule;
  _NgbTabsetModule_21:import21.NgbTabsetModule;
  _NgbTimepickerModule_22:import22.NgbTimepickerModule;
  _NgbTooltipModule_23:import23.NgbTooltipModule;
  _NgbTypeaheadModule_24:import24.NgbTypeaheadModule;
  _NgbModule_25:import25.NgbModule;
  _PagesModule_26:import1.PagesModule;
  __LOCALE_ID_27:any;
  __NgLocalization_28:import26.NgLocaleLocalization;
  _ErrorHandler_29:any;
  _ApplicationInitStatus_30:import27.ApplicationInitStatus;
  _Testability_31:import28.Testability;
  _ApplicationRef__32:import29.ApplicationRef_;
  __ApplicationRef_33:any;
  __Compiler_34:import30.Compiler;
  __APP_ID_35:any;
  __DOCUMENT_36:any;
  __HAMMER_GESTURE_CONFIG_37:import31.HammerGestureConfig;
  __EVENT_MANAGER_PLUGINS_38:any[];
  __EventManager_39:import32.EventManager;
  __DomSharedStylesHost_40:import33.DomSharedStylesHost;
  __AnimationDriver_41:any;
  __DomRootRenderer_42:import34.DomRootRenderer_;
  __RootRenderer_43:any;
  __DomSanitizer_44:import35.DomSanitizerImpl;
  __Sanitizer_45:any;
  __ViewUtils_46:import36.ViewUtils;
  __IterableDiffers_47:any;
  __KeyValueDiffers_48:any;
  __SharedStylesHost_49:any;
  __Title_50:import37.Title;
  __RadioControlRegistry_51:import38.RadioControlRegistry;
  __FormBuilder_52:import39.FormBuilder;
  __NgbModal_53:import40.NgbModal;
  __ROUTER_CONFIGURATION_54:any;
  __LocationStrategy_55:any;
  __Location_56:import41.Location;
  __UrlSerializer_57:import42.DefaultUrlSerializer;
  __RouterOutletMap_58:import43.RouterOutletMap;
  __NgModuleFactoryLoader_59:import44.SystemJsNgModuleLoader;
  __ROUTES_60:any[];
  __Router_61:any;
  __ActivatedRoute_62:any;
  __APP_BOOTSTRAP_LISTENER_63:any[];
  __NewsService_64:import45.NewsService;
  __TeamService_65:import46.TeamService;
  constructor(parent:import47.Injector) {
    super(parent,[
      import48.NgbAlertNgFactory,
      import49.NgbDatepickerNgFactory,
      import50.NgbModalBackdropNgFactory,
      import51.NgbModalWindowNgFactory,
      import52.NgbPopoverWindowNgFactory,
      import53.NgbTooltipWindowNgFactory,
      import54.NgbTypeaheadWindowNgFactory,
      import55.NewsNgFactory,
      import56.SearchNgFactory,
      import57.SingleNewsNgFactory,
      import58.UserSettingsNgFactory,
      import59.ConfirmEmailNgFactory,
      import60.ConfirmDataChangeNgFactory,
      import61.UserNotificationsNgFactory,
      import62.UserPageNgFactory
    ]
    ,[]);
  }
  get _LOCALE_ID_27():any {
    if ((this.__LOCALE_ID_27 == (null as any))) { (this.__LOCALE_ID_27 = 'en-US'); }
    return this.__LOCALE_ID_27;
  }
  get _NgLocalization_28():import26.NgLocaleLocalization {
    if ((this.__NgLocalization_28 == (null as any))) { (this.__NgLocalization_28 = new import26.NgLocaleLocalization(this._LOCALE_ID_27)); }
    return this.__NgLocalization_28;
  }
  get _ApplicationRef_33():any {
    if ((this.__ApplicationRef_33 == (null as any))) { (this.__ApplicationRef_33 = this._ApplicationRef__32); }
    return this.__ApplicationRef_33;
  }
  get _Compiler_34():import30.Compiler {
    if ((this.__Compiler_34 == (null as any))) { (this.__Compiler_34 = new import30.Compiler()); }
    return this.__Compiler_34;
  }
  get _APP_ID_35():any {
    if ((this.__APP_ID_35 == (null as any))) { (this.__APP_ID_35 = import63._appIdRandomProviderFactory()); }
    return this.__APP_ID_35;
  }
  get _DOCUMENT_36():any {
    if ((this.__DOCUMENT_36 == (null as any))) { (this.__DOCUMENT_36 = import4._document()); }
    return this.__DOCUMENT_36;
  }
  get _HAMMER_GESTURE_CONFIG_37():import31.HammerGestureConfig {
    if ((this.__HAMMER_GESTURE_CONFIG_37 == (null as any))) { (this.__HAMMER_GESTURE_CONFIG_37 = new import31.HammerGestureConfig()); }
    return this.__HAMMER_GESTURE_CONFIG_37;
  }
  get _EVENT_MANAGER_PLUGINS_38():any[] {
    if ((this.__EVENT_MANAGER_PLUGINS_38 == (null as any))) { (this.__EVENT_MANAGER_PLUGINS_38 = [
      new import64.DomEventsPlugin(),
      new import65.KeyEventsPlugin(),
      new import31.HammerGesturesPlugin(this._HAMMER_GESTURE_CONFIG_37)
    ]
    ); }
    return this.__EVENT_MANAGER_PLUGINS_38;
  }
  get _EventManager_39():import32.EventManager {
    if ((this.__EventManager_39 == (null as any))) { (this.__EventManager_39 = new import32.EventManager(this._EVENT_MANAGER_PLUGINS_38,this.parent.get(import66.NgZone))); }
    return this.__EventManager_39;
  }
  get _DomSharedStylesHost_40():import33.DomSharedStylesHost {
    if ((this.__DomSharedStylesHost_40 == (null as any))) { (this.__DomSharedStylesHost_40 = new import33.DomSharedStylesHost(this._DOCUMENT_36)); }
    return this.__DomSharedStylesHost_40;
  }
  get _AnimationDriver_41():any {
    if ((this.__AnimationDriver_41 == (null as any))) { (this.__AnimationDriver_41 = import4._resolveDefaultAnimationDriver()); }
    return this.__AnimationDriver_41;
  }
  get _DomRootRenderer_42():import34.DomRootRenderer_ {
    if ((this.__DomRootRenderer_42 == (null as any))) { (this.__DomRootRenderer_42 = new import34.DomRootRenderer_(this._DOCUMENT_36,this._EventManager_39,this._DomSharedStylesHost_40,this._AnimationDriver_41)); }
    return this.__DomRootRenderer_42;
  }
  get _RootRenderer_43():any {
    if ((this.__RootRenderer_43 == (null as any))) { (this.__RootRenderer_43 = import67._createConditionalRootRenderer(this._DomRootRenderer_42,this.parent.get(import67.NgProbeToken,(null as any)))); }
    return this.__RootRenderer_43;
  }
  get _DomSanitizer_44():import35.DomSanitizerImpl {
    if ((this.__DomSanitizer_44 == (null as any))) { (this.__DomSanitizer_44 = new import35.DomSanitizerImpl()); }
    return this.__DomSanitizer_44;
  }
  get _Sanitizer_45():any {
    if ((this.__Sanitizer_45 == (null as any))) { (this.__Sanitizer_45 = this._DomSanitizer_44); }
    return this.__Sanitizer_45;
  }
  get _ViewUtils_46():import36.ViewUtils {
    if ((this.__ViewUtils_46 == (null as any))) { (this.__ViewUtils_46 = new import36.ViewUtils(this._RootRenderer_43,this._APP_ID_35,this._Sanitizer_45)); }
    return this.__ViewUtils_46;
  }
  get _IterableDiffers_47():any {
    if ((this.__IterableDiffers_47 == (null as any))) { (this.__IterableDiffers_47 = import3._iterableDiffersFactory()); }
    return this.__IterableDiffers_47;
  }
  get _KeyValueDiffers_48():any {
    if ((this.__KeyValueDiffers_48 == (null as any))) { (this.__KeyValueDiffers_48 = import3._keyValueDiffersFactory()); }
    return this.__KeyValueDiffers_48;
  }
  get _SharedStylesHost_49():any {
    if ((this.__SharedStylesHost_49 == (null as any))) { (this.__SharedStylesHost_49 = this._DomSharedStylesHost_40); }
    return this.__SharedStylesHost_49;
  }
  get _Title_50():import37.Title {
    if ((this.__Title_50 == (null as any))) { (this.__Title_50 = new import37.Title()); }
    return this.__Title_50;
  }
  get _RadioControlRegistry_51():import38.RadioControlRegistry {
    if ((this.__RadioControlRegistry_51 == (null as any))) { (this.__RadioControlRegistry_51 = new import38.RadioControlRegistry()); }
    return this.__RadioControlRegistry_51;
  }
  get _FormBuilder_52():import39.FormBuilder {
    if ((this.__FormBuilder_52 == (null as any))) { (this.__FormBuilder_52 = new import39.FormBuilder()); }
    return this.__FormBuilder_52;
  }
  get _NgbModal_53():import40.NgbModal {
    if ((this.__NgbModal_53 == (null as any))) { (this.__NgbModal_53 = new import40.NgbModal(this,this,this.parent.get(import68.NgbModalStack))); }
    return this.__NgbModal_53;
  }
  get _ROUTER_CONFIGURATION_54():any {
    if ((this.__ROUTER_CONFIGURATION_54 == (null as any))) { (this.__ROUTER_CONFIGURATION_54 = {}); }
    return this.__ROUTER_CONFIGURATION_54;
  }
  get _LocationStrategy_55():any {
    if ((this.__LocationStrategy_55 == (null as any))) { (this.__LocationStrategy_55 = import8.provideLocationStrategy(this.parent.get(import69.PlatformLocation),this.parent.get(import70.APP_BASE_HREF,(null as any)),this._ROUTER_CONFIGURATION_54)); }
    return this.__LocationStrategy_55;
  }
  get _Location_56():import41.Location {
    if ((this.__Location_56 == (null as any))) { (this.__Location_56 = new import41.Location(this._LocationStrategy_55)); }
    return this.__Location_56;
  }
  get _UrlSerializer_57():import42.DefaultUrlSerializer {
    if ((this.__UrlSerializer_57 == (null as any))) { (this.__UrlSerializer_57 = new import42.DefaultUrlSerializer()); }
    return this.__UrlSerializer_57;
  }
  get _RouterOutletMap_58():import43.RouterOutletMap {
    if ((this.__RouterOutletMap_58 == (null as any))) { (this.__RouterOutletMap_58 = new import43.RouterOutletMap()); }
    return this.__RouterOutletMap_58;
  }
  get _NgModuleFactoryLoader_59():import44.SystemJsNgModuleLoader {
    if ((this.__NgModuleFactoryLoader_59 == (null as any))) { (this.__NgModuleFactoryLoader_59 = new import44.SystemJsNgModuleLoader(this._Compiler_34,this.parent.get(import44.SystemJsNgModuleLoaderConfig,(null as any)))); }
    return this.__NgModuleFactoryLoader_59;
  }
  get _ROUTES_60():any[] {
      if ((this.__ROUTES_60 == (null as any))) { (this.__ROUTES_60 = [[
        {
          path: '',
          component: import71.News,
          useAsDefault: true
        }
        ,
        {
          path: ':id',
          name: 'search',
          component: import72.Search
        }
        ,
        {
          path: 'news/:id',
          component: import73.SingleNews
        }
        ,
        {
          path: 'user/settings',
          component: import74.UserSettings
        }
        ,
        {
          path: 'email-confirm',
          component: import75.ConfirmEmail
        }
        ,
        {
          path: 'data-confirm',
          component: import76.ConfirmDataChange
        }
        ,
        {
          path: 'user/notifications',
          component: import77.UserNotifications
        }
        ,
        {
          path: 'user/:id',
          component: import78.UserPage
        }

      ]
    ]); }
    return this.__ROUTES_60;
  }
  get _Router_61():any {
    if ((this.__Router_61 == (null as any))) { (this.__Router_61 = import8.setupRouter(this._ApplicationRef_33,this._UrlSerializer_57,this._RouterOutletMap_58,this._Location_56,this,this._NgModuleFactoryLoader_59,this._Compiler_34,this._ROUTES_60,this._ROUTER_CONFIGURATION_54)); }
    return this.__Router_61;
  }
  get _ActivatedRoute_62():any {
    if ((this.__ActivatedRoute_62 == (null as any))) { (this.__ActivatedRoute_62 = import8.rootRoute(this._Router_61)); }
    return this.__ActivatedRoute_62;
  }
  get _APP_BOOTSTRAP_LISTENER_63():any[] {
    if ((this.__APP_BOOTSTRAP_LISTENER_63 == (null as any))) { (this.__APP_BOOTSTRAP_LISTENER_63 = [import8.initialRouterNavigation(this._Router_61,this._ROUTER_CONFIGURATION_54)]); }
    return this.__APP_BOOTSTRAP_LISTENER_63;
  }
  get _NewsService_64():import45.NewsService {
    if ((this.__NewsService_64 == (null as any))) { (this.__NewsService_64 = new import45.NewsService(this.parent.get(import79.ToastsManager),this.parent.get(import80.Http),this.parent.get(import81.SocketService))); }
    return this.__NewsService_64;
  }
  get _TeamService_65():import46.TeamService {
    if ((this.__TeamService_65 == (null as any))) { (this.__TeamService_65 = new import46.TeamService(this.parent.get(import80.Http),this.parent.get(import79.ToastsManager),this.parent.get(import82.UserInformationService),this.parent.get(import83.LocalizationService))); }
    return this.__TeamService_65;
  }
  createInternal():import1.PagesModule {
    this._CommonModule_0 = new import2.CommonModule();
    this._ApplicationModule_1 = new import3.ApplicationModule();
    this._BrowserModule_2 = new import4.BrowserModule(this.parent.get(import4.BrowserModule,(null as any)));
    this._InternalFormsSharedModule_3 = new import5.InternalFormsSharedModule();
    this._FormsModule_4 = new import6.FormsModule();
    this._ReactiveFormsModule_5 = new import6.ReactiveFormsModule();
    this._RlTagInputModule_6 = new import7.RlTagInputModule();
    this._ROUTER_FORROOT_GUARD_7 = import8.provideForRootGuard(this.parent.get(import84.Router,(null as any)));
    this._RouterModule_8 = new import8.RouterModule(this._ROUTER_FORROOT_GUARD_7);
    this._NgbAccordionModule_9 = new import9.NgbAccordionModule();
    this._NgbAlertModule_10 = new import10.NgbAlertModule();
    this._NgbButtonsModule_11 = new import11.NgbButtonsModule();
    this._NgbCarouselModule_12 = new import12.NgbCarouselModule();
    this._NgbCollapseModule_13 = new import13.NgbCollapseModule();
    this._NgbDatepickerModule_14 = new import14.NgbDatepickerModule();
    this._NgbDropdownModule_15 = new import15.NgbDropdownModule();
    this._NgbModalModule_16 = new import16.NgbModalModule();
    this._NgbPaginationModule_17 = new import17.NgbPaginationModule();
    this._NgbPopoverModule_18 = new import18.NgbPopoverModule();
    this._NgbProgressbarModule_19 = new import19.NgbProgressbarModule();
    this._NgbRatingModule_20 = new import20.NgbRatingModule();
    this._NgbTabsetModule_21 = new import21.NgbTabsetModule();
    this._NgbTimepickerModule_22 = new import22.NgbTimepickerModule();
    this._NgbTooltipModule_23 = new import23.NgbTooltipModule();
    this._NgbTypeaheadModule_24 = new import24.NgbTypeaheadModule();
    this._NgbModule_25 = new import25.NgbModule();
    this._PagesModule_26 = new import1.PagesModule();
    this._ErrorHandler_29 = import4.errorHandler();
    this._ApplicationInitStatus_30 = new import27.ApplicationInitStatus(this.parent.get(import27.APP_INITIALIZER,(null as any)));
    this._Testability_31 = new import28.Testability(this.parent.get(import66.NgZone));
    this._ApplicationRef__32 = new import29.ApplicationRef_(this.parent.get(import66.NgZone),this.parent.get(import85.Console),this,this._ErrorHandler_29,this,this._ApplicationInitStatus_30,this.parent.get(import28.TestabilityRegistry,(null as any)),this._Testability_31);
    return this._PagesModule_26;
  }
  getInternal(token:any,notFoundResult:any):any {
    if ((token === import2.CommonModule)) { return this._CommonModule_0; }
    if ((token === import3.ApplicationModule)) { return this._ApplicationModule_1; }
    if ((token === import4.BrowserModule)) { return this._BrowserModule_2; }
    if ((token === import5.InternalFormsSharedModule)) { return this._InternalFormsSharedModule_3; }
    if ((token === import6.FormsModule)) { return this._FormsModule_4; }
    if ((token === import6.ReactiveFormsModule)) { return this._ReactiveFormsModule_5; }
    if ((token === import7.RlTagInputModule)) { return this._RlTagInputModule_6; }
    if ((token === import8.ROUTER_FORROOT_GUARD)) { return this._ROUTER_FORROOT_GUARD_7; }
    if ((token === import8.RouterModule)) { return this._RouterModule_8; }
    if ((token === import9.NgbAccordionModule)) { return this._NgbAccordionModule_9; }
    if ((token === import10.NgbAlertModule)) { return this._NgbAlertModule_10; }
    if ((token === import11.NgbButtonsModule)) { return this._NgbButtonsModule_11; }
    if ((token === import12.NgbCarouselModule)) { return this._NgbCarouselModule_12; }
    if ((token === import13.NgbCollapseModule)) { return this._NgbCollapseModule_13; }
    if ((token === import14.NgbDatepickerModule)) { return this._NgbDatepickerModule_14; }
    if ((token === import15.NgbDropdownModule)) { return this._NgbDropdownModule_15; }
    if ((token === import16.NgbModalModule)) { return this._NgbModalModule_16; }
    if ((token === import17.NgbPaginationModule)) { return this._NgbPaginationModule_17; }
    if ((token === import18.NgbPopoverModule)) { return this._NgbPopoverModule_18; }
    if ((token === import19.NgbProgressbarModule)) { return this._NgbProgressbarModule_19; }
    if ((token === import20.NgbRatingModule)) { return this._NgbRatingModule_20; }
    if ((token === import21.NgbTabsetModule)) { return this._NgbTabsetModule_21; }
    if ((token === import22.NgbTimepickerModule)) { return this._NgbTimepickerModule_22; }
    if ((token === import23.NgbTooltipModule)) { return this._NgbTooltipModule_23; }
    if ((token === import24.NgbTypeaheadModule)) { return this._NgbTypeaheadModule_24; }
    if ((token === import25.NgbModule)) { return this._NgbModule_25; }
    if ((token === import1.PagesModule)) { return this._PagesModule_26; }
    if ((token === import86.LOCALE_ID)) { return this._LOCALE_ID_27; }
    if ((token === import26.NgLocalization)) { return this._NgLocalization_28; }
    if ((token === import87.ErrorHandler)) { return this._ErrorHandler_29; }
    if ((token === import27.ApplicationInitStatus)) { return this._ApplicationInitStatus_30; }
    if ((token === import28.Testability)) { return this._Testability_31; }
    if ((token === import29.ApplicationRef_)) { return this._ApplicationRef__32; }
    if ((token === import29.ApplicationRef)) { return this._ApplicationRef_33; }
    if ((token === import30.Compiler)) { return this._Compiler_34; }
    if ((token === import63.APP_ID)) { return this._APP_ID_35; }
    if ((token === import88.DOCUMENT)) { return this._DOCUMENT_36; }
    if ((token === import31.HAMMER_GESTURE_CONFIG)) { return this._HAMMER_GESTURE_CONFIG_37; }
    if ((token === import32.EVENT_MANAGER_PLUGINS)) { return this._EVENT_MANAGER_PLUGINS_38; }
    if ((token === import32.EventManager)) { return this._EventManager_39; }
    if ((token === import33.DomSharedStylesHost)) { return this._DomSharedStylesHost_40; }
    if ((token === import89.AnimationDriver)) { return this._AnimationDriver_41; }
    if ((token === import34.DomRootRenderer)) { return this._DomRootRenderer_42; }
    if ((token === import90.RootRenderer)) { return this._RootRenderer_43; }
    if ((token === import35.DomSanitizer)) { return this._DomSanitizer_44; }
    if ((token === import91.Sanitizer)) { return this._Sanitizer_45; }
    if ((token === import36.ViewUtils)) { return this._ViewUtils_46; }
    if ((token === import92.IterableDiffers)) { return this._IterableDiffers_47; }
    if ((token === import93.KeyValueDiffers)) { return this._KeyValueDiffers_48; }
    if ((token === import33.SharedStylesHost)) { return this._SharedStylesHost_49; }
    if ((token === import37.Title)) { return this._Title_50; }
    if ((token === import38.RadioControlRegistry)) { return this._RadioControlRegistry_51; }
    if ((token === import39.FormBuilder)) { return this._FormBuilder_52; }
    if ((token === import40.NgbModal)) { return this._NgbModal_53; }
    if ((token === import8.ROUTER_CONFIGURATION)) { return this._ROUTER_CONFIGURATION_54; }
    if ((token === import70.LocationStrategy)) { return this._LocationStrategy_55; }
    if ((token === import41.Location)) { return this._Location_56; }
    if ((token === import42.UrlSerializer)) { return this._UrlSerializer_57; }
    if ((token === import43.RouterOutletMap)) { return this._RouterOutletMap_58; }
    if ((token === import94.NgModuleFactoryLoader)) { return this._NgModuleFactoryLoader_59; }
    if ((token === import95.ROUTES)) { return this._ROUTES_60; }
    if ((token === import84.Router)) { return this._Router_61; }
    if ((token === import96.ActivatedRoute)) { return this._ActivatedRoute_62; }
    if ((token === import63.APP_BOOTSTRAP_LISTENER)) { return this._APP_BOOTSTRAP_LISTENER_63; }
    if ((token === import45.NewsService)) { return this._NewsService_64; }
    if ((token === import46.TeamService)) { return this._TeamService_65; }
    return notFoundResult;
  }
  destroyInternal():void {
    this._ApplicationRef__32.ngOnDestroy();
  }
}
export const PagesModuleNgFactory:import0.NgModuleFactory<import1.PagesModule> = new import0.NgModuleFactory(PagesModuleInjector,import1.PagesModule);