/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

import * as import0 from '@angular/core/src/render/api';
import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/linker/element';
import * as import3 from './Pages';
import * as import4 from '@angular/core/src/linker/view_utils';
import * as import5 from '@angular/core/src/di/injector';
import * as import6 from '@angular/core/src/linker/view_type';
import * as import7 from '@angular/core/src/change_detection/change_detection';
import * as import8 from '@angular/core/src/metadata/view';
import * as import9 from '@angular/core/src/linker/component_factory';
import * as import10 from '@angular/router/src/directives/router_outlet';
import * as import11 from '@angular/router/src/router_outlet_map';
import * as import12 from '@angular/core/src/linker/component_factory_resolver';
var renderType_Pages_Host:import0.RenderComponentType = (null as any);
class _View_Pages_Host0 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import2.AppElement;
  _Pages_0_4:import3.Pages;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_Pages_Host0,renderType_Pages_Host,import6.ViewType.HOST,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.selectOrCreateHostElement('pages',rootSelector,(null as any));
    this._appEl_0 = new import2.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = viewFactory_Pages0(this.viewUtils,this.injector(0),this._appEl_0);
    this._Pages_0_4 = new import3.Pages();
    this._appEl_0.initComponent(this._Pages_0_4,[],compView_0);
    compView_0.create(this._Pages_0_4,this.projectableNodes,(null as any));
    this.init([].concat([this._el_0]),[this._el_0],[],[]);
    return this._appEl_0;
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import3.Pages) && (0 === requestNodeIndex))) { return this._Pages_0_4; }
    return notFoundResult;
  }
}
function viewFactory_Pages_Host0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  if ((renderType_Pages_Host === (null as any))) { (renderType_Pages_Host = viewUtils.createRenderComponentType('',0,import8.ViewEncapsulation.None,[],{})); }
  return new _View_Pages_Host0(viewUtils,parentInjector,declarationEl);
}
export const PagesNgFactory:import9.ComponentFactory<import3.Pages> = new import9.ComponentFactory<import3.Pages>('pages',viewFactory_Pages_Host0,import3.Pages);
const styles_Pages:any[] = [];
var renderType_Pages:import0.RenderComponentType = (null as any);
class _View_Pages0 extends import1.AppView<import3.Pages> {
  _el_0:any;
  /*private*/ _appEl_0:import2.AppElement;
  _RouterOutlet_0_5:import10.RouterOutlet;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_Pages0,renderType_Pages,import6.ViewType.COMPONENT,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    const parentRenderNode:any = this.renderer.createViewRoot(this.declarationAppElement.nativeElement);
    this._el_0 = this.renderer.createElement(parentRenderNode,'router-outlet',(null as any));
    this._appEl_0 = new import2.AppElement(0,(null as any),this,this._el_0);
    this._RouterOutlet_0_5 = new import10.RouterOutlet(this.parentInjector.get(import11.RouterOutletMap),this._appEl_0.vcRef,this.parentInjector.get(import12.ComponentFactoryResolver),(null as any));
    this.init([],[this._el_0],[],[]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import10.RouterOutlet) && (0 === requestNodeIndex))) { return this._RouterOutlet_0_5; }
    return notFoundResult;
  }
  destroyInternal():void {
    this._RouterOutlet_0_5.ngOnDestroy();
  }
}
export function viewFactory_Pages0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<import3.Pages> {
  if ((renderType_Pages === (null as any))) { (renderType_Pages = viewUtils.createRenderComponentType('',0,import8.ViewEncapsulation.None,styles_Pages,{})); }
  return new _View_Pages0(viewUtils,parentInjector,declarationEl);
}