/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

import * as import0 from '@angular/core/src/render/api';
import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/linker/element';
import * as import3 from './AddNews';
import * as import4 from '@angular/core/src/linker/view_utils';
import * as import5 from '@angular/core/src/di/injector';
import * as import6 from '@angular/core/src/linker/view_type';
import * as import7 from '@angular/core/src/change_detection/change_detection';
import * as import8 from '../../../../services/NewsService';
import * as import9 from '../../../../services/LocalizationService';
import * as import10 from '../../../../services/AuthService';
import * as import11 from '../../../../services/UserInformationService';
import * as import12 from '../../../../services/ModalService';
import * as import13 from '@angular/core/src/metadata/view';
import * as import14 from '@angular/core/src/linker/component_factory';
import * as import15 from '@angular/common/src/directives/ng_if';
import * as import16 from '@angular/core/src/linker/template_ref';
import * as import17 from '@angular/forms/src/directives/ng_form';
import * as import18 from '@angular/forms/src/directives/ng_control_status';
import * as import19 from '@angular/forms/src/directives/default_value_accessor';
import * as import20 from '@angular/forms/src/directives/ng_model';
import * as import21 from '../../../../editors/tagInput/components/tag-input/TagInput';
import * as import22 from '@angular/core/src/linker/element_ref';
import * as import23 from '../../../../editors/tagInput/components/tag-input/TagInput.ngfactory';
import * as import24 from '@angular/forms/src/form_builder';
import * as import25 from '@angular/forms/src/directives/control_value_accessor';
import * as import26 from '@angular/forms/src/directives/ng_control';
import * as import27 from '@angular/forms/src/directives/control_container';
var renderType_AddNews_Host:import0.RenderComponentType = (null as any);
class _View_AddNews_Host0 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import2.AppElement;
  _AddNews_0_4:import3.AddNews;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_AddNews_Host0,renderType_AddNews_Host,import6.ViewType.HOST,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.selectOrCreateHostElement('add-news',rootSelector,(null as any));
    this._appEl_0 = new import2.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = viewFactory_AddNews0(this.viewUtils,this.injector(0),this._appEl_0);
    this._AddNews_0_4 = new import3.AddNews(this.parentInjector.get(import8.NewsService),this.parentInjector.get(import9.LocalizationService),this.parentInjector.get(import10.AuthService),this.parentInjector.get(import11.UserInformationService),this.parentInjector.get(import12.ModalService));
    this._appEl_0.initComponent(this._AddNews_0_4,[],compView_0);
    compView_0.create(this._AddNews_0_4,this.projectableNodes,(null as any));
    this.init([].concat([this._el_0]),[this._el_0],[],[]);
    return this._appEl_0;
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import3.AddNews) && (0 === requestNodeIndex))) { return this._AddNews_0_4; }
    return notFoundResult;
  }
}
function viewFactory_AddNews_Host0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  if ((renderType_AddNews_Host === (null as any))) { (renderType_AddNews_Host = viewUtils.createRenderComponentType('',0,import13.ViewEncapsulation.None,[],{})); }
  return new _View_AddNews_Host0(viewUtils,parentInjector,declarationEl);
}
export const AddNewsNgFactory:import14.ComponentFactory<import3.AddNews> = new import14.ComponentFactory<import3.AddNews>('add-news',viewFactory_AddNews_Host0,import3.AddNews);
const styles_AddNews:any[] = [];
var renderType_AddNews:import0.RenderComponentType = (null as any);
class _View_AddNews0 extends import1.AppView<import3.AddNews> {
  _anchor_0:any;
  /*private*/ _appEl_0:import2.AppElement;
  _TemplateRef_0_5:any;
  _NgIf_0_6:import15.NgIf;
  /*private*/ _expr_0:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_AddNews0,renderType_AddNews,import6.ViewType.COMPONENT,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    const parentRenderNode:any = this.renderer.createViewRoot(this.declarationAppElement.nativeElement);
    this._anchor_0 = this.renderer.createTemplateAnchor(parentRenderNode,(null as any));
    this._appEl_0 = new import2.AppElement(0,(null as any),this,this._anchor_0);
    this._TemplateRef_0_5 = new import16.TemplateRef_(this._appEl_0,viewFactory_AddNews1);
    this._NgIf_0_6 = new import15.NgIf(this._appEl_0.vcRef,this._TemplateRef_0_5);
    this._expr_0 = import7.UNINITIALIZED;
    this.init([],[this._anchor_0],[],[]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import16.TemplateRef) && (0 === requestNodeIndex))) { return this._TemplateRef_0_5; }
    if (((token === import15.NgIf) && (0 === requestNodeIndex))) { return this._NgIf_0_6; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_0:any = this.context.authService.isAuth;
    if (import4.checkBinding(throwOnChange,this._expr_0,currVal_0)) {
      this._NgIf_0_6.ngIf = currVal_0;
      this._expr_0 = currVal_0;
    }
    this.detectContentChildrenChanges(throwOnChange);
    this.detectViewChildrenChanges(throwOnChange);
  }
}
export function viewFactory_AddNews0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<import3.AddNews> {
  if ((renderType_AddNews === (null as any))) { (renderType_AddNews = viewUtils.createRenderComponentType('',0,import13.ViewEncapsulation.None,styles_AddNews,{})); }
  return new _View_AddNews0(viewUtils,parentInjector,declarationEl);
}
class _View_AddNews1 extends import1.AppView<any> {
  _el_0:any;
  _text_1:any;
  _el_2:any;
  _text_3:any;
  _text_4:any;
  _el_5:any;
  _text_6:any;
  _el_7:any;
  _text_8:any;
  _el_9:any;
  _text_10:any;
  _el_11:any;
  _NgForm_11_3:import17.NgForm;
  _ControlContainer_11_4:any;
  _NgControlStatusGroup_11_5:import18.NgControlStatusGroup;
  _text_12:any;
  _el_13:any;
  _DefaultValueAccessor_13_3:import19.DefaultValueAccessor;
  _NG_VALUE_ACCESSOR_13_4:any[];
  _NgModel_13_5:import20.NgModel;
  _NgControl_13_6:any;
  _NgControlStatus_13_7:import18.NgControlStatus;
  _text_14:any;
  _el_15:any;
  _text_16:any;
  _el_17:any;
  _text_18:any;
  _el_19:any;
  _text_20:any;
  _el_21:any;
  _text_22:any;
  _el_23:any;
  _text_24:any;
  _el_25:any;
  _text_26:any;
  _el_27:any;
  _text_28:any;
  _el_29:any;
  _text_30:any;
  _text_31:any;
  _text_32:any;
  _text_33:any;
  _el_34:any;
  /*private*/ _appEl_34:import2.AppElement;
  _TagInputComponent_34_4:import21.TagInputComponent;
  _NG_VALUE_ACCESSOR_34_5:any[];
  _NgModel_34_6:import20.NgModel;
  _NgControl_34_7:any;
  _NgControlStatus_34_8:import18.NgControlStatus;
  _text_35:any;
  _text_36:any;
  _text_37:any;
  _text_38:any;
  /*private*/ _expr_0:any;
  /*private*/ _expr_4:any;
  /*private*/ _expr_5:any;
  /*private*/ _expr_6:any;
  /*private*/ _expr_7:any;
  /*private*/ _expr_8:any;
  /*private*/ _expr_9:any;
  /*private*/ _expr_12:any;
  /*private*/ _expr_13:any;
  /*private*/ _expr_14:any;
  /*private*/ _expr_15:any;
  /*private*/ _expr_16:any;
  /*private*/ _expr_17:any;
  /*private*/ _expr_18:any;
  /*private*/ _expr_19:any;
  /*private*/ _expr_23:any;
  /*private*/ _expr_24:any;
  /*private*/ _expr_25:any;
  /*private*/ _expr_26:any;
  /*private*/ _expr_27:any;
  /*private*/ _expr_28:any;
  /*private*/ _expr_29:any;
  /*private*/ _expr_30:any;
  /*private*/ _expr_31:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_AddNews1,renderType_AddNews,import6.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'div',(null as any));
    this.renderer.setElementAttribute(this._el_0,'class','col-md-12 news-add news-add-publication');
    this._text_1 = this.renderer.createText(this._el_0,'\n  ',(null as any));
    this._el_2 = this.renderer.createElement(this._el_0,'h2',(null as any));
    this.renderer.setElementAttribute(this._el_2,'class','');
    this._text_3 = this.renderer.createText(this._el_2,'',(null as any));
    this._text_4 = this.renderer.createText(this._el_0,'\n\n  ',(null as any));
    this._el_5 = this.renderer.createElement(this._el_0,'div',(null as any));
    this.renderer.setElementAttribute(this._el_5,'class','submit_news_box clear_fix');
    this._text_6 = this.renderer.createText(this._el_5,'\n    ',(null as any));
    this._el_7 = this.renderer.createElement(this._el_5,'div',(null as any));
    this.renderer.setElementAttribute(this._el_7,'class','error');
    this.renderer.setElementAttribute(this._el_7,'id','submit_news_error');
    this._text_8 = this.renderer.createText(this._el_5,'\n\n    ',(null as any));
    this._el_9 = this.renderer.createElement(this._el_5,'div',(null as any));
    this.renderer.setElementAttribute(this._el_9,'class','news_input');
    this._text_10 = this.renderer.createText(this._el_9,'\n      ',(null as any));
    this._el_11 = this.renderer.createElement(this._el_9,'form',(null as any));
    this._NgForm_11_3 = new import17.NgForm((null as any),(null as any));
    this._ControlContainer_11_4 = this._NgForm_11_3;
    this._NgControlStatusGroup_11_5 = new import18.NgControlStatusGroup(this._ControlContainer_11_4);
    this._text_12 = this.renderer.createText(this._el_11,'\n        ',(null as any));
    this._el_13 = this.renderer.createElement(this._el_11,'input',(null as any));
    this.renderer.setElementAttribute(this._el_13,'class','news_content');
    this.renderer.setElementAttribute(this._el_13,'name','content');
    this.renderer.setElementAttribute(this._el_13,'ngModel','');
    this.renderer.setElementAttribute(this._el_13,'placeholder','Что расскажете?');
    this.renderer.setElementAttribute(this._el_13,'type','text');
    this._DefaultValueAccessor_13_3 = new import19.DefaultValueAccessor(this.renderer,new import22.ElementRef(this._el_13));
    this._NG_VALUE_ACCESSOR_13_4 = [this._DefaultValueAccessor_13_3];
    this._NgModel_13_5 = new import20.NgModel(this._ControlContainer_11_4,(null as any),(null as any),this._NG_VALUE_ACCESSOR_13_4);
    this._NgControl_13_6 = this._NgModel_13_5;
    this._NgControlStatus_13_7 = new import18.NgControlStatus(this._NgControl_13_6);
    this._text_14 = this.renderer.createText(this._el_11,'\n        ',(null as any));
    this._el_15 = this.renderer.createElement(this._el_11,'button',(null as any));
    this.renderer.setElementAttribute(this._el_15,'style','position: absolute; left: -9999px');
    this.renderer.setElementAttribute(this._el_15,'type','submit');
    this._text_16 = this.renderer.createText(this._el_11,'\n        ',(null as any));
    this._el_17 = this.renderer.createElement(this._el_11,'div',(null as any));
    this.renderer.setElementAttribute(this._el_17,'class','news_add_media');
    this._text_18 = this.renderer.createText(this._el_17,'\n          ',(null as any));
    this._el_19 = this.renderer.createElement(this._el_17,'div',(null as any));
    this.renderer.setElementAttribute(this._el_19,'class','media_selector clear_fix');
    this._text_20 = this.renderer.createText(this._el_19,'\n            ',(null as any));
    this._el_21 = this.renderer.createElement(this._el_19,'button',(null as any));
    this.renderer.setElementAttribute(this._el_21,'aria-label','Фотография');
    this.renderer.setElementAttribute(this._el_21,'class','ms_item ms_item_photo');
    this.renderer.setElementAttribute(this._el_21,'data-title','Фотография');
    this.renderer.setElementAttribute(this._el_21,'role','link');
    this.renderer.setElementAttribute(this._el_21,'tabindex','0');
    this._text_22 = this.renderer.createText(this._el_19,'\n            ',(null as any));
    this._el_23 = this.renderer.createElement(this._el_19,'button',(null as any));
    this.renderer.setElementAttribute(this._el_23,'aria-label','Видеозапись');
    this.renderer.setElementAttribute(this._el_23,'class','ms_item ms_item_video');
    this.renderer.setElementAttribute(this._el_23,'data-title','Видеозапись');
    this.renderer.setElementAttribute(this._el_23,'role','link');
    this.renderer.setElementAttribute(this._el_23,'tabindex','0');
    this._text_24 = this.renderer.createText(this._el_19,'\n            ',(null as any));
    this._el_25 = this.renderer.createElement(this._el_19,'button',(null as any));
    this.renderer.setElementAttribute(this._el_25,'aria-label','Аудиозапись');
    this.renderer.setElementAttribute(this._el_25,'class','ms_item ms_item_audio');
    this.renderer.setElementAttribute(this._el_25,'data-title','Аудиозапись');
    this.renderer.setElementAttribute(this._el_25,'role','link');
    this.renderer.setElementAttribute(this._el_25,'tabindex','0');
    this._text_26 = this.renderer.createText(this._el_19,'\n            ',(null as any));
    this._el_27 = this.renderer.createElement(this._el_19,'button',(null as any));
    this.renderer.setElementAttribute(this._el_27,'aria-label','Редактировать');
    this.renderer.setElementAttribute(this._el_27,'class','ms_item ms_item_edit');
    this.renderer.setElementAttribute(this._el_27,'data-title','Редактировать');
    this.renderer.setElementAttribute(this._el_27,'role','link');
    this.renderer.setElementAttribute(this._el_27,'tabindex','0');
    this._text_28 = this.renderer.createText(this._el_19,'\n            ',(null as any));
    this._el_29 = this.renderer.createElement(this._el_19,'button',(null as any));
    this.renderer.setElementAttribute(this._el_29,'aria-label','Другое');
    this.renderer.setElementAttribute(this._el_29,'class','ms_item ms_item_shape');
    this.renderer.setElementAttribute(this._el_29,'data-title','Другое');
    this.renderer.setElementAttribute(this._el_29,'role','link');
    this.renderer.setElementAttribute(this._el_29,'tabindex','0');
    this._text_30 = this.renderer.createText(this._el_19,'\n          ',(null as any));
    this._text_31 = this.renderer.createText(this._el_17,'\n        ',(null as any));
    this._text_32 = this.renderer.createText(this._el_11,'\n      ',(null as any));
    this._text_33 = this.renderer.createText(this._el_9,'\n      ',(null as any));
    this._el_34 = this.renderer.createElement(this._el_9,'rl-tag-input',(null as any));
    this.renderer.setElementAttribute(this._el_34,'placeholder','Теги');
    this._appEl_34 = new import2.AppElement(34,9,this,this._el_34);
    var compView_34:any = import23.viewFactory_TagInputComponent0(this.viewUtils,this.injector(34),this._appEl_34);
    this._TagInputComponent_34_4 = new import21.TagInputComponent(this.parentInjector.get(import24.FormBuilder),new import22.ElementRef(this._el_34));
    this._NG_VALUE_ACCESSOR_34_5 = [this._TagInputComponent_34_4];
    this._NgModel_34_6 = new import20.NgModel((null as any),(null as any),(null as any),this._NG_VALUE_ACCESSOR_34_5);
    this._NgControl_34_7 = this._NgModel_34_6;
    this._NgControlStatus_34_8 = new import18.NgControlStatus(this._NgControl_34_7);
    this._appEl_34.initComponent(this._TagInputComponent_34_4,[],compView_34);
    this._text_35 = this.renderer.createText((null as any),'\n      ',(null as any));
    compView_34.create(this._TagInputComponent_34_4,[],(null as any));
    this._text_36 = this.renderer.createText(this._el_9,'\n\n    ',(null as any));
    this._text_37 = this.renderer.createText(this._el_5,'\n  ',(null as any));
    this._text_38 = this.renderer.createText(this._el_0,'\n\n',(null as any));
    this._expr_0 = import7.UNINITIALIZED;
    var disposable_0:Function = this.renderer.listen(this._el_11,'ngSubmit',this.eventHandler(this._handle_ngSubmit_11_0.bind(this)));
    var disposable_1:Function = this.renderer.listen(this._el_11,'submit',this.eventHandler(this._handle_submit_11_1.bind(this)));
    var disposable_2:Function = this.renderer.listen(this._el_11,'reset',this.eventHandler(this._handle_reset_11_2.bind(this)));
    const subscription_0:any = this._NgForm_11_3.ngSubmit.subscribe(this.eventHandler(this._handle_ngSubmit_11_0.bind(this)));
    this._expr_4 = import7.UNINITIALIZED;
    this._expr_5 = import7.UNINITIALIZED;
    this._expr_6 = import7.UNINITIALIZED;
    this._expr_7 = import7.UNINITIALIZED;
    this._expr_8 = import7.UNINITIALIZED;
    this._expr_9 = import7.UNINITIALIZED;
    var disposable_3:Function = this.renderer.listen(this._el_13,'input',this.eventHandler(this._handle_input_13_0.bind(this)));
    var disposable_4:Function = this.renderer.listen(this._el_13,'blur',this.eventHandler(this._handle_blur_13_1.bind(this)));
    this._expr_12 = import7.UNINITIALIZED;
    this._expr_13 = import7.UNINITIALIZED;
    this._expr_14 = import7.UNINITIALIZED;
    this._expr_15 = import7.UNINITIALIZED;
    this._expr_16 = import7.UNINITIALIZED;
    this._expr_17 = import7.UNINITIALIZED;
    this._expr_18 = import7.UNINITIALIZED;
    this._expr_19 = import7.UNINITIALIZED;
    var disposable_5:Function = this.renderer.listen(this._el_27,'click',this.eventHandler(this._handle_click_27_0.bind(this)));
    var disposable_6:Function = this.renderer.listen(this._el_34,'ngModelChange',this.eventHandler(this._handle_ngModelChange_34_0.bind(this)));
    var disposable_7:Function = this.renderer.listenGlobal('document','click',this.eventHandler(this._handle_click_34_1.bind(this)));
    this._expr_23 = import7.UNINITIALIZED;
    this._expr_24 = import7.UNINITIALIZED;
    this._expr_25 = import7.UNINITIALIZED;
    const subscription_1:any = this._NgModel_34_6.update.subscribe(this.eventHandler(this._handle_ngModelChange_34_0.bind(this)));
    this._expr_26 = import7.UNINITIALIZED;
    this._expr_27 = import7.UNINITIALIZED;
    this._expr_28 = import7.UNINITIALIZED;
    this._expr_29 = import7.UNINITIALIZED;
    this._expr_30 = import7.UNINITIALIZED;
    this._expr_31 = import7.UNINITIALIZED;
    this.init([].concat([this._el_0]),[
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._text_4,
      this._el_5,
      this._text_6,
      this._el_7,
      this._text_8,
      this._el_9,
      this._text_10,
      this._el_11,
      this._text_12,
      this._el_13,
      this._text_14,
      this._el_15,
      this._text_16,
      this._el_17,
      this._text_18,
      this._el_19,
      this._text_20,
      this._el_21,
      this._text_22,
      this._el_23,
      this._text_24,
      this._el_25,
      this._text_26,
      this._el_27,
      this._text_28,
      this._el_29,
      this._text_30,
      this._text_31,
      this._text_32,
      this._text_33,
      this._el_34,
      this._text_35,
      this._text_36,
      this._text_37,
      this._text_38
    ]
    ,[
      disposable_0,
      disposable_1,
      disposable_2,
      disposable_3,
      disposable_4,
      disposable_5,
      disposable_6,
      disposable_7
    ]
    ,[
      subscription_0,
      subscription_1
    ]
    );
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import19.DefaultValueAccessor) && (13 === requestNodeIndex))) { return this._DefaultValueAccessor_13_3; }
    if (((token === import25.NG_VALUE_ACCESSOR) && (13 === requestNodeIndex))) { return this._NG_VALUE_ACCESSOR_13_4; }
    if (((token === import20.NgModel) && (13 === requestNodeIndex))) { return this._NgModel_13_5; }
    if (((token === import26.NgControl) && (13 === requestNodeIndex))) { return this._NgControl_13_6; }
    if (((token === import18.NgControlStatus) && (13 === requestNodeIndex))) { return this._NgControlStatus_13_7; }
    if (((token === import17.NgForm) && ((11 <= requestNodeIndex) && (requestNodeIndex <= 32)))) { return this._NgForm_11_3; }
    if (((token === import27.ControlContainer) && ((11 <= requestNodeIndex) && (requestNodeIndex <= 32)))) { return this._ControlContainer_11_4; }
    if (((token === import18.NgControlStatusGroup) && ((11 <= requestNodeIndex) && (requestNodeIndex <= 32)))) { return this._NgControlStatusGroup_11_5; }
    if (((token === import21.TagInputComponent) && ((34 <= requestNodeIndex) && (requestNodeIndex <= 35)))) { return this._TagInputComponent_34_4; }
    if (((token === import25.NG_VALUE_ACCESSOR) && ((34 <= requestNodeIndex) && (requestNodeIndex <= 35)))) { return this._NG_VALUE_ACCESSOR_34_5; }
    if (((token === import20.NgModel) && ((34 <= requestNodeIndex) && (requestNodeIndex <= 35)))) { return this._NgModel_34_6; }
    if (((token === import26.NgControl) && ((34 <= requestNodeIndex) && (requestNodeIndex <= 35)))) { return this._NgControl_34_7; }
    if (((token === import18.NgControlStatus) && ((34 <= requestNodeIndex) && (requestNodeIndex <= 35)))) { return this._NgControlStatus_34_8; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    var changes:{[key: string]:import7.SimpleChange} = (null as any);
    changes = (null as any);
    const currVal_12:any = 'content';
    if (import4.checkBinding(throwOnChange,this._expr_12,currVal_12)) {
      this._NgModel_13_5.name = currVal_12;
      if ((changes === (null as any))) { (changes = {}); }
      changes['name'] = new import7.SimpleChange(this._expr_12,currVal_12);
      this._expr_12 = currVal_12;
    }
    const currVal_13:any = '';
    if (import4.checkBinding(throwOnChange,this._expr_13,currVal_13)) {
      this._NgModel_13_5.model = currVal_13;
      if ((changes === (null as any))) { (changes = {}); }
      changes['model'] = new import7.SimpleChange(this._expr_13,currVal_13);
      this._expr_13 = currVal_13;
    }
    if ((changes !== (null as any))) { this._NgModel_13_5.ngOnChanges(changes); }
    const currVal_23:any = 'Теги';
    if (import4.checkBinding(throwOnChange,this._expr_23,currVal_23)) {
      this._TagInputComponent_34_4.placeholder = currVal_23;
      this._expr_23 = currVal_23;
    }
    if (((this.numberOfChecks === 0) && !throwOnChange)) { this._TagInputComponent_34_4.ngOnInit(); }
    changes = (null as any);
    const currVal_25:any = this.parent.context.tags;
    if (import4.checkBinding(throwOnChange,this._expr_25,currVal_25)) {
      this._NgModel_34_6.model = currVal_25;
      if ((changes === (null as any))) { (changes = {}); }
      changes['model'] = new import7.SimpleChange(this._expr_25,currVal_25);
      this._expr_25 = currVal_25;
    }
    if ((changes !== (null as any))) { this._NgModel_34_6.ngOnChanges(changes); }
    this.detectContentChildrenChanges(throwOnChange);
    const currVal_0:any = import4.interpolate(1,'',this.parent.context.lS.translateByKey('pages.news.addNews.content'),': ');
    if (import4.checkBinding(throwOnChange,this._expr_0,currVal_0)) {
      this.renderer.setText(this._text_3,currVal_0);
      this._expr_0 = currVal_0;
    }
    const currVal_4:any = this._NgControlStatusGroup_11_5.ngClassUntouched;
    if (import4.checkBinding(throwOnChange,this._expr_4,currVal_4)) {
      this.renderer.setElementClass(this._el_11,'ng-untouched',currVal_4);
      this._expr_4 = currVal_4;
    }
    const currVal_5:any = this._NgControlStatusGroup_11_5.ngClassTouched;
    if (import4.checkBinding(throwOnChange,this._expr_5,currVal_5)) {
      this.renderer.setElementClass(this._el_11,'ng-touched',currVal_5);
      this._expr_5 = currVal_5;
    }
    const currVal_6:any = this._NgControlStatusGroup_11_5.ngClassPristine;
    if (import4.checkBinding(throwOnChange,this._expr_6,currVal_6)) {
      this.renderer.setElementClass(this._el_11,'ng-pristine',currVal_6);
      this._expr_6 = currVal_6;
    }
    const currVal_7:any = this._NgControlStatusGroup_11_5.ngClassDirty;
    if (import4.checkBinding(throwOnChange,this._expr_7,currVal_7)) {
      this.renderer.setElementClass(this._el_11,'ng-dirty',currVal_7);
      this._expr_7 = currVal_7;
    }
    const currVal_8:any = this._NgControlStatusGroup_11_5.ngClassValid;
    if (import4.checkBinding(throwOnChange,this._expr_8,currVal_8)) {
      this.renderer.setElementClass(this._el_11,'ng-valid',currVal_8);
      this._expr_8 = currVal_8;
    }
    const currVal_9:any = this._NgControlStatusGroup_11_5.ngClassInvalid;
    if (import4.checkBinding(throwOnChange,this._expr_9,currVal_9)) {
      this.renderer.setElementClass(this._el_11,'ng-invalid',currVal_9);
      this._expr_9 = currVal_9;
    }
    const currVal_14:any = this._NgControlStatus_13_7.ngClassUntouched;
    if (import4.checkBinding(throwOnChange,this._expr_14,currVal_14)) {
      this.renderer.setElementClass(this._el_13,'ng-untouched',currVal_14);
      this._expr_14 = currVal_14;
    }
    const currVal_15:any = this._NgControlStatus_13_7.ngClassTouched;
    if (import4.checkBinding(throwOnChange,this._expr_15,currVal_15)) {
      this.renderer.setElementClass(this._el_13,'ng-touched',currVal_15);
      this._expr_15 = currVal_15;
    }
    const currVal_16:any = this._NgControlStatus_13_7.ngClassPristine;
    if (import4.checkBinding(throwOnChange,this._expr_16,currVal_16)) {
      this.renderer.setElementClass(this._el_13,'ng-pristine',currVal_16);
      this._expr_16 = currVal_16;
    }
    const currVal_17:any = this._NgControlStatus_13_7.ngClassDirty;
    if (import4.checkBinding(throwOnChange,this._expr_17,currVal_17)) {
      this.renderer.setElementClass(this._el_13,'ng-dirty',currVal_17);
      this._expr_17 = currVal_17;
    }
    const currVal_18:any = this._NgControlStatus_13_7.ngClassValid;
    if (import4.checkBinding(throwOnChange,this._expr_18,currVal_18)) {
      this.renderer.setElementClass(this._el_13,'ng-valid',currVal_18);
      this._expr_18 = currVal_18;
    }
    const currVal_19:any = this._NgControlStatus_13_7.ngClassInvalid;
    if (import4.checkBinding(throwOnChange,this._expr_19,currVal_19)) {
      this.renderer.setElementClass(this._el_13,'ng-invalid',currVal_19);
      this._expr_19 = currVal_19;
    }
    const currVal_24:any = this._TagInputComponent_34_4.isFocused;
    if (import4.checkBinding(throwOnChange,this._expr_24,currVal_24)) {
      this.renderer.setElementClass(this._el_34,'ng2-tag-input-focus',currVal_24);
      this._expr_24 = currVal_24;
    }
    const currVal_26:any = this._NgControlStatus_34_8.ngClassUntouched;
    if (import4.checkBinding(throwOnChange,this._expr_26,currVal_26)) {
      this.renderer.setElementClass(this._el_34,'ng-untouched',currVal_26);
      this._expr_26 = currVal_26;
    }
    const currVal_27:any = this._NgControlStatus_34_8.ngClassTouched;
    if (import4.checkBinding(throwOnChange,this._expr_27,currVal_27)) {
      this.renderer.setElementClass(this._el_34,'ng-touched',currVal_27);
      this._expr_27 = currVal_27;
    }
    const currVal_28:any = this._NgControlStatus_34_8.ngClassPristine;
    if (import4.checkBinding(throwOnChange,this._expr_28,currVal_28)) {
      this.renderer.setElementClass(this._el_34,'ng-pristine',currVal_28);
      this._expr_28 = currVal_28;
    }
    const currVal_29:any = this._NgControlStatus_34_8.ngClassDirty;
    if (import4.checkBinding(throwOnChange,this._expr_29,currVal_29)) {
      this.renderer.setElementClass(this._el_34,'ng-dirty',currVal_29);
      this._expr_29 = currVal_29;
    }
    const currVal_30:any = this._NgControlStatus_34_8.ngClassValid;
    if (import4.checkBinding(throwOnChange,this._expr_30,currVal_30)) {
      this.renderer.setElementClass(this._el_34,'ng-valid',currVal_30);
      this._expr_30 = currVal_30;
    }
    const currVal_31:any = this._NgControlStatus_34_8.ngClassInvalid;
    if (import4.checkBinding(throwOnChange,this._expr_31,currVal_31)) {
      this.renderer.setElementClass(this._el_34,'ng-invalid',currVal_31);
      this._expr_31 = currVal_31;
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
  destroyInternal():void {
    this._NgModel_13_5.ngOnDestroy();
    this._TagInputComponent_34_4.ngOnDestroy();
    this._NgModel_34_6.ngOnDestroy();
  }
  private _handle_ngSubmit_11_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.parent.context.addNews(this._NgForm_11_3)) !== false);
    return (true && pd_0);
  }
  private _handle_submit_11_1($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._NgForm_11_3.onSubmit()) !== false);
    return (true && pd_0);
  }
  private _handle_reset_11_2($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._NgForm_11_3.onReset()) !== false);
    return (true && pd_0);
  }
  private _handle_input_13_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._DefaultValueAccessor_13_3.onChange($event.target.value)) !== false);
    return (true && pd_0);
  }
  private _handle_blur_13_1($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._DefaultValueAccessor_13_3.onTouched()) !== false);
    return (true && pd_0);
  }
  private _handle_click_27_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.parent.context.showAddNewsModal()) !== false);
    return (true && pd_0);
  }
  private _handle_ngModelChange_34_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>(this.parent.context.tags = $event)) !== false);
    return (true && pd_0);
  }
  private _handle_click_34_1($event:any):boolean {
    this._appEl_34.componentView.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._TagInputComponent_34_4.onDocumentClick($event,$event.target)) !== false);
    return (true && pd_0);
  }
}
function viewFactory_AddNews1(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  return new _View_AddNews1(viewUtils,parentInjector,declarationEl);
}