/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

import * as import0 from '@angular/core/src/render/api';
import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/linker/element';
import * as import3 from './RegistrationModal';
import * as import4 from '@angular/core/src/linker/view_utils';
import * as import5 from '@angular/core/src/di/injector';
import * as import6 from '@angular/core/src/linker/view_type';
import * as import7 from '@angular/core/src/change_detection/change_detection';
import * as import8 from '@angular/http/src/http';
import * as import9 from '../../../services/ModalService';
import * as import10 from '../../../services/UserInformationService';
import * as import11 from '../../../services/AuthService';
import * as import12 from '../../../services/LocalStorageService';
import * as import13 from 'ng2-toastr/src/toast-manager';
import * as import14 from '@angular/core/src/metadata/view';
import * as import15 from '@angular/core/src/linker/component_factory';
import * as import16 from '@angular/forms/src/directives/ng_form';
import * as import17 from '@angular/forms/src/directives/ng_control_status';
import * as import18 from '@angular/forms/src/directives/default_value_accessor';
import * as import19 from '@angular/forms/src/directives/ng_model';
import * as import20 from '@angular/core/src/linker/element_ref';
import * as import21 from '@angular/forms/src/directives/control_value_accessor';
import * as import22 from '@angular/forms/src/directives/ng_control';
import * as import23 from '@angular/forms/src/directives/control_container';
import * as import24 from '@angular/core/src/security';
var renderType_RegistrationModal_Host:import0.RenderComponentType = (null as any);
class _View_RegistrationModal_Host0 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import2.AppElement;
  _RegistrationModal_0_4:import3.RegistrationModal;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_RegistrationModal_Host0,renderType_RegistrationModal_Host,import6.ViewType.HOST,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.selectOrCreateHostElement('registration-modal',rootSelector,(null as any));
    this._appEl_0 = new import2.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = viewFactory_RegistrationModal0(this.viewUtils,this.injector(0),this._appEl_0);
    this._RegistrationModal_0_4 = new import3.RegistrationModal(this.parentInjector.get(import8.Http),this.parentInjector.get(import9.ModalService),this.parentInjector.get(import10.UserInformationService),this.parentInjector.get(import11.AuthService),this.parentInjector.get(import12.LocalStorageService),this.parentInjector.get(import13.ToastsManager));
    this._appEl_0.initComponent(this._RegistrationModal_0_4,[],compView_0);
    compView_0.create(this._RegistrationModal_0_4,this.projectableNodes,(null as any));
    this.init([].concat([this._el_0]),[this._el_0],[],[]);
    return this._appEl_0;
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import3.RegistrationModal) && (0 === requestNodeIndex))) { return this._RegistrationModal_0_4; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    if (((this.numberOfChecks === 0) && !throwOnChange)) { this._RegistrationModal_0_4.ngOnInit(); }
    this.detectContentChildrenChanges(throwOnChange);
    this.detectViewChildrenChanges(throwOnChange);
  }
}
function viewFactory_RegistrationModal_Host0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  if ((renderType_RegistrationModal_Host === (null as any))) { (renderType_RegistrationModal_Host = viewUtils.createRenderComponentType('',0,import14.ViewEncapsulation.None,[],{})); }
  return new _View_RegistrationModal_Host0(viewUtils,parentInjector,declarationEl);
}
export const RegistrationModalNgFactory:import15.ComponentFactory<import3.RegistrationModal> = new import15.ComponentFactory<import3.RegistrationModal>('registration-modal',viewFactory_RegistrationModal_Host0,import3.RegistrationModal);
const styles_RegistrationModal:any[] = [];
var renderType_RegistrationModal:import0.RenderComponentType = (null as any);
class _View_RegistrationModal0 extends import1.AppView<import3.RegistrationModal> {
  _el_0:any;
  _text_1:any;
  _el_2:any;
  _text_3:any;
  _el_4:any;
  _text_5:any;
  _el_6:any;
  _text_7:any;
  _el_8:any;
  _text_9:any;
  _el_10:any;
  _text_11:any;
  _text_12:any;
  _text_13:any;
  _el_14:any;
  _text_15:any;
  _text_16:any;
  _text_17:any;
  _el_18:any;
  _text_19:any;
  _el_20:any;
  _NgForm_20_3:import16.NgForm;
  _ControlContainer_20_4:any;
  _NgControlStatusGroup_20_5:import17.NgControlStatusGroup;
  _text_21:any;
  _el_22:any;
  _text_23:any;
  _el_24:any;
  _text_25:any;
  _text_26:any;
  _el_27:any;
  _DefaultValueAccessor_27_3:import18.DefaultValueAccessor;
  _NG_VALUE_ACCESSOR_27_4:any[];
  _NgModel_27_5:import19.NgModel;
  _NgControl_27_6:any;
  _NgControlStatus_27_7:import17.NgControlStatus;
  _text_28:any;
  _text_29:any;
  _el_30:any;
  _text_31:any;
  _el_32:any;
  _text_33:any;
  _text_34:any;
  _el_35:any;
  _DefaultValueAccessor_35_3:import18.DefaultValueAccessor;
  _NG_VALUE_ACCESSOR_35_4:any[];
  _NgModel_35_5:import19.NgModel;
  _NgControl_35_6:any;
  _NgControlStatus_35_7:import17.NgControlStatus;
  _text_36:any;
  _text_37:any;
  _el_38:any;
  _text_39:any;
  _el_40:any;
  _text_41:any;
  _text_42:any;
  _el_43:any;
  _DefaultValueAccessor_43_3:import18.DefaultValueAccessor;
  _NG_VALUE_ACCESSOR_43_4:any[];
  _NgModel_43_5:import19.NgModel;
  _NgControl_43_6:any;
  _NgControlStatus_43_7:import17.NgControlStatus;
  _text_44:any;
  _text_45:any;
  _el_46:any;
  _text_47:any;
  _el_48:any;
  _text_49:any;
  _text_50:any;
  _el_51:any;
  _DefaultValueAccessor_51_3:import18.DefaultValueAccessor;
  _NG_VALUE_ACCESSOR_51_4:any[];
  _NgModel_51_5:import19.NgModel;
  _NgControl_51_6:any;
  _NgControlStatus_51_7:import17.NgControlStatus;
  _text_52:any;
  _text_53:any;
  _text_54:any;
  _el_55:any;
  _text_56:any;
  _text_57:any;
  _text_58:any;
  _el_59:any;
  _text_60:any;
  _el_61:any;
  _text_62:any;
  _text_63:any;
  _el_64:any;
  _text_65:any;
  _text_66:any;
  _text_67:any;
  _text_68:any;
  _text_69:any;
  _text_70:any;
  /*private*/ _expr_3:any;
  /*private*/ _expr_4:any;
  /*private*/ _expr_5:any;
  /*private*/ _expr_6:any;
  /*private*/ _expr_7:any;
  /*private*/ _expr_8:any;
  /*private*/ _expr_12:any;
  _map_0:any;
  /*private*/ _expr_13:any;
  /*private*/ _expr_14:any;
  /*private*/ _expr_15:any;
  /*private*/ _expr_16:any;
  /*private*/ _expr_17:any;
  /*private*/ _expr_18:any;
  /*private*/ _expr_19:any;
  /*private*/ _expr_23:any;
  _map_1:any;
  /*private*/ _expr_24:any;
  /*private*/ _expr_25:any;
  /*private*/ _expr_26:any;
  /*private*/ _expr_27:any;
  /*private*/ _expr_28:any;
  /*private*/ _expr_29:any;
  /*private*/ _expr_30:any;
  /*private*/ _expr_34:any;
  _map_2:any;
  /*private*/ _expr_35:any;
  /*private*/ _expr_36:any;
  /*private*/ _expr_37:any;
  /*private*/ _expr_38:any;
  /*private*/ _expr_39:any;
  /*private*/ _expr_40:any;
  /*private*/ _expr_41:any;
  /*private*/ _expr_45:any;
  _map_3:any;
  /*private*/ _expr_46:any;
  /*private*/ _expr_47:any;
  /*private*/ _expr_48:any;
  /*private*/ _expr_49:any;
  /*private*/ _expr_50:any;
  /*private*/ _expr_51:any;
  /*private*/ _expr_52:any;
  /*private*/ _expr_53:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_RegistrationModal0,renderType_RegistrationModal,import6.ViewType.COMPONENT,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    const parentRenderNode:any = this.renderer.createViewRoot(this.declarationAppElement.nativeElement);
    this._el_0 = this.renderer.createElement(parentRenderNode,'div',(null as any));
    this.renderer.setElementAttribute(this._el_0,'aria-labelledby','exampleModalLabel');
    this.renderer.setElementAttribute(this._el_0,'class','modal');
    this.renderer.setElementAttribute(this._el_0,'id','exampleModal');
    this.renderer.setElementAttribute(this._el_0,'role','dialog');
    this.renderer.setElementAttribute(this._el_0,'tabindex','-1');
    this._text_1 = this.renderer.createText(this._el_0,'\n  ',(null as any));
    this._el_2 = this.renderer.createElement(this._el_0,'div',(null as any));
    this.renderer.setElementAttribute(this._el_2,'class','modal-dialog');
    this.renderer.setElementAttribute(this._el_2,'role','document');
    this._text_3 = this.renderer.createText(this._el_2,'\n    ',(null as any));
    this._el_4 = this.renderer.createElement(this._el_2,'div',(null as any));
    this.renderer.setElementAttribute(this._el_4,'class','modal-content');
    this._text_5 = this.renderer.createText(this._el_4,'\n      ',(null as any));
    this._el_6 = this.renderer.createElement(this._el_4,'div',(null as any));
    this.renderer.setElementAttribute(this._el_6,'class','modal-header');
    this._text_7 = this.renderer.createText(this._el_6,'\n        ',(null as any));
    this._el_8 = this.renderer.createElement(this._el_6,'button',(null as any));
    this.renderer.setElementAttribute(this._el_8,'aria-label','Close');
    this.renderer.setElementAttribute(this._el_8,'class','close');
    this.renderer.setElementAttribute(this._el_8,'type','button');
    this._text_9 = this.renderer.createText(this._el_8,'\n          ',(null as any));
    this._el_10 = this.renderer.createElement(this._el_8,'span',(null as any));
    this.renderer.setElementAttribute(this._el_10,'aria-hidden','true');
    this._text_11 = this.renderer.createText(this._el_10,'×',(null as any));
    this._text_12 = this.renderer.createText(this._el_8,'\n        ',(null as any));
    this._text_13 = this.renderer.createText(this._el_6,'\n        ',(null as any));
    this._el_14 = this.renderer.createElement(this._el_6,'h1',(null as any));
    this.renderer.setElementAttribute(this._el_14,'class','modal-title');
    this.renderer.setElementAttribute(this._el_14,'id','exampleModalLabel');
    this._text_15 = this.renderer.createText(this._el_14,'Регитрация',(null as any));
    this._text_16 = this.renderer.createText(this._el_6,'\n      ',(null as any));
    this._text_17 = this.renderer.createText(this._el_4,'\n      ',(null as any));
    this._el_18 = this.renderer.createElement(this._el_4,'div',(null as any));
    this.renderer.setElementAttribute(this._el_18,'class','modal-body');
    this._text_19 = this.renderer.createText(this._el_18,'\n        ',(null as any));
    this._el_20 = this.renderer.createElement(this._el_18,'form',(null as any));
    this._NgForm_20_3 = new import16.NgForm((null as any),(null as any));
    this._ControlContainer_20_4 = this._NgForm_20_3;
    this._NgControlStatusGroup_20_5 = new import17.NgControlStatusGroup(this._ControlContainer_20_4);
    this._text_21 = this.renderer.createText(this._el_20,'\n          ',(null as any));
    this._el_22 = this.renderer.createElement(this._el_20,'div',(null as any));
    this.renderer.setElementAttribute(this._el_22,'class','form-group');
    this._text_23 = this.renderer.createText(this._el_22,'\n            ',(null as any));
    this._el_24 = this.renderer.createElement(this._el_22,'label',(null as any));
    this.renderer.setElementAttribute(this._el_24,'class','form-control-label');
    this.renderer.setElementAttribute(this._el_24,'for','name');
    this._text_25 = this.renderer.createText(this._el_24,'Имя:',(null as any));
    this._text_26 = this.renderer.createText(this._el_22,'\n            ',(null as any));
    this._el_27 = this.renderer.createElement(this._el_22,'input',(null as any));
    this.renderer.setElementAttribute(this._el_27,'class','form-control');
    this.renderer.setElementAttribute(this._el_27,'id','name');
    this.renderer.setElementAttribute(this._el_27,'type','text');
    this._DefaultValueAccessor_27_3 = new import18.DefaultValueAccessor(this.renderer,new import20.ElementRef(this._el_27));
    this._NG_VALUE_ACCESSOR_27_4 = [this._DefaultValueAccessor_27_3];
    this._NgModel_27_5 = new import19.NgModel(this._ControlContainer_20_4,(null as any),(null as any),this._NG_VALUE_ACCESSOR_27_4);
    this._NgControl_27_6 = this._NgModel_27_5;
    this._NgControlStatus_27_7 = new import17.NgControlStatus(this._NgControl_27_6);
    this._text_28 = this.renderer.createText(this._el_22,'\n          ',(null as any));
    this._text_29 = this.renderer.createText(this._el_20,'\n          ',(null as any));
    this._el_30 = this.renderer.createElement(this._el_20,'div',(null as any));
    this.renderer.setElementAttribute(this._el_30,'class','form-group');
    this._text_31 = this.renderer.createText(this._el_30,'\n            ',(null as any));
    this._el_32 = this.renderer.createElement(this._el_30,'label',(null as any));
    this.renderer.setElementAttribute(this._el_32,'class','form-control-label');
    this.renderer.setElementAttribute(this._el_32,'for','nickname');
    this._text_33 = this.renderer.createText(this._el_32,'Игровой ник:',(null as any));
    this._text_34 = this.renderer.createText(this._el_30,'\n            ',(null as any));
    this._el_35 = this.renderer.createElement(this._el_30,'input',(null as any));
    this.renderer.setElementAttribute(this._el_35,'class','form-control');
    this.renderer.setElementAttribute(this._el_35,'id','nickname');
    this.renderer.setElementAttribute(this._el_35,'type','text');
    this._DefaultValueAccessor_35_3 = new import18.DefaultValueAccessor(this.renderer,new import20.ElementRef(this._el_35));
    this._NG_VALUE_ACCESSOR_35_4 = [this._DefaultValueAccessor_35_3];
    this._NgModel_35_5 = new import19.NgModel(this._ControlContainer_20_4,(null as any),(null as any),this._NG_VALUE_ACCESSOR_35_4);
    this._NgControl_35_6 = this._NgModel_35_5;
    this._NgControlStatus_35_7 = new import17.NgControlStatus(this._NgControl_35_6);
    this._text_36 = this.renderer.createText(this._el_30,'\n          ',(null as any));
    this._text_37 = this.renderer.createText(this._el_20,'\n          ',(null as any));
    this._el_38 = this.renderer.createElement(this._el_20,'div',(null as any));
    this.renderer.setElementAttribute(this._el_38,'class','form-group');
    this._text_39 = this.renderer.createText(this._el_38,'\n            ',(null as any));
    this._el_40 = this.renderer.createElement(this._el_38,'label',(null as any));
    this.renderer.setElementAttribute(this._el_40,'class','form-control-label');
    this.renderer.setElementAttribute(this._el_40,'for','email');
    this._text_41 = this.renderer.createText(this._el_40,'Адресс електронной почты:',(null as any));
    this._text_42 = this.renderer.createText(this._el_38,'\n            ',(null as any));
    this._el_43 = this.renderer.createElement(this._el_38,'input',(null as any));
    this.renderer.setElementAttribute(this._el_43,'class','form-control');
    this.renderer.setElementAttribute(this._el_43,'id','email');
    this.renderer.setElementAttribute(this._el_43,'type','text');
    this._DefaultValueAccessor_43_3 = new import18.DefaultValueAccessor(this.renderer,new import20.ElementRef(this._el_43));
    this._NG_VALUE_ACCESSOR_43_4 = [this._DefaultValueAccessor_43_3];
    this._NgModel_43_5 = new import19.NgModel(this._ControlContainer_20_4,(null as any),(null as any),this._NG_VALUE_ACCESSOR_43_4);
    this._NgControl_43_6 = this._NgModel_43_5;
    this._NgControlStatus_43_7 = new import17.NgControlStatus(this._NgControl_43_6);
    this._text_44 = this.renderer.createText(this._el_38,'\n          ',(null as any));
    this._text_45 = this.renderer.createText(this._el_20,'\n          ',(null as any));
    this._el_46 = this.renderer.createElement(this._el_20,'div',(null as any));
    this.renderer.setElementAttribute(this._el_46,'class','form-group');
    this._text_47 = this.renderer.createText(this._el_46,'\n            ',(null as any));
    this._el_48 = this.renderer.createElement(this._el_46,'label',(null as any));
    this.renderer.setElementAttribute(this._el_48,'class','form-control-label');
    this.renderer.setElementAttribute(this._el_48,'for','password');
    this._text_49 = this.renderer.createText(this._el_48,'Пароль:',(null as any));
    this._text_50 = this.renderer.createText(this._el_46,'\n            ',(null as any));
    this._el_51 = this.renderer.createElement(this._el_46,'input',(null as any));
    this.renderer.setElementAttribute(this._el_51,'class','form-control');
    this.renderer.setElementAttribute(this._el_51,'id','password');
    this.renderer.setElementAttribute(this._el_51,'type','password');
    this._DefaultValueAccessor_51_3 = new import18.DefaultValueAccessor(this.renderer,new import20.ElementRef(this._el_51));
    this._NG_VALUE_ACCESSOR_51_4 = [this._DefaultValueAccessor_51_3];
    this._NgModel_51_5 = new import19.NgModel(this._ControlContainer_20_4,(null as any),(null as any),this._NG_VALUE_ACCESSOR_51_4);
    this._NgControl_51_6 = this._NgModel_51_5;
    this._NgControlStatus_51_7 = new import17.NgControlStatus(this._NgControl_51_6);
    this._text_52 = this.renderer.createText(this._el_46,'\n          ',(null as any));
    this._text_53 = this.renderer.createText(this._el_20,'\n        ',(null as any));
    this._text_54 = this.renderer.createText(this._el_18,'\n        ',(null as any));
    this._el_55 = this.renderer.createElement(this._el_18,'a',(null as any));
    this._text_56 = this.renderer.createText(this._el_55,'Steam',(null as any));
    this._text_57 = this.renderer.createText(this._el_18,'\n      ',(null as any));
    this._text_58 = this.renderer.createText(this._el_4,'\n      ',(null as any));
    this._el_59 = this.renderer.createElement(this._el_4,'div',(null as any));
    this.renderer.setElementAttribute(this._el_59,'class','modal-footer');
    this._text_60 = this.renderer.createText(this._el_59,'\n        ',(null as any));
    this._el_61 = this.renderer.createElement(this._el_59,'button',(null as any));
    this.renderer.setElementAttribute(this._el_61,'class','btn btn-secondary');
    this.renderer.setElementAttribute(this._el_61,'data-dismiss','modal');
    this.renderer.setElementAttribute(this._el_61,'type','button');
    this._text_62 = this.renderer.createText(this._el_61,'\n          Закрыть\n        ',(null as any));
    this._text_63 = this.renderer.createText(this._el_59,'\n        ',(null as any));
    this._el_64 = this.renderer.createElement(this._el_59,'button',(null as any));
    this.renderer.setElementAttribute(this._el_64,'class','btn btn-primary');
    this.renderer.setElementAttribute(this._el_64,'type','button');
    this._text_65 = this.renderer.createText(this._el_64,'Регистрация',(null as any));
    this._text_66 = this.renderer.createText(this._el_59,'\n      ',(null as any));
    this._text_67 = this.renderer.createText(this._el_4,'\n    ',(null as any));
    this._text_68 = this.renderer.createText(this._el_2,'\n  ',(null as any));
    this._text_69 = this.renderer.createText(this._el_0,'\n',(null as any));
    this._text_70 = this.renderer.createText(parentRenderNode,'\n',(null as any));
    var disposable_0:Function = this.renderer.listen(this._el_8,'click',this.eventHandler(this._handle_click_8_0.bind(this)));
    var disposable_1:Function = this.renderer.listen(this._el_20,'submit',this.eventHandler(this._handle_submit_20_0.bind(this)));
    var disposable_2:Function = this.renderer.listen(this._el_20,'reset',this.eventHandler(this._handle_reset_20_1.bind(this)));
    this._expr_3 = import7.UNINITIALIZED;
    this._expr_4 = import7.UNINITIALIZED;
    this._expr_5 = import7.UNINITIALIZED;
    this._expr_6 = import7.UNINITIALIZED;
    this._expr_7 = import7.UNINITIALIZED;
    this._expr_8 = import7.UNINITIALIZED;
    var disposable_3:Function = this.renderer.listen(this._el_27,'ngModelChange',this.eventHandler(this._handle_ngModelChange_27_0.bind(this)));
    var disposable_4:Function = this.renderer.listen(this._el_27,'input',this.eventHandler(this._handle_input_27_1.bind(this)));
    var disposable_5:Function = this.renderer.listen(this._el_27,'blur',this.eventHandler(this._handle_blur_27_2.bind(this)));
    this._expr_12 = import7.UNINITIALIZED;
    this._map_0 = import4.pureProxy1((p0:any):{[key: string]:any} => {
      return {standalone: p0};
    });
    this._expr_13 = import7.UNINITIALIZED;
    const subscription_0:any = this._NgModel_27_5.update.subscribe(this.eventHandler(this._handle_ngModelChange_27_0.bind(this)));
    this._expr_14 = import7.UNINITIALIZED;
    this._expr_15 = import7.UNINITIALIZED;
    this._expr_16 = import7.UNINITIALIZED;
    this._expr_17 = import7.UNINITIALIZED;
    this._expr_18 = import7.UNINITIALIZED;
    this._expr_19 = import7.UNINITIALIZED;
    var disposable_6:Function = this.renderer.listen(this._el_35,'ngModelChange',this.eventHandler(this._handle_ngModelChange_35_0.bind(this)));
    var disposable_7:Function = this.renderer.listen(this._el_35,'input',this.eventHandler(this._handle_input_35_1.bind(this)));
    var disposable_8:Function = this.renderer.listen(this._el_35,'blur',this.eventHandler(this._handle_blur_35_2.bind(this)));
    this._expr_23 = import7.UNINITIALIZED;
    this._map_1 = import4.pureProxy1((p0:any):{[key: string]:any} => {
      return {standalone: p0};
    });
    this._expr_24 = import7.UNINITIALIZED;
    const subscription_1:any = this._NgModel_35_5.update.subscribe(this.eventHandler(this._handle_ngModelChange_35_0.bind(this)));
    this._expr_25 = import7.UNINITIALIZED;
    this._expr_26 = import7.UNINITIALIZED;
    this._expr_27 = import7.UNINITIALIZED;
    this._expr_28 = import7.UNINITIALIZED;
    this._expr_29 = import7.UNINITIALIZED;
    this._expr_30 = import7.UNINITIALIZED;
    var disposable_9:Function = this.renderer.listen(this._el_43,'ngModelChange',this.eventHandler(this._handle_ngModelChange_43_0.bind(this)));
    var disposable_10:Function = this.renderer.listen(this._el_43,'input',this.eventHandler(this._handle_input_43_1.bind(this)));
    var disposable_11:Function = this.renderer.listen(this._el_43,'blur',this.eventHandler(this._handle_blur_43_2.bind(this)));
    this._expr_34 = import7.UNINITIALIZED;
    this._map_2 = import4.pureProxy1((p0:any):{[key: string]:any} => {
      return {standalone: p0};
    });
    this._expr_35 = import7.UNINITIALIZED;
    const subscription_2:any = this._NgModel_43_5.update.subscribe(this.eventHandler(this._handle_ngModelChange_43_0.bind(this)));
    this._expr_36 = import7.UNINITIALIZED;
    this._expr_37 = import7.UNINITIALIZED;
    this._expr_38 = import7.UNINITIALIZED;
    this._expr_39 = import7.UNINITIALIZED;
    this._expr_40 = import7.UNINITIALIZED;
    this._expr_41 = import7.UNINITIALIZED;
    var disposable_12:Function = this.renderer.listen(this._el_51,'ngModelChange',this.eventHandler(this._handle_ngModelChange_51_0.bind(this)));
    var disposable_13:Function = this.renderer.listen(this._el_51,'input',this.eventHandler(this._handle_input_51_1.bind(this)));
    var disposable_14:Function = this.renderer.listen(this._el_51,'blur',this.eventHandler(this._handle_blur_51_2.bind(this)));
    this._expr_45 = import7.UNINITIALIZED;
    this._map_3 = import4.pureProxy1((p0:any):{[key: string]:any} => {
      return {standalone: p0};
    });
    this._expr_46 = import7.UNINITIALIZED;
    const subscription_3:any = this._NgModel_51_5.update.subscribe(this.eventHandler(this._handle_ngModelChange_51_0.bind(this)));
    this._expr_47 = import7.UNINITIALIZED;
    this._expr_48 = import7.UNINITIALIZED;
    this._expr_49 = import7.UNINITIALIZED;
    this._expr_50 = import7.UNINITIALIZED;
    this._expr_51 = import7.UNINITIALIZED;
    this._expr_52 = import7.UNINITIALIZED;
    this._expr_53 = import7.UNINITIALIZED;
    var disposable_15:Function = this.renderer.listen(this._el_61,'click',this.eventHandler(this._handle_click_61_0.bind(this)));
    var disposable_16:Function = this.renderer.listen(this._el_64,'click',this.eventHandler(this._handle_click_64_0.bind(this)));
    this.init([],[
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._el_4,
      this._text_5,
      this._el_6,
      this._text_7,
      this._el_8,
      this._text_9,
      this._el_10,
      this._text_11,
      this._text_12,
      this._text_13,
      this._el_14,
      this._text_15,
      this._text_16,
      this._text_17,
      this._el_18,
      this._text_19,
      this._el_20,
      this._text_21,
      this._el_22,
      this._text_23,
      this._el_24,
      this._text_25,
      this._text_26,
      this._el_27,
      this._text_28,
      this._text_29,
      this._el_30,
      this._text_31,
      this._el_32,
      this._text_33,
      this._text_34,
      this._el_35,
      this._text_36,
      this._text_37,
      this._el_38,
      this._text_39,
      this._el_40,
      this._text_41,
      this._text_42,
      this._el_43,
      this._text_44,
      this._text_45,
      this._el_46,
      this._text_47,
      this._el_48,
      this._text_49,
      this._text_50,
      this._el_51,
      this._text_52,
      this._text_53,
      this._text_54,
      this._el_55,
      this._text_56,
      this._text_57,
      this._text_58,
      this._el_59,
      this._text_60,
      this._el_61,
      this._text_62,
      this._text_63,
      this._el_64,
      this._text_65,
      this._text_66,
      this._text_67,
      this._text_68,
      this._text_69,
      this._text_70
    ]
    ,[
      disposable_0,
      disposable_1,
      disposable_2,
      disposable_3,
      disposable_4,
      disposable_5,
      disposable_6,
      disposable_7,
      disposable_8,
      disposable_9,
      disposable_10,
      disposable_11,
      disposable_12,
      disposable_13,
      disposable_14,
      disposable_15,
      disposable_16
    ]
    ,[
      subscription_0,
      subscription_1,
      subscription_2,
      subscription_3
    ]
    );
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import18.DefaultValueAccessor) && (27 === requestNodeIndex))) { return this._DefaultValueAccessor_27_3; }
    if (((token === import21.NG_VALUE_ACCESSOR) && (27 === requestNodeIndex))) { return this._NG_VALUE_ACCESSOR_27_4; }
    if (((token === import19.NgModel) && (27 === requestNodeIndex))) { return this._NgModel_27_5; }
    if (((token === import22.NgControl) && (27 === requestNodeIndex))) { return this._NgControl_27_6; }
    if (((token === import17.NgControlStatus) && (27 === requestNodeIndex))) { return this._NgControlStatus_27_7; }
    if (((token === import18.DefaultValueAccessor) && (35 === requestNodeIndex))) { return this._DefaultValueAccessor_35_3; }
    if (((token === import21.NG_VALUE_ACCESSOR) && (35 === requestNodeIndex))) { return this._NG_VALUE_ACCESSOR_35_4; }
    if (((token === import19.NgModel) && (35 === requestNodeIndex))) { return this._NgModel_35_5; }
    if (((token === import22.NgControl) && (35 === requestNodeIndex))) { return this._NgControl_35_6; }
    if (((token === import17.NgControlStatus) && (35 === requestNodeIndex))) { return this._NgControlStatus_35_7; }
    if (((token === import18.DefaultValueAccessor) && (43 === requestNodeIndex))) { return this._DefaultValueAccessor_43_3; }
    if (((token === import21.NG_VALUE_ACCESSOR) && (43 === requestNodeIndex))) { return this._NG_VALUE_ACCESSOR_43_4; }
    if (((token === import19.NgModel) && (43 === requestNodeIndex))) { return this._NgModel_43_5; }
    if (((token === import22.NgControl) && (43 === requestNodeIndex))) { return this._NgControl_43_6; }
    if (((token === import17.NgControlStatus) && (43 === requestNodeIndex))) { return this._NgControlStatus_43_7; }
    if (((token === import18.DefaultValueAccessor) && (51 === requestNodeIndex))) { return this._DefaultValueAccessor_51_3; }
    if (((token === import21.NG_VALUE_ACCESSOR) && (51 === requestNodeIndex))) { return this._NG_VALUE_ACCESSOR_51_4; }
    if (((token === import19.NgModel) && (51 === requestNodeIndex))) { return this._NgModel_51_5; }
    if (((token === import22.NgControl) && (51 === requestNodeIndex))) { return this._NgControl_51_6; }
    if (((token === import17.NgControlStatus) && (51 === requestNodeIndex))) { return this._NgControlStatus_51_7; }
    if (((token === import16.NgForm) && ((20 <= requestNodeIndex) && (requestNodeIndex <= 53)))) { return this._NgForm_20_3; }
    if (((token === import23.ControlContainer) && ((20 <= requestNodeIndex) && (requestNodeIndex <= 53)))) { return this._ControlContainer_20_4; }
    if (((token === import17.NgControlStatusGroup) && ((20 <= requestNodeIndex) && (requestNodeIndex <= 53)))) { return this._NgControlStatusGroup_20_5; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    var changes:{[key: string]:import7.SimpleChange} = (null as any);
    changes = (null as any);
    const currVal_12:any = this.context.name;
    if (import4.checkBinding(throwOnChange,this._expr_12,currVal_12)) {
      this._NgModel_27_5.model = currVal_12;
      if ((changes === (null as any))) { (changes = {}); }
      changes['model'] = new import7.SimpleChange(this._expr_12,currVal_12);
      this._expr_12 = currVal_12;
    }
    const currVal_13:any = this._map_0(true);
    if (import4.checkBinding(throwOnChange,this._expr_13,currVal_13)) {
      this._NgModel_27_5.options = currVal_13;
      if ((changes === (null as any))) { (changes = {}); }
      changes['options'] = new import7.SimpleChange(this._expr_13,currVal_13);
      this._expr_13 = currVal_13;
    }
    if ((changes !== (null as any))) { this._NgModel_27_5.ngOnChanges(changes); }
    changes = (null as any);
    const currVal_23:any = this.context.nickname;
    if (import4.checkBinding(throwOnChange,this._expr_23,currVal_23)) {
      this._NgModel_35_5.model = currVal_23;
      if ((changes === (null as any))) { (changes = {}); }
      changes['model'] = new import7.SimpleChange(this._expr_23,currVal_23);
      this._expr_23 = currVal_23;
    }
    const currVal_24:any = this._map_1(true);
    if (import4.checkBinding(throwOnChange,this._expr_24,currVal_24)) {
      this._NgModel_35_5.options = currVal_24;
      if ((changes === (null as any))) { (changes = {}); }
      changes['options'] = new import7.SimpleChange(this._expr_24,currVal_24);
      this._expr_24 = currVal_24;
    }
    if ((changes !== (null as any))) { this._NgModel_35_5.ngOnChanges(changes); }
    changes = (null as any);
    const currVal_34:any = this.context.email;
    if (import4.checkBinding(throwOnChange,this._expr_34,currVal_34)) {
      this._NgModel_43_5.model = currVal_34;
      if ((changes === (null as any))) { (changes = {}); }
      changes['model'] = new import7.SimpleChange(this._expr_34,currVal_34);
      this._expr_34 = currVal_34;
    }
    const currVal_35:any = this._map_2(true);
    if (import4.checkBinding(throwOnChange,this._expr_35,currVal_35)) {
      this._NgModel_43_5.options = currVal_35;
      if ((changes === (null as any))) { (changes = {}); }
      changes['options'] = new import7.SimpleChange(this._expr_35,currVal_35);
      this._expr_35 = currVal_35;
    }
    if ((changes !== (null as any))) { this._NgModel_43_5.ngOnChanges(changes); }
    changes = (null as any);
    const currVal_45:any = this.context.password;
    if (import4.checkBinding(throwOnChange,this._expr_45,currVal_45)) {
      this._NgModel_51_5.model = currVal_45;
      if ((changes === (null as any))) { (changes = {}); }
      changes['model'] = new import7.SimpleChange(this._expr_45,currVal_45);
      this._expr_45 = currVal_45;
    }
    const currVal_46:any = this._map_3(true);
    if (import4.checkBinding(throwOnChange,this._expr_46,currVal_46)) {
      this._NgModel_51_5.options = currVal_46;
      if ((changes === (null as any))) { (changes = {}); }
      changes['options'] = new import7.SimpleChange(this._expr_46,currVal_46);
      this._expr_46 = currVal_46;
    }
    if ((changes !== (null as any))) { this._NgModel_51_5.ngOnChanges(changes); }
    this.detectContentChildrenChanges(throwOnChange);
    const currVal_3:any = this._NgControlStatusGroup_20_5.ngClassUntouched;
    if (import4.checkBinding(throwOnChange,this._expr_3,currVal_3)) {
      this.renderer.setElementClass(this._el_20,'ng-untouched',currVal_3);
      this._expr_3 = currVal_3;
    }
    const currVal_4:any = this._NgControlStatusGroup_20_5.ngClassTouched;
    if (import4.checkBinding(throwOnChange,this._expr_4,currVal_4)) {
      this.renderer.setElementClass(this._el_20,'ng-touched',currVal_4);
      this._expr_4 = currVal_4;
    }
    const currVal_5:any = this._NgControlStatusGroup_20_5.ngClassPristine;
    if (import4.checkBinding(throwOnChange,this._expr_5,currVal_5)) {
      this.renderer.setElementClass(this._el_20,'ng-pristine',currVal_5);
      this._expr_5 = currVal_5;
    }
    const currVal_6:any = this._NgControlStatusGroup_20_5.ngClassDirty;
    if (import4.checkBinding(throwOnChange,this._expr_6,currVal_6)) {
      this.renderer.setElementClass(this._el_20,'ng-dirty',currVal_6);
      this._expr_6 = currVal_6;
    }
    const currVal_7:any = this._NgControlStatusGroup_20_5.ngClassValid;
    if (import4.checkBinding(throwOnChange,this._expr_7,currVal_7)) {
      this.renderer.setElementClass(this._el_20,'ng-valid',currVal_7);
      this._expr_7 = currVal_7;
    }
    const currVal_8:any = this._NgControlStatusGroup_20_5.ngClassInvalid;
    if (import4.checkBinding(throwOnChange,this._expr_8,currVal_8)) {
      this.renderer.setElementClass(this._el_20,'ng-invalid',currVal_8);
      this._expr_8 = currVal_8;
    }
    const currVal_14:any = this._NgControlStatus_27_7.ngClassUntouched;
    if (import4.checkBinding(throwOnChange,this._expr_14,currVal_14)) {
      this.renderer.setElementClass(this._el_27,'ng-untouched',currVal_14);
      this._expr_14 = currVal_14;
    }
    const currVal_15:any = this._NgControlStatus_27_7.ngClassTouched;
    if (import4.checkBinding(throwOnChange,this._expr_15,currVal_15)) {
      this.renderer.setElementClass(this._el_27,'ng-touched',currVal_15);
      this._expr_15 = currVal_15;
    }
    const currVal_16:any = this._NgControlStatus_27_7.ngClassPristine;
    if (import4.checkBinding(throwOnChange,this._expr_16,currVal_16)) {
      this.renderer.setElementClass(this._el_27,'ng-pristine',currVal_16);
      this._expr_16 = currVal_16;
    }
    const currVal_17:any = this._NgControlStatus_27_7.ngClassDirty;
    if (import4.checkBinding(throwOnChange,this._expr_17,currVal_17)) {
      this.renderer.setElementClass(this._el_27,'ng-dirty',currVal_17);
      this._expr_17 = currVal_17;
    }
    const currVal_18:any = this._NgControlStatus_27_7.ngClassValid;
    if (import4.checkBinding(throwOnChange,this._expr_18,currVal_18)) {
      this.renderer.setElementClass(this._el_27,'ng-valid',currVal_18);
      this._expr_18 = currVal_18;
    }
    const currVal_19:any = this._NgControlStatus_27_7.ngClassInvalid;
    if (import4.checkBinding(throwOnChange,this._expr_19,currVal_19)) {
      this.renderer.setElementClass(this._el_27,'ng-invalid',currVal_19);
      this._expr_19 = currVal_19;
    }
    const currVal_25:any = this._NgControlStatus_35_7.ngClassUntouched;
    if (import4.checkBinding(throwOnChange,this._expr_25,currVal_25)) {
      this.renderer.setElementClass(this._el_35,'ng-untouched',currVal_25);
      this._expr_25 = currVal_25;
    }
    const currVal_26:any = this._NgControlStatus_35_7.ngClassTouched;
    if (import4.checkBinding(throwOnChange,this._expr_26,currVal_26)) {
      this.renderer.setElementClass(this._el_35,'ng-touched',currVal_26);
      this._expr_26 = currVal_26;
    }
    const currVal_27:any = this._NgControlStatus_35_7.ngClassPristine;
    if (import4.checkBinding(throwOnChange,this._expr_27,currVal_27)) {
      this.renderer.setElementClass(this._el_35,'ng-pristine',currVal_27);
      this._expr_27 = currVal_27;
    }
    const currVal_28:any = this._NgControlStatus_35_7.ngClassDirty;
    if (import4.checkBinding(throwOnChange,this._expr_28,currVal_28)) {
      this.renderer.setElementClass(this._el_35,'ng-dirty',currVal_28);
      this._expr_28 = currVal_28;
    }
    const currVal_29:any = this._NgControlStatus_35_7.ngClassValid;
    if (import4.checkBinding(throwOnChange,this._expr_29,currVal_29)) {
      this.renderer.setElementClass(this._el_35,'ng-valid',currVal_29);
      this._expr_29 = currVal_29;
    }
    const currVal_30:any = this._NgControlStatus_35_7.ngClassInvalid;
    if (import4.checkBinding(throwOnChange,this._expr_30,currVal_30)) {
      this.renderer.setElementClass(this._el_35,'ng-invalid',currVal_30);
      this._expr_30 = currVal_30;
    }
    const currVal_36:any = this._NgControlStatus_43_7.ngClassUntouched;
    if (import4.checkBinding(throwOnChange,this._expr_36,currVal_36)) {
      this.renderer.setElementClass(this._el_43,'ng-untouched',currVal_36);
      this._expr_36 = currVal_36;
    }
    const currVal_37:any = this._NgControlStatus_43_7.ngClassTouched;
    if (import4.checkBinding(throwOnChange,this._expr_37,currVal_37)) {
      this.renderer.setElementClass(this._el_43,'ng-touched',currVal_37);
      this._expr_37 = currVal_37;
    }
    const currVal_38:any = this._NgControlStatus_43_7.ngClassPristine;
    if (import4.checkBinding(throwOnChange,this._expr_38,currVal_38)) {
      this.renderer.setElementClass(this._el_43,'ng-pristine',currVal_38);
      this._expr_38 = currVal_38;
    }
    const currVal_39:any = this._NgControlStatus_43_7.ngClassDirty;
    if (import4.checkBinding(throwOnChange,this._expr_39,currVal_39)) {
      this.renderer.setElementClass(this._el_43,'ng-dirty',currVal_39);
      this._expr_39 = currVal_39;
    }
    const currVal_40:any = this._NgControlStatus_43_7.ngClassValid;
    if (import4.checkBinding(throwOnChange,this._expr_40,currVal_40)) {
      this.renderer.setElementClass(this._el_43,'ng-valid',currVal_40);
      this._expr_40 = currVal_40;
    }
    const currVal_41:any = this._NgControlStatus_43_7.ngClassInvalid;
    if (import4.checkBinding(throwOnChange,this._expr_41,currVal_41)) {
      this.renderer.setElementClass(this._el_43,'ng-invalid',currVal_41);
      this._expr_41 = currVal_41;
    }
    const currVal_47:any = this._NgControlStatus_51_7.ngClassUntouched;
    if (import4.checkBinding(throwOnChange,this._expr_47,currVal_47)) {
      this.renderer.setElementClass(this._el_51,'ng-untouched',currVal_47);
      this._expr_47 = currVal_47;
    }
    const currVal_48:any = this._NgControlStatus_51_7.ngClassTouched;
    if (import4.checkBinding(throwOnChange,this._expr_48,currVal_48)) {
      this.renderer.setElementClass(this._el_51,'ng-touched',currVal_48);
      this._expr_48 = currVal_48;
    }
    const currVal_49:any = this._NgControlStatus_51_7.ngClassPristine;
    if (import4.checkBinding(throwOnChange,this._expr_49,currVal_49)) {
      this.renderer.setElementClass(this._el_51,'ng-pristine',currVal_49);
      this._expr_49 = currVal_49;
    }
    const currVal_50:any = this._NgControlStatus_51_7.ngClassDirty;
    if (import4.checkBinding(throwOnChange,this._expr_50,currVal_50)) {
      this.renderer.setElementClass(this._el_51,'ng-dirty',currVal_50);
      this._expr_50 = currVal_50;
    }
    const currVal_51:any = this._NgControlStatus_51_7.ngClassValid;
    if (import4.checkBinding(throwOnChange,this._expr_51,currVal_51)) {
      this.renderer.setElementClass(this._el_51,'ng-valid',currVal_51);
      this._expr_51 = currVal_51;
    }
    const currVal_52:any = this._NgControlStatus_51_7.ngClassInvalid;
    if (import4.checkBinding(throwOnChange,this._expr_52,currVal_52)) {
      this.renderer.setElementClass(this._el_51,'ng-invalid',currVal_52);
      this._expr_52 = currVal_52;
    }
    const currVal_53:any = (this.context.restUrl + '/auth/steam');
    if (import4.checkBinding(throwOnChange,this._expr_53,currVal_53)) {
      this.renderer.setElementProperty(this._el_55,'href',this.viewUtils.sanitizer.sanitize(import24.SecurityContext.URL,currVal_53));
      this._expr_53 = currVal_53;
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
  destroyInternal():void {
    this._NgModel_27_5.ngOnDestroy();
    this._NgModel_35_5.ngOnDestroy();
    this._NgModel_43_5.ngOnDestroy();
    this._NgModel_51_5.ngOnDestroy();
  }
  private _handle_click_8_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.context.hideRegistrationModal()) !== false);
    return (true && pd_0);
  }
  private _handle_submit_20_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._NgForm_20_3.onSubmit()) !== false);
    return (true && pd_0);
  }
  private _handle_reset_20_1($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._NgForm_20_3.onReset()) !== false);
    return (true && pd_0);
  }
  private _handle_ngModelChange_27_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>(this.context.name = $event)) !== false);
    return (true && pd_0);
  }
  private _handle_input_27_1($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._DefaultValueAccessor_27_3.onChange($event.target.value)) !== false);
    return (true && pd_0);
  }
  private _handle_blur_27_2($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._DefaultValueAccessor_27_3.onTouched()) !== false);
    return (true && pd_0);
  }
  private _handle_ngModelChange_35_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>(this.context.nickname = $event)) !== false);
    return (true && pd_0);
  }
  private _handle_input_35_1($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._DefaultValueAccessor_35_3.onChange($event.target.value)) !== false);
    return (true && pd_0);
  }
  private _handle_blur_35_2($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._DefaultValueAccessor_35_3.onTouched()) !== false);
    return (true && pd_0);
  }
  private _handle_ngModelChange_43_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>(this.context.email = $event)) !== false);
    return (true && pd_0);
  }
  private _handle_input_43_1($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._DefaultValueAccessor_43_3.onChange($event.target.value)) !== false);
    return (true && pd_0);
  }
  private _handle_blur_43_2($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._DefaultValueAccessor_43_3.onTouched()) !== false);
    return (true && pd_0);
  }
  private _handle_ngModelChange_51_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>(this.context.password = $event)) !== false);
    return (true && pd_0);
  }
  private _handle_input_51_1($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._DefaultValueAccessor_51_3.onChange($event.target.value)) !== false);
    return (true && pd_0);
  }
  private _handle_blur_51_2($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._DefaultValueAccessor_51_3.onTouched()) !== false);
    return (true && pd_0);
  }
  private _handle_click_61_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.context.hideRegistrationModal()) !== false);
    return (true && pd_0);
  }
  private _handle_click_64_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.context.onSubmit()) !== false);
    return (true && pd_0);
  }
}
export function viewFactory_RegistrationModal0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<import3.RegistrationModal> {
  if ((renderType_RegistrationModal === (null as any))) { (renderType_RegistrationModal = viewUtils.createRenderComponentType('',0,import14.ViewEncapsulation.None,styles_RegistrationModal,{})); }
  return new _View_RegistrationModal0(viewUtils,parentInjector,declarationEl);
}