/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

import * as import0 from '@angular/core/src/linker/ng_module_factory';
import * as import1 from './ApplicationModule';
import * as import2 from '@angular/common/src/common_module';
import * as import3 from '@angular/core/src/application_module';
import * as import4 from '@angular/platform-browser/src/browser';
import * as import5 from '@angular/http/src/http_module';
import * as import6 from '@angular/forms/src/directives';
import * as import7 from '@angular/forms/src/form_providers';
import * as import8 from './modals/ModalAdapterModule';
import * as import9 from '../editors/tagInput/TagInputModel';
import * as import10 from '@angular/router/src/router_module';
import * as import11 from '@ng-bootstrap/ng-bootstrap/accordion/accordion.module';
import * as import12 from '@ng-bootstrap/ng-bootstrap/alert/alert.module';
import * as import13 from '@ng-bootstrap/ng-bootstrap/buttons/radio.module';
import * as import14 from '@ng-bootstrap/ng-bootstrap/carousel/carousel.module';
import * as import15 from '@ng-bootstrap/ng-bootstrap/collapse/collapse.module';
import * as import16 from '@ng-bootstrap/ng-bootstrap/datepicker/datepicker.module';
import * as import17 from '@ng-bootstrap/ng-bootstrap/dropdown/dropdown.module';
import * as import18 from '@ng-bootstrap/ng-bootstrap/modal/modal.module';
import * as import19 from '@ng-bootstrap/ng-bootstrap/pagination/pagination.module';
import * as import20 from '@ng-bootstrap/ng-bootstrap/popover/popover.module';
import * as import21 from '@ng-bootstrap/ng-bootstrap/progressbar/progressbar.module';
import * as import22 from '@ng-bootstrap/ng-bootstrap/rating/rating.module';
import * as import23 from '@ng-bootstrap/ng-bootstrap/tabset/tabset.module';
import * as import24 from '@ng-bootstrap/ng-bootstrap/timepicker/timepicker.module';
import * as import25 from '@ng-bootstrap/ng-bootstrap/tooltip/tooltip.module';
import * as import26 from '@ng-bootstrap/ng-bootstrap/typeahead/typeahead.module';
import * as import27 from '@ng-bootstrap/ng-bootstrap/index';
import * as import28 from './pages/PagesModule';
import * as import29 from 'ng2-toastr/src/toast.module';
import * as import30 from '@angular/http/src/backends/browser_xhr';
import * as import31 from '@angular/http/src/base_response_options';
import * as import32 from '@angular/http/src/backends/xhr_backend';
import * as import33 from '@angular/http/src/base_request_options';
import * as import34 from '../services/ModalService';
import * as import35 from '../services/UserInformationService';
import * as import36 from '@angular/common/src/localization';
import * as import37 from '@angular/core/src/application_init';
import * as import38 from '@angular/core/src/testability/testability';
import * as import39 from '@angular/core/src/application_ref';
import * as import40 from '@angular/core/src/linker/compiler';
import * as import41 from '@angular/platform-browser/src/dom/events/hammer_gestures';
import * as import42 from '@angular/platform-browser/src/dom/events/event_manager';
import * as import43 from '@angular/platform-browser/src/dom/shared_styles_host';
import * as import44 from '@angular/platform-browser/src/dom/dom_renderer';
import * as import45 from '@angular/platform-browser/src/security/dom_sanitization_service';
import * as import46 from '@angular/core/src/linker/view_utils';
import * as import47 from '@angular/platform-browser/src/browser/title';
import * as import48 from '@angular/forms/src/directives/radio_control_value_accessor';
import * as import49 from '@angular/forms/src/form_builder';
import * as import50 from '@ng-bootstrap/ng-bootstrap/modal/modal-stack';
import * as import51 from '@ng-bootstrap/ng-bootstrap/modal/modal';
import * as import52 from '@angular/common/src/location/location';
import * as import53 from '@angular/router/src/url_tree';
import * as import54 from '@angular/router/src/router_outlet_map';
import * as import55 from '@angular/core/src/linker/system_js_ng_module_factory_loader';
import * as import56 from 'ng2-toastr/src/toast-manager';
import * as import57 from '../services/SocketService';
import * as import58 from '../services/NewsService';
import * as import59 from '../services/LocalStorageService';
import * as import60 from '../services/LocalizationService';
import * as import61 from '../services/TeamService';
import * as import62 from '@ng-bootstrap/ng-bootstrap/alert/alert-config';
import * as import63 from '@ng-bootstrap/ng-bootstrap/progressbar/progressbar-config';
import * as import64 from '@ng-bootstrap/ng-bootstrap/tooltip/tooltip-config';
import * as import65 from '@ng-bootstrap/ng-bootstrap/typeahead/typeahead-config';
import * as import66 from '@ng-bootstrap/ng-bootstrap/accordion/accordion-config';
import * as import67 from '@ng-bootstrap/ng-bootstrap/carousel/carousel-config';
import * as import68 from '@ng-bootstrap/ng-bootstrap/datepicker/ngb-calendar';
import * as import69 from '@ng-bootstrap/ng-bootstrap/datepicker/datepicker-i18n';
import * as import70 from '@ng-bootstrap/ng-bootstrap/datepicker/ngb-date-parser-formatter';
import * as import71 from '@ng-bootstrap/ng-bootstrap/datepicker/datepicker-service';
import * as import72 from '@ng-bootstrap/ng-bootstrap/datepicker/datepicker-config';
import * as import73 from '@ng-bootstrap/ng-bootstrap/dropdown/dropdown-config';
import * as import74 from '@ng-bootstrap/ng-bootstrap/pagination/pagination-config';
import * as import75 from '@ng-bootstrap/ng-bootstrap/popover/popover-config';
import * as import76 from '@ng-bootstrap/ng-bootstrap/rating/rating-config';
import * as import77 from '@ng-bootstrap/ng-bootstrap/tabset/tabset-config';
import * as import78 from '@ng-bootstrap/ng-bootstrap/timepicker/timepicker-config';
import * as import79 from '../services/ModeService';
import * as import80 from '../services/SettingsService';
import * as import81 from '../services/AuthService';
import * as import82 from '../services/UserFriendsService';
import * as import83 from '../services/UserNotificationsService';
import * as import84 from '../services/NavigatorService';
import * as import85 from '../services/FileUploadService';
import * as import86 from '@angular/core/src/di/injector';
import * as import87 from '../../../node_modules/@ng-bootstrap/ng-bootstrap/alert/alert.ngfactory';
import * as import88 from '../../../node_modules/@ng-bootstrap/ng-bootstrap/datepicker/datepicker.ngfactory';
import * as import89 from '../../../node_modules/@ng-bootstrap/ng-bootstrap/modal/modal-backdrop.ngfactory';
import * as import90 from '../../../node_modules/@ng-bootstrap/ng-bootstrap/modal/modal-window.ngfactory';
import * as import91 from '../../../node_modules/@ng-bootstrap/ng-bootstrap/popover/popover.ngfactory';
import * as import92 from '../../../node_modules/@ng-bootstrap/ng-bootstrap/tooltip/tooltip.ngfactory';
import * as import93 from '../../../node_modules/@ng-bootstrap/ng-bootstrap/typeahead/typeahead-window.ngfactory';
import * as import94 from './pages/news/News.ngfactory';
import * as import95 from './pages/search/Search.ngfactory';
import * as import96 from './pages/singleNews/SingleNews.ngfactory';
import * as import97 from './pages/userSettings/UserSettings.ngfactory';
import * as import98 from './pages/confirmEmail/ConfirmEmail.ngfactory';
import * as import99 from './pages/confirmDataChange/ConfirmDataChange.ngfactory';
import * as import100 from './pages/userNotifications/UserNotifications.ngfactory';
import * as import101 from './pages/user/UserPage.ngfactory';
import * as import102 from '../../../node_modules/ng2-toastr/src/toast-container.component.ngfactory';
import * as import103 from './Application.ngfactory';
import * as import104 from '@angular/core/src/application_tokens';
import * as import105 from '@angular/platform-browser/src/dom/events/dom_events';
import * as import106 from '@angular/platform-browser/src/dom/events/key_events';
import * as import107 from '@angular/core/src/zone/ng_zone';
import * as import108 from '@angular/platform-browser/src/dom/debug/ng_probe';
import * as import109 from '@angular/common/src/location/platform_location';
import * as import110 from '@angular/common/src/location/location_strategy';
import * as import111 from './pages/news/News';
import * as import112 from './pages/search/Search';
import * as import113 from './pages/singleNews/SingleNews';
import * as import114 from './pages/userSettings/UserSettings';
import * as import115 from './pages/confirmEmail/ConfirmEmail';
import * as import116 from './pages/confirmDataChange/ConfirmDataChange';
import * as import117 from './pages/userNotifications/UserNotifications';
import * as import118 from './pages/user/UserPage';
import * as import119 from 'ng2-toastr/src/toast-options';
import * as import120 from '@angular/router/src/router';
import * as import121 from '@angular/core/src/console';
import * as import122 from '@angular/http/src/interfaces';
import * as import123 from '@angular/http/src/http';
import * as import124 from '@angular/core/src/i18n/tokens';
import * as import125 from '@angular/core/src/error_handler';
import * as import126 from '@angular/platform-browser/src/dom/dom_tokens';
import * as import127 from '@angular/platform-browser/src/dom/animation_driver';
import * as import128 from '@angular/core/src/render/api';
import * as import129 from '@angular/core/src/security';
import * as import130 from '@angular/core/src/change_detection/differs/iterable_differs';
import * as import131 from '@angular/core/src/change_detection/differs/keyvalue_differs';
import * as import132 from '@angular/core/src/linker/ng_module_factory_loader';
import * as import133 from '@angular/router/src/router_config_loader';
import * as import134 from '@angular/router/src/router_state';
class ApplicationModuleInjector extends import0.NgModuleInjector<import1.ApplicationModule> {
  _CommonModule_0:import2.CommonModule;
  _ApplicationModule_1:import3.ApplicationModule;
  _BrowserModule_2:import4.BrowserModule;
  _HttpModule_3:import5.HttpModule;
  _InternalFormsSharedModule_4:import6.InternalFormsSharedModule;
  _FormsModule_5:import7.FormsModule;
  _ModalAdapterModule_6:import8.ModalAdapterModule;
  _ReactiveFormsModule_7:import7.ReactiveFormsModule;
  _RlTagInputModule_8:import9.RlTagInputModule;
  _ROUTER_FORROOT_GUARD_9:any;
  _RouterModule_10:import10.RouterModule;
  _NgbAccordionModule_11:import11.NgbAccordionModule;
  _NgbAlertModule_12:import12.NgbAlertModule;
  _NgbButtonsModule_13:import13.NgbButtonsModule;
  _NgbCarouselModule_14:import14.NgbCarouselModule;
  _NgbCollapseModule_15:import15.NgbCollapseModule;
  _NgbDatepickerModule_16:import16.NgbDatepickerModule;
  _NgbDropdownModule_17:import17.NgbDropdownModule;
  _NgbModalModule_18:import18.NgbModalModule;
  _NgbPaginationModule_19:import19.NgbPaginationModule;
  _NgbPopoverModule_20:import20.NgbPopoverModule;
  _NgbProgressbarModule_21:import21.NgbProgressbarModule;
  _NgbRatingModule_22:import22.NgbRatingModule;
  _NgbTabsetModule_23:import23.NgbTabsetModule;
  _NgbTimepickerModule_24:import24.NgbTimepickerModule;
  _NgbTooltipModule_25:import25.NgbTooltipModule;
  _NgbTypeaheadModule_26:import26.NgbTypeaheadModule;
  _NgbModule_27:import27.NgbModule;
  _PagesModule_28:import28.PagesModule;
  _ToastModule_29:import29.ToastModule;
  _NgbRootModule_30:import27.NgbRootModule;
  _BrowserXhr_31:import30.BrowserXhr;
  _ResponseOptions_32:import31.BaseResponseOptions;
  _XSRFStrategy_33:any;
  _XHRBackend_34:import32.XHRBackend;
  _RequestOptions_35:import33.BaseRequestOptions;
  _Http_36:any;
  _ModalService_37:import34.ModalService;
  _UserInformationService_38:import35.UserInformationService;
  _ApplicationModule_39:import1.ApplicationModule;
  __LOCALE_ID_40:any;
  __NgLocalization_41:import36.NgLocaleLocalization;
  _ErrorHandler_42:any;
  _ApplicationInitStatus_43:import37.ApplicationInitStatus;
  _Testability_44:import38.Testability;
  _ApplicationRef__45:import39.ApplicationRef_;
  __ApplicationRef_46:any;
  __Compiler_47:import40.Compiler;
  __APP_ID_48:any;
  __DOCUMENT_49:any;
  __HAMMER_GESTURE_CONFIG_50:import41.HammerGestureConfig;
  __EVENT_MANAGER_PLUGINS_51:any[];
  __EventManager_52:import42.EventManager;
  __DomSharedStylesHost_53:import43.DomSharedStylesHost;
  __AnimationDriver_54:any;
  __DomRootRenderer_55:import44.DomRootRenderer_;
  __RootRenderer_56:any;
  __DomSanitizer_57:import45.DomSanitizerImpl;
  __Sanitizer_58:any;
  __ViewUtils_59:import46.ViewUtils;
  __IterableDiffers_60:any;
  __KeyValueDiffers_61:any;
  __SharedStylesHost_62:any;
  __Title_63:import47.Title;
  __RadioControlRegistry_64:import48.RadioControlRegistry;
  __FormBuilder_65:import49.FormBuilder;
  __NgbModalStack_66:import50.NgbModalStack;
  __NgbModal_67:import51.NgbModal;
  __ROUTER_CONFIGURATION_68:any;
  __LocationStrategy_69:any;
  __Location_70:import52.Location;
  __UrlSerializer_71:import53.DefaultUrlSerializer;
  __RouterOutletMap_72:import54.RouterOutletMap;
  __NgModuleFactoryLoader_73:import55.SystemJsNgModuleLoader;
  __ROUTES_74:any[];
  __Router_75:any;
  __ActivatedRoute_76:any;
  __APP_BOOTSTRAP_LISTENER_77:any[];
  __ToastsManager_78:import56.ToastsManager;
  __SocketService_79:import57.SocketService;
  __NewsService_80:import58.NewsService;
  __LocalStorageService_81:import59.LocalStorageService;
  __LocalizationService_82:import60.LocalizationService;
  __TeamService_83:import61.TeamService;
  __NgbAlertConfig_84:import62.NgbAlertConfig;
  __NgbProgressbarConfig_85:import63.NgbProgressbarConfig;
  __NgbTooltipConfig_86:import64.NgbTooltipConfig;
  __NgbTypeaheadConfig_87:import65.NgbTypeaheadConfig;
  __NgbAccordionConfig_88:import66.NgbAccordionConfig;
  __NgbCarouselConfig_89:import67.NgbCarouselConfig;
  __NgbCalendar_90:import68.NgbCalendarGregorian;
  __NgbDatepickerI18n_91:import69.NgbDatepickerI18nDefault;
  __NgbDateParserFormatter_92:import70.NgbDateISOParserFormatter;
  __NgbDatepickerService_93:import71.NgbDatepickerService;
  __NgbDatepickerConfig_94:import72.NgbDatepickerConfig;
  __NgbDropdownConfig_95:import73.NgbDropdownConfig;
  __NgbPaginationConfig_96:import74.NgbPaginationConfig;
  __NgbPopoverConfig_97:import75.NgbPopoverConfig;
  __NgbRatingConfig_98:import76.NgbRatingConfig;
  __NgbTabsetConfig_99:import77.NgbTabsetConfig;
  __NgbTimepickerConfig_100:import78.NgbTimepickerConfig;
  __ModeService_101:import79.ModeService;
  __SettingsService_102:import80.SettingsService;
  __AuthService_103:import81.AuthService;
  __UserFriendsService_104:import82.UserFriendsService;
  __UserNotificationsService_105:import83.UserNotificationsService;
  __NavigatorService_106:import84.NavigatorService;
  __FileUploadService_107:import85.FileUploadService;
  constructor(parent:import86.Injector) {
    super(parent,[
      import87.NgbAlertNgFactory,
      import88.NgbDatepickerNgFactory,
      import89.NgbModalBackdropNgFactory,
      import90.NgbModalWindowNgFactory,
      import91.NgbPopoverWindowNgFactory,
      import92.NgbTooltipWindowNgFactory,
      import93.NgbTypeaheadWindowNgFactory,
      import94.NewsNgFactory,
      import95.SearchNgFactory,
      import96.SingleNewsNgFactory,
      import97.UserSettingsNgFactory,
      import98.ConfirmEmailNgFactory,
      import99.ConfirmDataChangeNgFactory,
      import100.UserNotificationsNgFactory,
      import101.UserPageNgFactory,
      import102.ToastContainerNgFactory,
      import103.ApplicationNgFactory
    ]
    ,[import103.ApplicationNgFactory]);
  }
  get _LOCALE_ID_40():any {
    if ((this.__LOCALE_ID_40 == (null as any))) { (this.__LOCALE_ID_40 = 'en-US'); }
    return this.__LOCALE_ID_40;
  }
  get _NgLocalization_41():import36.NgLocaleLocalization {
    if ((this.__NgLocalization_41 == (null as any))) { (this.__NgLocalization_41 = new import36.NgLocaleLocalization(this._LOCALE_ID_40)); }
    return this.__NgLocalization_41;
  }
  get _ApplicationRef_46():any {
    if ((this.__ApplicationRef_46 == (null as any))) { (this.__ApplicationRef_46 = this._ApplicationRef__45); }
    return this.__ApplicationRef_46;
  }
  get _Compiler_47():import40.Compiler {
    if ((this.__Compiler_47 == (null as any))) { (this.__Compiler_47 = new import40.Compiler()); }
    return this.__Compiler_47;
  }
  get _APP_ID_48():any {
    if ((this.__APP_ID_48 == (null as any))) { (this.__APP_ID_48 = import104._appIdRandomProviderFactory()); }
    return this.__APP_ID_48;
  }
  get _DOCUMENT_49():any {
    if ((this.__DOCUMENT_49 == (null as any))) { (this.__DOCUMENT_49 = import4._document()); }
    return this.__DOCUMENT_49;
  }
  get _HAMMER_GESTURE_CONFIG_50():import41.HammerGestureConfig {
    if ((this.__HAMMER_GESTURE_CONFIG_50 == (null as any))) { (this.__HAMMER_GESTURE_CONFIG_50 = new import41.HammerGestureConfig()); }
    return this.__HAMMER_GESTURE_CONFIG_50;
  }
  get _EVENT_MANAGER_PLUGINS_51():any[] {
    if ((this.__EVENT_MANAGER_PLUGINS_51 == (null as any))) { (this.__EVENT_MANAGER_PLUGINS_51 = [
      new import105.DomEventsPlugin(),
      new import106.KeyEventsPlugin(),
      new import41.HammerGesturesPlugin(this._HAMMER_GESTURE_CONFIG_50)
    ]
    ); }
    return this.__EVENT_MANAGER_PLUGINS_51;
  }
  get _EventManager_52():import42.EventManager {
    if ((this.__EventManager_52 == (null as any))) { (this.__EventManager_52 = new import42.EventManager(this._EVENT_MANAGER_PLUGINS_51,this.parent.get(import107.NgZone))); }
    return this.__EventManager_52;
  }
  get _DomSharedStylesHost_53():import43.DomSharedStylesHost {
    if ((this.__DomSharedStylesHost_53 == (null as any))) { (this.__DomSharedStylesHost_53 = new import43.DomSharedStylesHost(this._DOCUMENT_49)); }
    return this.__DomSharedStylesHost_53;
  }
  get _AnimationDriver_54():any {
    if ((this.__AnimationDriver_54 == (null as any))) { (this.__AnimationDriver_54 = import4._resolveDefaultAnimationDriver()); }
    return this.__AnimationDriver_54;
  }
  get _DomRootRenderer_55():import44.DomRootRenderer_ {
    if ((this.__DomRootRenderer_55 == (null as any))) { (this.__DomRootRenderer_55 = new import44.DomRootRenderer_(this._DOCUMENT_49,this._EventManager_52,this._DomSharedStylesHost_53,this._AnimationDriver_54)); }
    return this.__DomRootRenderer_55;
  }
  get _RootRenderer_56():any {
    if ((this.__RootRenderer_56 == (null as any))) { (this.__RootRenderer_56 = import108._createConditionalRootRenderer(this._DomRootRenderer_55,this.parent.get(import108.NgProbeToken,(null as any)))); }
    return this.__RootRenderer_56;
  }
  get _DomSanitizer_57():import45.DomSanitizerImpl {
    if ((this.__DomSanitizer_57 == (null as any))) { (this.__DomSanitizer_57 = new import45.DomSanitizerImpl()); }
    return this.__DomSanitizer_57;
  }
  get _Sanitizer_58():any {
    if ((this.__Sanitizer_58 == (null as any))) { (this.__Sanitizer_58 = this._DomSanitizer_57); }
    return this.__Sanitizer_58;
  }
  get _ViewUtils_59():import46.ViewUtils {
    if ((this.__ViewUtils_59 == (null as any))) { (this.__ViewUtils_59 = new import46.ViewUtils(this._RootRenderer_56,this._APP_ID_48,this._Sanitizer_58)); }
    return this.__ViewUtils_59;
  }
  get _IterableDiffers_60():any {
    if ((this.__IterableDiffers_60 == (null as any))) { (this.__IterableDiffers_60 = import3._iterableDiffersFactory()); }
    return this.__IterableDiffers_60;
  }
  get _KeyValueDiffers_61():any {
    if ((this.__KeyValueDiffers_61 == (null as any))) { (this.__KeyValueDiffers_61 = import3._keyValueDiffersFactory()); }
    return this.__KeyValueDiffers_61;
  }
  get _SharedStylesHost_62():any {
    if ((this.__SharedStylesHost_62 == (null as any))) { (this.__SharedStylesHost_62 = this._DomSharedStylesHost_53); }
    return this.__SharedStylesHost_62;
  }
  get _Title_63():import47.Title {
    if ((this.__Title_63 == (null as any))) { (this.__Title_63 = new import47.Title()); }
    return this.__Title_63;
  }
  get _RadioControlRegistry_64():import48.RadioControlRegistry {
    if ((this.__RadioControlRegistry_64 == (null as any))) { (this.__RadioControlRegistry_64 = new import48.RadioControlRegistry()); }
    return this.__RadioControlRegistry_64;
  }
  get _FormBuilder_65():import49.FormBuilder {
    if ((this.__FormBuilder_65 == (null as any))) { (this.__FormBuilder_65 = new import49.FormBuilder()); }
    return this.__FormBuilder_65;
  }
  get _NgbModalStack_66():import50.NgbModalStack {
    if ((this.__NgbModalStack_66 == (null as any))) { (this.__NgbModalStack_66 = new import50.NgbModalStack()); }
    return this.__NgbModalStack_66;
  }
  get _NgbModal_67():import51.NgbModal {
    if ((this.__NgbModal_67 == (null as any))) { (this.__NgbModal_67 = new import51.NgbModal(this,this,this._NgbModalStack_66)); }
    return this.__NgbModal_67;
  }
  get _ROUTER_CONFIGURATION_68():any {
    if ((this.__ROUTER_CONFIGURATION_68 == (null as any))) { (this.__ROUTER_CONFIGURATION_68 = {}); }
    return this.__ROUTER_CONFIGURATION_68;
  }
  get _LocationStrategy_69():any {
    if ((this.__LocationStrategy_69 == (null as any))) { (this.__LocationStrategy_69 = import10.provideLocationStrategy(this.parent.get(import109.PlatformLocation),this.parent.get(import110.APP_BASE_HREF,(null as any)),this._ROUTER_CONFIGURATION_68)); }
    return this.__LocationStrategy_69;
  }
  get _Location_70():import52.Location {
    if ((this.__Location_70 == (null as any))) { (this.__Location_70 = new import52.Location(this._LocationStrategy_69)); }
    return this.__Location_70;
  }
  get _UrlSerializer_71():import53.DefaultUrlSerializer {
    if ((this.__UrlSerializer_71 == (null as any))) { (this.__UrlSerializer_71 = new import53.DefaultUrlSerializer()); }
    return this.__UrlSerializer_71;
  }
  get _RouterOutletMap_72():import54.RouterOutletMap {
    if ((this.__RouterOutletMap_72 == (null as any))) { (this.__RouterOutletMap_72 = new import54.RouterOutletMap()); }
    return this.__RouterOutletMap_72;
  }
  get _NgModuleFactoryLoader_73():import55.SystemJsNgModuleLoader {
    if ((this.__NgModuleFactoryLoader_73 == (null as any))) { (this.__NgModuleFactoryLoader_73 = new import55.SystemJsNgModuleLoader(this._Compiler_47,this.parent.get(import55.SystemJsNgModuleLoaderConfig,(null as any)))); }
    return this.__NgModuleFactoryLoader_73;
  }
  get _ROUTES_74():any[] {
      if ((this.__ROUTES_74 == (null as any))) { (this.__ROUTES_74 = [[
        {
          path: '',
          component: import111.News,
          useAsDefault: true
        }
        ,
        {
          path: ':id',
          name: 'search',
          component: import112.Search
        }
        ,
        {
          path: 'news/:id',
          component: import113.SingleNews
        }
        ,
        {
          path: 'user/settings',
          component: import114.UserSettings
        }
        ,
        {
          path: 'email-confirm',
          component: import115.ConfirmEmail
        }
        ,
        {
          path: 'data-confirm',
          component: import116.ConfirmDataChange
        }
        ,
        {
          path: 'user/notifications',
          component: import117.UserNotifications
        }
        ,
        {
          path: 'user/:id',
          component: import118.UserPage
        }

      ]
    ]); }
    return this.__ROUTES_74;
  }
  get _Router_75():any {
    if ((this.__Router_75 == (null as any))) { (this.__Router_75 = import10.setupRouter(this._ApplicationRef_46,this._UrlSerializer_71,this._RouterOutletMap_72,this._Location_70,this,this._NgModuleFactoryLoader_73,this._Compiler_47,this._ROUTES_74,this._ROUTER_CONFIGURATION_68)); }
    return this.__Router_75;
  }
  get _ActivatedRoute_76():any {
    if ((this.__ActivatedRoute_76 == (null as any))) { (this.__ActivatedRoute_76 = import10.rootRoute(this._Router_75)); }
    return this.__ActivatedRoute_76;
  }
  get _APP_BOOTSTRAP_LISTENER_77():any[] {
    if ((this.__APP_BOOTSTRAP_LISTENER_77 == (null as any))) { (this.__APP_BOOTSTRAP_LISTENER_77 = [import10.initialRouterNavigation(this._Router_75,this._ROUTER_CONFIGURATION_68)]); }
    return this.__APP_BOOTSTRAP_LISTENER_77;
  }
  get _ToastsManager_78():import56.ToastsManager {
    if ((this.__ToastsManager_78 == (null as any))) { (this.__ToastsManager_78 = new import56.ToastsManager(this,this._ApplicationRef_46,this.parent.get(import119.ToastOptions,(null as any)))); }
    return this.__ToastsManager_78;
  }
  get _SocketService_79():import57.SocketService {
    if ((this.__SocketService_79 == (null as any))) { (this.__SocketService_79 = new import57.SocketService()); }
    return this.__SocketService_79;
  }
  get _NewsService_80():import58.NewsService {
    if ((this.__NewsService_80 == (null as any))) { (this.__NewsService_80 = new import58.NewsService(this._ToastsManager_78,this._Http_36,this._SocketService_79)); }
    return this.__NewsService_80;
  }
  get _LocalStorageService_81():import59.LocalStorageService {
    if ((this.__LocalStorageService_81 == (null as any))) { (this.__LocalStorageService_81 = new import59.LocalStorageService()); }
    return this.__LocalStorageService_81;
  }
  get _LocalizationService_82():import60.LocalizationService {
    if ((this.__LocalizationService_82 == (null as any))) { (this.__LocalizationService_82 = new import60.LocalizationService(this._Http_36,this._LocalStorageService_81)); }
    return this.__LocalizationService_82;
  }
  get _TeamService_83():import61.TeamService {
    if ((this.__TeamService_83 == (null as any))) { (this.__TeamService_83 = new import61.TeamService(this._Http_36,this._ToastsManager_78,this._UserInformationService_38,this._LocalizationService_82)); }
    return this.__TeamService_83;
  }
  get _NgbAlertConfig_84():import62.NgbAlertConfig {
    if ((this.__NgbAlertConfig_84 == (null as any))) { (this.__NgbAlertConfig_84 = new import62.NgbAlertConfig()); }
    return this.__NgbAlertConfig_84;
  }
  get _NgbProgressbarConfig_85():import63.NgbProgressbarConfig {
    if ((this.__NgbProgressbarConfig_85 == (null as any))) { (this.__NgbProgressbarConfig_85 = new import63.NgbProgressbarConfig()); }
    return this.__NgbProgressbarConfig_85;
  }
  get _NgbTooltipConfig_86():import64.NgbTooltipConfig {
    if ((this.__NgbTooltipConfig_86 == (null as any))) { (this.__NgbTooltipConfig_86 = new import64.NgbTooltipConfig()); }
    return this.__NgbTooltipConfig_86;
  }
  get _NgbTypeaheadConfig_87():import65.NgbTypeaheadConfig {
    if ((this.__NgbTypeaheadConfig_87 == (null as any))) { (this.__NgbTypeaheadConfig_87 = new import65.NgbTypeaheadConfig()); }
    return this.__NgbTypeaheadConfig_87;
  }
  get _NgbAccordionConfig_88():import66.NgbAccordionConfig {
    if ((this.__NgbAccordionConfig_88 == (null as any))) { (this.__NgbAccordionConfig_88 = new import66.NgbAccordionConfig()); }
    return this.__NgbAccordionConfig_88;
  }
  get _NgbCarouselConfig_89():import67.NgbCarouselConfig {
    if ((this.__NgbCarouselConfig_89 == (null as any))) { (this.__NgbCarouselConfig_89 = new import67.NgbCarouselConfig()); }
    return this.__NgbCarouselConfig_89;
  }
  get _NgbCalendar_90():import68.NgbCalendarGregorian {
    if ((this.__NgbCalendar_90 == (null as any))) { (this.__NgbCalendar_90 = new import68.NgbCalendarGregorian()); }
    return this.__NgbCalendar_90;
  }
  get _NgbDatepickerI18n_91():import69.NgbDatepickerI18nDefault {
    if ((this.__NgbDatepickerI18n_91 == (null as any))) { (this.__NgbDatepickerI18n_91 = new import69.NgbDatepickerI18nDefault()); }
    return this.__NgbDatepickerI18n_91;
  }
  get _NgbDateParserFormatter_92():import70.NgbDateISOParserFormatter {
    if ((this.__NgbDateParserFormatter_92 == (null as any))) { (this.__NgbDateParserFormatter_92 = new import70.NgbDateISOParserFormatter()); }
    return this.__NgbDateParserFormatter_92;
  }
  get _NgbDatepickerService_93():import71.NgbDatepickerService {
    if ((this.__NgbDatepickerService_93 == (null as any))) { (this.__NgbDatepickerService_93 = new import71.NgbDatepickerService(this._NgbCalendar_90)); }
    return this.__NgbDatepickerService_93;
  }
  get _NgbDatepickerConfig_94():import72.NgbDatepickerConfig {
    if ((this.__NgbDatepickerConfig_94 == (null as any))) { (this.__NgbDatepickerConfig_94 = new import72.NgbDatepickerConfig()); }
    return this.__NgbDatepickerConfig_94;
  }
  get _NgbDropdownConfig_95():import73.NgbDropdownConfig {
    if ((this.__NgbDropdownConfig_95 == (null as any))) { (this.__NgbDropdownConfig_95 = new import73.NgbDropdownConfig()); }
    return this.__NgbDropdownConfig_95;
  }
  get _NgbPaginationConfig_96():import74.NgbPaginationConfig {
    if ((this.__NgbPaginationConfig_96 == (null as any))) { (this.__NgbPaginationConfig_96 = new import74.NgbPaginationConfig()); }
    return this.__NgbPaginationConfig_96;
  }
  get _NgbPopoverConfig_97():import75.NgbPopoverConfig {
    if ((this.__NgbPopoverConfig_97 == (null as any))) { (this.__NgbPopoverConfig_97 = new import75.NgbPopoverConfig()); }
    return this.__NgbPopoverConfig_97;
  }
  get _NgbRatingConfig_98():import76.NgbRatingConfig {
    if ((this.__NgbRatingConfig_98 == (null as any))) { (this.__NgbRatingConfig_98 = new import76.NgbRatingConfig()); }
    return this.__NgbRatingConfig_98;
  }
  get _NgbTabsetConfig_99():import77.NgbTabsetConfig {
    if ((this.__NgbTabsetConfig_99 == (null as any))) { (this.__NgbTabsetConfig_99 = new import77.NgbTabsetConfig()); }
    return this.__NgbTabsetConfig_99;
  }
  get _NgbTimepickerConfig_100():import78.NgbTimepickerConfig {
    if ((this.__NgbTimepickerConfig_100 == (null as any))) { (this.__NgbTimepickerConfig_100 = new import78.NgbTimepickerConfig()); }
    return this.__NgbTimepickerConfig_100;
  }
  get _ModeService_101():import79.ModeService {
    if ((this.__ModeService_101 == (null as any))) { (this.__ModeService_101 = new import79.ModeService()); }
    return this.__ModeService_101;
  }
  get _SettingsService_102():import80.SettingsService {
    if ((this.__SettingsService_102 == (null as any))) { (this.__SettingsService_102 = new import80.SettingsService()); }
    return this.__SettingsService_102;
  }
  get _AuthService_103():import81.AuthService {
    if ((this.__AuthService_103 == (null as any))) { (this.__AuthService_103 = new import81.AuthService(this._Http_36)); }
    return this.__AuthService_103;
  }
  get _UserFriendsService_104():import82.UserFriendsService {
    if ((this.__UserFriendsService_104 == (null as any))) { (this.__UserFriendsService_104 = new import82.UserFriendsService(this._Http_36)); }
    return this.__UserFriendsService_104;
  }
  get _UserNotificationsService_105():import83.UserNotificationsService {
    if ((this.__UserNotificationsService_105 == (null as any))) { (this.__UserNotificationsService_105 = new import83.UserNotificationsService(this._Http_36)); }
    return this.__UserNotificationsService_105;
  }
  get _NavigatorService_106():import84.NavigatorService {
    if ((this.__NavigatorService_106 == (null as any))) { (this.__NavigatorService_106 = new import84.NavigatorService(this._Router_75)); }
    return this.__NavigatorService_106;
  }
  get _FileUploadService_107():import85.FileUploadService {
    if ((this.__FileUploadService_107 == (null as any))) { (this.__FileUploadService_107 = new import85.FileUploadService()); }
    return this.__FileUploadService_107;
  }
  createInternal():import1.ApplicationModule {
    this._CommonModule_0 = new import2.CommonModule();
    this._ApplicationModule_1 = new import3.ApplicationModule();
    this._BrowserModule_2 = new import4.BrowserModule(this.parent.get(import4.BrowserModule,(null as any)));
    this._HttpModule_3 = new import5.HttpModule();
    this._InternalFormsSharedModule_4 = new import6.InternalFormsSharedModule();
    this._FormsModule_5 = new import7.FormsModule();
    this._ModalAdapterModule_6 = new import8.ModalAdapterModule();
    this._ReactiveFormsModule_7 = new import7.ReactiveFormsModule();
    this._RlTagInputModule_8 = new import9.RlTagInputModule();
    this._ROUTER_FORROOT_GUARD_9 = import10.provideForRootGuard(this.parent.get(import120.Router,(null as any)));
    this._RouterModule_10 = new import10.RouterModule(this._ROUTER_FORROOT_GUARD_9);
    this._NgbAccordionModule_11 = new import11.NgbAccordionModule();
    this._NgbAlertModule_12 = new import12.NgbAlertModule();
    this._NgbButtonsModule_13 = new import13.NgbButtonsModule();
    this._NgbCarouselModule_14 = new import14.NgbCarouselModule();
    this._NgbCollapseModule_15 = new import15.NgbCollapseModule();
    this._NgbDatepickerModule_16 = new import16.NgbDatepickerModule();
    this._NgbDropdownModule_17 = new import17.NgbDropdownModule();
    this._NgbModalModule_18 = new import18.NgbModalModule();
    this._NgbPaginationModule_19 = new import19.NgbPaginationModule();
    this._NgbPopoverModule_20 = new import20.NgbPopoverModule();
    this._NgbProgressbarModule_21 = new import21.NgbProgressbarModule();
    this._NgbRatingModule_22 = new import22.NgbRatingModule();
    this._NgbTabsetModule_23 = new import23.NgbTabsetModule();
    this._NgbTimepickerModule_24 = new import24.NgbTimepickerModule();
    this._NgbTooltipModule_25 = new import25.NgbTooltipModule();
    this._NgbTypeaheadModule_26 = new import26.NgbTypeaheadModule();
    this._NgbModule_27 = new import27.NgbModule();
    this._PagesModule_28 = new import28.PagesModule();
    this._ToastModule_29 = new import29.ToastModule();
    this._NgbRootModule_30 = new import27.NgbRootModule();
    this._BrowserXhr_31 = new import30.BrowserXhr();
    this._ResponseOptions_32 = new import31.BaseResponseOptions();
    this._XSRFStrategy_33 = import5._createDefaultCookieXSRFStrategy();
    this._XHRBackend_34 = new import32.XHRBackend(this._BrowserXhr_31,this._ResponseOptions_32,this._XSRFStrategy_33);
    this._RequestOptions_35 = new import33.BaseRequestOptions();
    this._Http_36 = import5.httpFactory(this._XHRBackend_34,this._RequestOptions_35);
    this._ModalService_37 = new import34.ModalService();
    this._UserInformationService_38 = new import35.UserInformationService(this._Http_36,this._ModalService_37);
    this._ApplicationModule_39 = new import1.ApplicationModule(this._UserInformationService_38);
    this._ErrorHandler_42 = import4.errorHandler();
    this._ApplicationInitStatus_43 = new import37.ApplicationInitStatus(this.parent.get(import37.APP_INITIALIZER,(null as any)));
    this._Testability_44 = new import38.Testability(this.parent.get(import107.NgZone));
    this._ApplicationRef__45 = new import39.ApplicationRef_(this.parent.get(import107.NgZone),this.parent.get(import121.Console),this,this._ErrorHandler_42,this,this._ApplicationInitStatus_43,this.parent.get(import38.TestabilityRegistry,(null as any)),this._Testability_44);
    return this._ApplicationModule_39;
  }
  getInternal(token:any,notFoundResult:any):any {
    if ((token === import2.CommonModule)) { return this._CommonModule_0; }
    if ((token === import3.ApplicationModule)) { return this._ApplicationModule_1; }
    if ((token === import4.BrowserModule)) { return this._BrowserModule_2; }
    if ((token === import5.HttpModule)) { return this._HttpModule_3; }
    if ((token === import6.InternalFormsSharedModule)) { return this._InternalFormsSharedModule_4; }
    if ((token === import7.FormsModule)) { return this._FormsModule_5; }
    if ((token === import8.ModalAdapterModule)) { return this._ModalAdapterModule_6; }
    if ((token === import7.ReactiveFormsModule)) { return this._ReactiveFormsModule_7; }
    if ((token === import9.RlTagInputModule)) { return this._RlTagInputModule_8; }
    if ((token === import10.ROUTER_FORROOT_GUARD)) { return this._ROUTER_FORROOT_GUARD_9; }
    if ((token === import10.RouterModule)) { return this._RouterModule_10; }
    if ((token === import11.NgbAccordionModule)) { return this._NgbAccordionModule_11; }
    if ((token === import12.NgbAlertModule)) { return this._NgbAlertModule_12; }
    if ((token === import13.NgbButtonsModule)) { return this._NgbButtonsModule_13; }
    if ((token === import14.NgbCarouselModule)) { return this._NgbCarouselModule_14; }
    if ((token === import15.NgbCollapseModule)) { return this._NgbCollapseModule_15; }
    if ((token === import16.NgbDatepickerModule)) { return this._NgbDatepickerModule_16; }
    if ((token === import17.NgbDropdownModule)) { return this._NgbDropdownModule_17; }
    if ((token === import18.NgbModalModule)) { return this._NgbModalModule_18; }
    if ((token === import19.NgbPaginationModule)) { return this._NgbPaginationModule_19; }
    if ((token === import20.NgbPopoverModule)) { return this._NgbPopoverModule_20; }
    if ((token === import21.NgbProgressbarModule)) { return this._NgbProgressbarModule_21; }
    if ((token === import22.NgbRatingModule)) { return this._NgbRatingModule_22; }
    if ((token === import23.NgbTabsetModule)) { return this._NgbTabsetModule_23; }
    if ((token === import24.NgbTimepickerModule)) { return this._NgbTimepickerModule_24; }
    if ((token === import25.NgbTooltipModule)) { return this._NgbTooltipModule_25; }
    if ((token === import26.NgbTypeaheadModule)) { return this._NgbTypeaheadModule_26; }
    if ((token === import27.NgbModule)) { return this._NgbModule_27; }
    if ((token === import28.PagesModule)) { return this._PagesModule_28; }
    if ((token === import29.ToastModule)) { return this._ToastModule_29; }
    if ((token === import27.NgbRootModule)) { return this._NgbRootModule_30; }
    if ((token === import30.BrowserXhr)) { return this._BrowserXhr_31; }
    if ((token === import31.ResponseOptions)) { return this._ResponseOptions_32; }
    if ((token === import122.XSRFStrategy)) { return this._XSRFStrategy_33; }
    if ((token === import32.XHRBackend)) { return this._XHRBackend_34; }
    if ((token === import33.RequestOptions)) { return this._RequestOptions_35; }
    if ((token === import123.Http)) { return this._Http_36; }
    if ((token === import34.ModalService)) { return this._ModalService_37; }
    if ((token === import35.UserInformationService)) { return this._UserInformationService_38; }
    if ((token === import1.ApplicationModule)) { return this._ApplicationModule_39; }
    if ((token === import124.LOCALE_ID)) { return this._LOCALE_ID_40; }
    if ((token === import36.NgLocalization)) { return this._NgLocalization_41; }
    if ((token === import125.ErrorHandler)) { return this._ErrorHandler_42; }
    if ((token === import37.ApplicationInitStatus)) { return this._ApplicationInitStatus_43; }
    if ((token === import38.Testability)) { return this._Testability_44; }
    if ((token === import39.ApplicationRef_)) { return this._ApplicationRef__45; }
    if ((token === import39.ApplicationRef)) { return this._ApplicationRef_46; }
    if ((token === import40.Compiler)) { return this._Compiler_47; }
    if ((token === import104.APP_ID)) { return this._APP_ID_48; }
    if ((token === import126.DOCUMENT)) { return this._DOCUMENT_49; }
    if ((token === import41.HAMMER_GESTURE_CONFIG)) { return this._HAMMER_GESTURE_CONFIG_50; }
    if ((token === import42.EVENT_MANAGER_PLUGINS)) { return this._EVENT_MANAGER_PLUGINS_51; }
    if ((token === import42.EventManager)) { return this._EventManager_52; }
    if ((token === import43.DomSharedStylesHost)) { return this._DomSharedStylesHost_53; }
    if ((token === import127.AnimationDriver)) { return this._AnimationDriver_54; }
    if ((token === import44.DomRootRenderer)) { return this._DomRootRenderer_55; }
    if ((token === import128.RootRenderer)) { return this._RootRenderer_56; }
    if ((token === import45.DomSanitizer)) { return this._DomSanitizer_57; }
    if ((token === import129.Sanitizer)) { return this._Sanitizer_58; }
    if ((token === import46.ViewUtils)) { return this._ViewUtils_59; }
    if ((token === import130.IterableDiffers)) { return this._IterableDiffers_60; }
    if ((token === import131.KeyValueDiffers)) { return this._KeyValueDiffers_61; }
    if ((token === import43.SharedStylesHost)) { return this._SharedStylesHost_62; }
    if ((token === import47.Title)) { return this._Title_63; }
    if ((token === import48.RadioControlRegistry)) { return this._RadioControlRegistry_64; }
    if ((token === import49.FormBuilder)) { return this._FormBuilder_65; }
    if ((token === import50.NgbModalStack)) { return this._NgbModalStack_66; }
    if ((token === import51.NgbModal)) { return this._NgbModal_67; }
    if ((token === import10.ROUTER_CONFIGURATION)) { return this._ROUTER_CONFIGURATION_68; }
    if ((token === import110.LocationStrategy)) { return this._LocationStrategy_69; }
    if ((token === import52.Location)) { return this._Location_70; }
    if ((token === import53.UrlSerializer)) { return this._UrlSerializer_71; }
    if ((token === import54.RouterOutletMap)) { return this._RouterOutletMap_72; }
    if ((token === import132.NgModuleFactoryLoader)) { return this._NgModuleFactoryLoader_73; }
    if ((token === import133.ROUTES)) { return this._ROUTES_74; }
    if ((token === import120.Router)) { return this._Router_75; }
    if ((token === import134.ActivatedRoute)) { return this._ActivatedRoute_76; }
    if ((token === import104.APP_BOOTSTRAP_LISTENER)) { return this._APP_BOOTSTRAP_LISTENER_77; }
    if ((token === import56.ToastsManager)) { return this._ToastsManager_78; }
    if ((token === import57.SocketService)) { return this._SocketService_79; }
    if ((token === import58.NewsService)) { return this._NewsService_80; }
    if ((token === import59.LocalStorageService)) { return this._LocalStorageService_81; }
    if ((token === import60.LocalizationService)) { return this._LocalizationService_82; }
    if ((token === import61.TeamService)) { return this._TeamService_83; }
    if ((token === import62.NgbAlertConfig)) { return this._NgbAlertConfig_84; }
    if ((token === import63.NgbProgressbarConfig)) { return this._NgbProgressbarConfig_85; }
    if ((token === import64.NgbTooltipConfig)) { return this._NgbTooltipConfig_86; }
    if ((token === import65.NgbTypeaheadConfig)) { return this._NgbTypeaheadConfig_87; }
    if ((token === import66.NgbAccordionConfig)) { return this._NgbAccordionConfig_88; }
    if ((token === import67.NgbCarouselConfig)) { return this._NgbCarouselConfig_89; }
    if ((token === import68.NgbCalendar)) { return this._NgbCalendar_90; }
    if ((token === import69.NgbDatepickerI18n)) { return this._NgbDatepickerI18n_91; }
    if ((token === import70.NgbDateParserFormatter)) { return this._NgbDateParserFormatter_92; }
    if ((token === import71.NgbDatepickerService)) { return this._NgbDatepickerService_93; }
    if ((token === import72.NgbDatepickerConfig)) { return this._NgbDatepickerConfig_94; }
    if ((token === import73.NgbDropdownConfig)) { return this._NgbDropdownConfig_95; }
    if ((token === import74.NgbPaginationConfig)) { return this._NgbPaginationConfig_96; }
    if ((token === import75.NgbPopoverConfig)) { return this._NgbPopoverConfig_97; }
    if ((token === import76.NgbRatingConfig)) { return this._NgbRatingConfig_98; }
    if ((token === import77.NgbTabsetConfig)) { return this._NgbTabsetConfig_99; }
    if ((token === import78.NgbTimepickerConfig)) { return this._NgbTimepickerConfig_100; }
    if ((token === import79.ModeService)) { return this._ModeService_101; }
    if ((token === import80.SettingsService)) { return this._SettingsService_102; }
    if ((token === import81.AuthService)) { return this._AuthService_103; }
    if ((token === import82.UserFriendsService)) { return this._UserFriendsService_104; }
    if ((token === import83.UserNotificationsService)) { return this._UserNotificationsService_105; }
    if ((token === import84.NavigatorService)) { return this._NavigatorService_106; }
    if ((token === import85.FileUploadService)) { return this._FileUploadService_107; }
    return notFoundResult;
  }
  destroyInternal():void {
    this._ApplicationRef__45.ngOnDestroy();
  }
}
export const ApplicationModuleNgFactory:import0.NgModuleFactory<import1.ApplicationModule> = new import0.NgModuleFactory(ApplicationModuleInjector,import1.ApplicationModule);